### ISSUE TITLE
Download and Favorite Playlists

### ISSUE THREAD

**Issue by fliegentoeter** [gokadzev/Musify#100]
### Describe your suggested feature

I would love to download a whole playlist at once and not click every song. Same goes for faving playlists and not just single songs.
Btw. thanks for this awesome app!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by 825i** [comment]
This is pretty infeasible and would likely result in swift action by YouTube... At the very least it would likely cause API rate limiting and/or banning. I think one song at a time is fair.

**Comment by sanctimoniousape** [comment]
> This is pretty infeasible and would likely result in swift action by YouTube... At the very least it would likely cause API rate limiting and/or banning. I think one song at a time is fair.

You can do both, can you not? User is already downloading all items anyway - they just don't want to go through the hassle of clicking every single one.  There shouldn't be any reason they can't be downloaded one at a time as if they were being played normally - you can even pace the downloads as such if need be.

I personally would also like this feature as I drive for a living and don't want to use up my cellular data allotment if I can avoid it.  I'd rather start a series of playlist downloads before I go to sleep and wake up with music ready to go for my day at work.  I work 10-12 hour days on average, so anything that can save time and hassle would be much appreciated.

**Comment by gokadzev** [comment]
> This is pretty infeasible and would likely result in swift action by YouTube... At the very least it would likely cause API rate limiting and/or banning. I think one song at a time is fair.

It's true, if we try to download all songs at the same time it will restrict us from using the api (temporary, but anyway)

**Comment by sanctimoniousape** [comment]
I think you misunderstood me.  I'm not asking for downloading all the
tracks simultaneously.  I'm merely asking to make one click to select them
all for download.  Perhaps a better way of putting it is I'm requesting an
option to "keep the tracks after they play" since they must be downloaded
to play anyway.
