### ISSUE TITLE
Can't Edit Tags

### ISSUE THREAD

**Issue by Hentilador** [gokadzev/Musify#101]
### Steps to reproduce

Download a song and then try to tag the file using an app (I use Automatag)

### Expected behavior

It should be able to edit the tags.

### Actual behavior

It says the file is corrupted yet I can still play the song but it has no tags and no album image

### Musify version

3.3.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
- [X] I will fill out all

**Comment by gokadzev** [comment]
> ### Steps to reproduce
> Download a song and then try to tag the file using an app (I use Automatag)
> 
> ### Expected behavior
> It should be able to edit the tags.
> 
> ### Actual behavior
> It says the file is corrupted yet I can still play the song but it has no tags and no album image
> 
> ### Musify version
> 3.3.0
> 
> ### Android version
> Android 11
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
> * [x]  I will fill out all

i tried fixing this, but app becomes huge (more than 100MB). so i think it doesn't worth because of just meta tags.
