### ISSUE TITLE
Does not ask for storage permission

### ISSUE THREAD

**Issue by Nesaijn** [gokadzev/Musify#102]
### Steps to reproduce

1. Download App
2. Open the App
3. Search a song
4. Download a song

### Expected behavior

It should download the song and live an indicator that it is downloading

### Actual behavior

Nothing happens.

### Musify version

3.3.0

### Android version

Android 13

### Other details

Checking the permissions, it does not have storage permissions. And since it also did not ask for it, I can't give it manually. I can only give it the permissions it asked for.
It seems that there is something wrong with the permissions settings in the app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
- [X] I will fill out all

**Comment by N3koSempai** [comment]
added this code to main.dart :

```dart
import 'package:simple_permissions/simple_permissions.dart';

PermissionStatus permissionResult = await SimplePermissions.requestPermission(Permission. WriteExternalStorage);
if (permissionResult == PermissionStatus.authorized){
   "code of read or write file in external storage (SD card)"
}
```

**Comment by gokadzev** [comment]
> add this code to main.dart :
> 
> ```dart
> import 'package:simple_permissions/simple_permissions.dart';
> 
> PermissionStatus permissionResult = await SimplePermissions.requestPermission(Permission. WriteExternalStorage);
> if (permissionResult == PermissionStatus.authorized){
>    "code of read or write file in external storage (SD card)"
> }
> ```

the dependency is pretty old, i use other dependency which works for Android 12 and below, since i made the some changes i think you will be able to grant new permissions for Android 13, but since there's not any supported dependency for Android 13 you should do it manually.
