### ISSUE TITLE
Android 13 Download Does Not Work

### ISSUE THREAD

**Issue by Nesaijn** [gokadzev/Musify#106]
### Steps to reproduce

1. Open App
2. Grant the new music and audio permissions manually (newly added here #102 ) 
3. Search a Song
4. Press the Download Button

### Expected behavior

"Download Started" Popup appears and download starts

### Actual behavior

"Download Started" Popup appears and nothing else.

### Musify version

3.4.0

### Android version

Android 13

### Other details

My first thought was that Musify still tries to download the files to /root/Musify like mentioned here #58 , which is still not possible with the music and audio permission as far as I know. If I remember correctly it only grants permission to the /root/Music folder.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
- [ ] I will fill out all

**Comment by gokadzev** [comment]
@Nesaijn does backup/restore and auto updater work? i think they need to be removed for Android 13

**Comment by Nesaijn** [comment]
@gokadzev Backup/Restore buttons do nothing. Regarding the auto updater, do you mean the "Download app update" button? If so, it says "App update is not available!". Can't check what happens when there actually is an update right now.
I tried adding a playlist and typed some random characters in their and pressed add. A loading animation appeared  and nothing else happened. I can navigate arround, close the app, force quit it and open it back, but the loading animation is still there when going back. I tried again by inputting a legit youtube id but nothing changes.

**Comment by gokadzev** [comment]
@Nesaijn check the latest version

**Comment by Nesaijn** [comment]
@gokadzev 
Pre update on 3.4.: When opening the app a notification appeared, that a new update is available. When pressing the "Download app update" button it says app update available and downloading but nothing else happens. Even after giving it permission to install unknown applications.

After update to 3.5.:
Installed the Musify.apk from GitHub releases. Going to the about page only shows me a grey page but with the normal app header. Checking version from system settings it shows that I have the 3.5 version installed.

Removing and installing the app from the apk again:
After opening the apk it asks if I want to allow network permission, granted and installed. About page still grey. When pressing the download button for a song it asks for music and audio file permissions. After granting them, nothing happens. Seems to be the same as in the version before. I also put a song in the "Music" folder and checked "Local songs" but nothing appears even after clearing the cache and restarting the app.

**Comment by gokadzev** [comment]
@Nesaijn First of all thanks for cool feedback/report about the app.

About updater (For android 12 and below) and about page: it's fixed already and i will release 3.5.1 soon.

About download/updater/local songs for Android 13, i still don't know the reason. generally these features are using flutter inbuilt functions or plugins, i guess there's problem with one of them. i will try to find the information about it.

**Comment by Nesaijn** [comment]
@gokadzev You are welcome and I am happy to see your appreciation!

Since we came to a dead end I checked logcat and these lines appeared when pressing the download button:

```
10-19 13:06:30.722 13099 13099 D permissions_handler: No permissions found in manifest for: []15
10-19 13:06:30.723 13099 13099 D permissions_handler: No permissions found in manifest for: []15
10-19 13:06:30.723 13099 13099 D permissions_handler: No permissions found in manifest for: []18
10-19 13:06:30.723 13099 13099 D permissions_handler: No android specific permissions needed for: 6
10-19 13:06:30.725 13099 13099 D permissions_handler: No permissions found in manifest for: []15
10-19 13:06:30.727 13099 13099 D permissions_handler: No permissions found in manifest for: []15
10-19 13:06:30.740 13099 13099 D permissions_handler: No permissions found in manifest for: []15
10-19 13:06:30.742 13099 13169 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: something went wrong
10-19 13:06:30.742 13099 13169 E flutter : #0      ExtStorageProvider.getExtStorage (package:musify/services/ext_storage.dart:54)
10-19 13:06:30.742 13099 13169 E flutter : <asynchronous suspension>
10-19 13:06:30.742 13099 13169 E flutter : #1      downloadSong (package:musify/services/download_manager.dart:45)
10-19 13:06:30.742 13099 13169 E flutter : <asynchronous suspension>
10-19 13:06:30.742 13099 13169 E flutter : 
```

**Comment by 825i** [comment]
Yeah download doesn't work at all for Android 13. All apps in Android 13 need to ask for "Full storage" permissions when saving files. So you'll need to mark that permission into the app.

**Comment by 825i** [comment]
Still broken on 3.7.0, released on 6.12.22

I've granted all possible permissions and nothing is working.

**Comment by Nesaijn** [comment]
https://stackoverflow.com/questions/72310162/how-do-i-request-push-notification-permissions-for-android-13

Here the accepted answer did additionaly add `compileSdkVersion 33` to `defaultConfig`

Which would be here? I think?
https://github.com/gokadzev/Musify/blob/c3aa6a8a3a96318bf5f9592e7d9dce1dd264e04e/android/app/build.gradle#L58

**Comment by gokadzev** [comment]
> https://stackoverflow.com/questions/72310162/how-do-i-request-push-notification-permissions-for-android-13
> 
> Here the accepted answer did additionaly add `compileSdkVersion 33` to `defaultConfig`
> 
> Which would be here? I think?
> 
> https://github.com/gokadzev/Musify/blob/c3aa6a8a3a96318bf5f9592e7d9dce1dd264e04e/android/app/build.gradle#L58

problem is the way app gets download folder path, it won't work

**Comment by gokadzev** [comment]
@Nesaijn check the latest version

**Comment by Nesaijn** [comment]
I kinda approve that it works.
What is confusing though is that there is no indication that it is downloading. Checking the previously chosen folder after a while shows the file. But it is not appearing in the "Downloaded Songs" or "Local Songs" windows of the app. Even after restarting the app.

But I guess the main issue is finally solved 🎉 Thank you!
