### ISSUE TITLE
Some Unicode characters do not display

### ISSUE THREAD

**Issue by 825i** [gokadzev/Musify#107]
Some Unicode characters do not display.

See the screenshot below:
https://i.imgur.com/19QEa8k.jpg

This is what should be displayed:

ᴘ v ʟ ᴇ (XLIEXCRYXDIEX) - ᴜ ʐ ɪ
https://www.youtube.com/watch?v=7KjGDr5LNvA

This is by no means a serious bug, but it does make it nearly impossible to find or recognise many vapourware songs.

**Comment by denzhaummer** [comment]
also the letters "ş-ğ" do not display

**Comment by 825i** [comment]
Stilla present on v3.7.0 released on 6.12.22
