### ISSUE TITLE
Opening links in the app stops background music

### ISSUE THREAD

**Issue by 825i** [gokadzev/Musify#108]
For example, going to "About" and opening the developer's Github profile, loads Github in the app which stops the music.

You should just elect to serve the link to an external browser app on the user's phone. Another good reason for this is because now whilst I am on Github. I have no way back to the application music menu. Unless I kill the app and open it again.

This is not so much a bug as it is a QoL improvement.

**Comment by gokadzev** [comment]
could you attach app logs here?
