### ISSUE TITLE
Dynamic theme 

### ISSUE THREAD

**Issue by owencz1998** [gokadzev/Musify#113]
### Describe your suggested feature

Uses album colors for the theme looks nice.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by gokadzev** [comment]
Hello, if you have Android 12 / Android 12.1 / Android 13 dynamic theming is added in the latest version but according to your wallpaper/system color. setting app color with album color isn't the good idea because it will change so frequently and effect on app perfomance.

**Comment by owencz1998** [comment]
No worries thanks for your work 👍
