### ISSUE TITLE
Songs on the playlist tab don't play

### ISSUE THREAD

**Issue by 825i** [gokadzev/Musify#115]
Check the video. Some of the songs on the playlist tab don't play. Tapping on them sends you back to the list of playlists again.

https://www.veed.io/view/d90156bd-b945-48f4-9081-c8e7c289e020?sharingWidget=true&panel=share

**Comment by 825i** [comment]
This is still an issue with 3.7.0 which was released 220467 6.12.22

**Comment by gokadzev** [comment]
> This is still an issue with 3.7.0 which was released 220467 6.12.22

maybe they're restricted by youtube, this problem shouldn't be related to the app.
