### ISSUE TITLE
Add thumbnail support

### ISSUE THREAD

**Issue by max5354** [gokadzev/Musify#12]
Add thumbnail support. Whenever we search something it shows default image. So plz improve that and add support of thumbnail.

**Comment by gokadzev** [comment]
> Add thumbnail support. Whenever we search something it shows default image. So plz improve that and add support of thumbnail.

i think that would be useless as well, thumbnails are showed on important places like player and mini player. just another thing to decrease app perfomance for no reason (it may won't be noticable but anyway)
