### ISSUE TITLE
[Feature] Don't kick user back to "More" page after selecting playlist song

### ISSUE THREAD

**Issue by 825i** [gokadzev/Musify#121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

Logical Improvements

### Credits

Me

### Pain

When tapping a song in the playlist, it kicks you back to the "more" page to start playing the song.

### Suggested Solution

The app should stay where it is. On the playlist page and just play the song. Similar to basically all other music apps. Instead of taking the user somewhere they didn't expect to go.

### Useful resources/references

This is a similar improvement to #105

In that the user should stay on the playlist page and see evidence of the song they are playing directly in the list. Like Apple Music does:

![Screenshot_20221207_020325_Apple Music](https://user-images.githubusercontent.com/58630825/206052572-318dcec6-3cdd-4e59-ad3a-5737371c1ca0.jpg)

**Comment by gokadzev** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Category of the Feature
> Logical Improvements
> 
> ### Credits
> Me
> 
> ### Pain
> When tapping a song in the playlist, it kicks you back to the "more" page to start playing the song.
> 
> ### Suggested Solution
> The app should stay where it is. On the playlist page and just play the song. Similar to basically all other music apps. Instead of taking the user somewhere they didn't expect to go.
> 
> ### Useful resources/references
> This is a similar improvement to #105
> 
> In that the user should stay on the playlist page and see evidence of the song they are playing directly in the list. Like Apple Music does:
> 
> ![Screenshot_20221207_020325_Apple Music](https://user-images.githubusercontent.com/58630825/206052572-318dcec6-3cdd-4e59-ad3a-5737371c1ca0.jpg)

well, that's the problem actually. i can change code and you won't be kicked back to the other page after clicking on any song but now playing tab won't be visible.

**Comment by gokadzev** [comment]
> > ### Is there an existing issue for this?
> > 
> > * [x]   I have searched the existing issues
> > 
> > ### Category of the Feature
> > Logical Improvements
> > ### Credits
> > Me
> > ### Pain
> > When tapping a song in the playlist, it kicks you back to the "more" page to start playing the song.
> > ### Suggested Solution
> > The app should stay where it is. On the playlist page and just play the song. Similar to basically all other music apps. Instead of taking the user somewhere they didn't expect to go.
> > ### Useful resources/references
> > This is a similar improvement to #105
> > In that the user should stay on the playlist page and see evidence of the song they are playing directly in the list. Like Apple Music does:
> > ![Screenshot_20221207_020325_Apple Music](https://user-images.githubusercontent.com/58630825/206052572-318dcec6-3cdd-4e59-ad3a-5737371c1ca0.jpg)
> 
> well, that's the problem actually. i can change code and you won't be kicked back to the other page after clicking on any song but now playing tab won't be visible.

nvm, it's possible. idk how yet but anyway, i will try to change the code.
