### ISSUE TITLE
Linux app not working 

### ISSUE THREAD

**Issue by Adithyan007hack** [gokadzev/Musify#122]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
- [X] I will fill out all

### Current Behavior

After installing the app it should show in app drawer but it is not showing and when I try to open it using terminal it also not working 
![2022-12-07_20-31](https://user-images.githubusercontent.com/87800041/206213820-5e300136-215e-49d7-a06d-8bf5635eb3d2.png)
As you can see above musify is installed 

### Expected Behavior

I should install and work as expexted

### Steps To Reproduce

1. Install the app
2. launch it using terminal or app drawer
3. But it is not showing in app drawer and not working using terminal

### Musify Version

Linux Version (Alpha) V3.6.0

### Operating System Version

Zorin os (Ubuntu 20.04 )

**Comment by gokadzev** [comment]
@Adithyan007hack it seems like the dependency had problem, release is updated (not .deb anymore but follow instructions and enjoy)
