### ISSUE TITLE
> Hello, the app uses YouTube as the main source of music.

### ISSUE THREAD

**Issue by victor10100111001** [gokadzev/Musify#124]
> Hello, the app uses YouTube as the main source of music.

You mention that YouTune is the main source. Does that mean there are other sources? Do you plan to include something like p2p :)

_Originally posted by @victor10100111001 in https://github.com/gokadzev/Musify/issues/123#issuecomment-1345626722_

**Comment by gokadzev** [comment]
> ```
>     > Hello, the app uses YouTube as the main source of music.
> ```
> 
> You mention that YouTune is the main source. Does that mean there are other sources? Do you plan to include something like p2p :)
> 
> _Originally posted by @victor10100111001 in [#123 (comment)](https://github.com/gokadzev/Musify/issues/123#issuecomment-1345626722)_

there's not planned adding any other source at the moment.
