### ISSUE TITLE
[Bug] Eliminate duplicate on F-Droid

### ISSUE THREAD

**Issue by Korb** [gokadzev/Musify#128]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
- [X] I will fill out all

### Current Behavior

Among the repositories on F-Droid are two copies of this application:
https://f-droid.org/packages/com.gokadzev.musify/ and https://f-droid.org/packages/me.musify/

### Expected Behavior

This application exists in the F-Droid catalogs in a single copy.

### Steps To Reproduce

Open F-Droid app, search "Musify"

### Musify Version

3.7.0

### Operating System Version

Android 13

### Additional information

![Screenshot_2023_0103_084853](https://user-images.githubusercontent.com/3509797/210306050-f8be128b-82d7-4167-8df2-eb87bc2f9f65.jpg)
![Screenshot_2023_0103_084930](https://user-images.githubusercontent.com/3509797/210306063-b68b50cb-8bdf-48e2-aa7f-9c0b13f75e95.jpg)

**Comment by gokadzev** [comment]
i don't see any problem there, i think it's obvious which is the latest one, isn't it?

**Comment by Korb** [comment]
> i think it's obvious which is the latest one?

You are right, it is obvious when compared. But if you just go to a non-updatable page and install the app from there, the app will not be updated through the F-Droid app. For example, if the user saw the "wrong" page in the recommendations, or they sent him a direct link to it, or it was the first in the search results... - there are many reasons.

**Comment by gokadzev** [comment]
> > i think it's obvious which is the latest one?
> 
> You are right, it is obvious when compared. But if you just go to a non-updatable page and install the app from there, the app will not be updated through the F-Droid app. For example, if the user saw the "wrong" page in the recommendations, or they sent him a direct link to it, or it was the first in the search results... - there are many reasons.

okay, let's tag @IzzySoft and see if there's any solution for that :)

**Comment by IzzySoft** [comment]
I cannot confirm the issue: both of the above links give a 404 to me. Going by the screenshots you rather meant my repo I guess? There `me.musify` is marked for removal due to "rebranding". As usual, there's an overlap period to give users of the old version a chance to realize and switch to the new app; once the old app is removed that pointer is gone. That said, removal would happen within the next few days, it was scheduled for this week.

**Comment by Korb** [comment]
I confirm the solution to the problem. I just updated all the repositories in the F-Droid app, and now the search for "musify" returns the only app with that name, "[Musify (Music Streaming and Downloading app)](https://f-droid.org/packages/com.gokadzev.musify/)".
