### ISSUE TITLE
Whitelist and blacklist for offline Music 

### ISSUE THREAD

**Issue by anujithpp** [gokadzev/Musify#133]
Add blacklist or whitelist for offline songs recording and others things are also shown it's irritating

**Comment by gokadzev** [comment]
> Add blacklist or whitelist for offline songs recording and others things are also shown it's irritating

check the latest version, you don't need custom blacklist and whitelist anymore, it does that job automatically :)

**Comment by anujithpp** [comment]
> > Add blacklist or whitelist for offline songs recording and others things are also shown it's irritating
> 
> check the latest version, you don't need custom blacklist and whitelist anymore, it does that job automatically :)

Bro new version also shows call recordings and WhatsApp audio in offline song section
