### ISSUE TITLE
[Bug] < Notification takes a long time to appear and cause the music to stop when exiting the app>

### ISSUE THREAD

**Issue by Tysina** [gokadzev/Musify#143]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
- [X] I will fill out all

### Current Behavior

The notification takes between 7 and 15 seconds to appear. which results in stopping the music when closing the app. But everything works fine after the notification appears. This issue happens to both online and offline song .

### Expected Behavior

The notification should appear immediately when playing a song  .

### Steps To Reproduce

1.Open the App
2.play any track 
3.when song is playing you won't see the  music notification. Then close  or exit the app.
4.The song you were playing will stop. 

### Musify Version

V4.0.1

### Operating System Version

Android 12

**Comment by DarkCrypt** [comment]
Notification takes 1-1:30 min to appear for me, v4.1.0 on Android 13.

**Comment by gokadzev** [comment]
@Tysina @DarkCrypt check the latest version

**Comment by Tysina** [comment]
The problem is still there but better now .

**Comment by DarkCrypt** [comment]
Still issue for me too, v4.2.0. I have notifications and foreground turned on. I experimented by playing more of an assortment of different songs and I'm experiencing notification wait times of 30 secs - 4 mins.

**Comment by gokadzev** [comment]
@Tysina @DarkCrypt  Could you check how's it in v4.3.0?

**Comment by DarkCrypt** [comment]
Still same issue, v4.3.0. Notification wait time varies widely like before.

New issue also:
Play song from search results and song plays but when selecting different song nothing happens. I can officially post as new issue if you want.

**Comment by gokadzev** [comment]
> Still same issue, v4.3.0. Notification wait time varies widely like before.
> 
> New issues also:
> 
> 1. Play song from search results and song plays but when selecting different song nothing happens.
> 2. When I open app, it always says new update available.
> 
> I can officially post as new issues if you want.

okay, i will re-release 4.3.0.

**Comment by DarkCrypt** [comment]
Re-release fixed 1 & 2.

**Comment by gokadzev** [comment]
@Tysina check everything and tell me if it works good: https://github.com/gokadzev/Musify/releases/tag/master

**Comment by DarkCrypt** [comment]
Notification starts instantly when playing song, v.4.4.0 Beta. Nice work! 👍

> 2. When I open app, it always says new update available.

This came back.

**Comment by Tysina** [comment]
Thank you so much @gokadzev
