### ISSUE TITLE
[Feature] <On search  change the keyboard IME_ACTION_DONE to IME_ACTION_SEARCH >

### ISSUE THREAD

**Issue by Tysina** [gokadzev/Musify#144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Credits

Me

### Pain

The Ime option done is confusing 

### Suggested Solution

By chaging the keyboard IME_ACTION_DONE to IME_ACTION_SEARCH will help improve the UI .As it will remove search icon next to the edite text in the search bar .

### Useful resources/references

Link :https://stackoverflow.com/questions/3205339/android-how-to-make-keyboard-enter-button-say-search-and-handle-its-click

**Comment by gokadzev** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Category of the Feature
> _No response_
> 
> ### Credits
> Me
> 
> ### Pain
> The Ime option done is confusing
> 
> ### Suggested Solution
> By chaging the keyboard IME_ACTION_DONE to IME_ACTION_SEARCH will help improve the UI .As it will remove search icon next to the edite text in the search bar .
> 
> ### Useful resources/references
> Link :https://stackoverflow.com/questions/3205339/android-how-to-make-keyboard-enter-button-say-search-and-handle-its-click

@Tysina sorry, i don't understand what do you mean, could you explain me what's the problem? also as  i understood above mentioned things are available in java/kotlin and here we use flutter.

**Comment by Tysina** [comment]
Sorry, I don't  know flutter . But the two  screenshots will help explain what i meant by Done to Search icon on the keyboard  . 

Before : ![Screenshot_20230207-211111](https://user-images.githubusercontent.com/77760220/217386921-5eb8aafd-238c-43e6-8777-c5c3518ba0ae.jpg)

After  : ![Screenshot_20230207-211059_Google](https://user-images.githubusercontent.com/77760220/217386927-4edf8274-a598-4805-baf7-27def24bc008.jpg)

Here is the solution I found  from stockover flow https://stackoverflow.com/questions/50107284/how-do-i-change-text-input-action-button-return-enter-key-on-keyboard-in-flutt

**Comment by gokadzev** [comment]
> Sorry, I don't know flutter . But the two screenshots will help explain what i meant by Done to Search icon on the keyboard .
> 
> Before : ![Screenshot_20230207-211111](https://user-images.githubusercontent.com/77760220/217386921-5eb8aafd-238c-43e6-8777-c5c3518ba0ae.jpg)
> 
> After : ![Screenshot_20230207-211059_Google](https://user-images.githubusercontent.com/77760220/217386927-4edf8274-a598-4805-baf7-27def24bc008.jpg)
> 
> Here is the solution I found from stockover flow https://stackoverflow.com/questions/50107284/how-do-i-change-text-input-action-button-return-enter-key-on-keyboard-in-flutt

isn't after version better than before?

**Comment by Tysina** [comment]
Yes. It make the search Ui look clean and simple .
Just like the example below 
![WipeOut02_09_2023_010209 630000](https://user-images.githubusercontent.com/77760220/217671490-2c7e966b-8376-40e0-b5cd-5eda68b20356.jpg)

**Comment by gokadzev** [comment]
> Yes. It make the search Ui look clean and simple . Just like the example below ![WipeOut02_09_2023_010209 630000](https://user-images.githubusercontent.com/77760220/217671490-2c7e966b-8376-40e0-b5cd-5eda68b20356.jpg)

okay then, it will be changed in the next release. thank you for good suggestion
