### ISSUE TITLE
Make square thumbnail with gradient color

### ISSUE THREAD

**Issue by max5354** [gokadzev/Musify#15]
When we play songs. The thumbnail becomes zoomed. Plz fix that. Make it square with gradient color. I know in YouTube all thumbnails are "landscape" so when we zoom out thumbnail than it will become "landscape". so i have an idea. Just make "square" thumbnail. Make top and bottom of thumbnail with color matching "gradient color". Plz don't use solid colors. YouTube music uses solid color and its looks bad. So plz use color matching gradient color to make square thumbnail. For reference screenshot already attached.
![1655587898788](https://user-images.githubusercontent.com/90886938/174457780-91692ec8-f78f-496d-ad85-53697a8290a2.png)

**Comment by gokadzev** [comment]
app isn't youtube music clone or something to make everything like youtube music has. about landscape, currently only portrait mode is supported.

**Comment by max5354** [comment]
> app isn't youtube music clone or something to make everything like youtube music has. about landscape, currently only portrait mode is supported.

But you can see "ymusic" thumbnail for reference. It show all type of landscape thumbnail by making it square. Only my mean is that the zoomed thumbnail is looks bad that's why i am requesting you to make it square just like ymusic does.

**Comment by max5354** [comment]
> app isn't youtube music clone or something to make everything like youtube music has. about landscape, currently only portrait mode is supported.

But you can see "ymusic" thumbnail for reference. It show all type of landscape thumbnail by making it square. Only my mean is that the zoomed thumbnail is looks bad that's why i am requesting you to make it square just like ymusic does.

**Comment by gokadzev** [comment]
> > app isn't youtube music clone or something to make everything like youtube music has. about landscape, currently only portrait mode is supported.
> 
> But you can see "ymusic" thumbnail for reference. It show all type of landscape thumbnail by making it square. Only my mean is that the zoomed thumbnail is looks bad that's why i am requesting you to make it square just like ymusic does.

it would not fit to app design also i think current version is good.
