### ISSUE TITLE
[Bug] Multiple Player Buttons Not Working

### ISSUE THREAD

**Issue by DarkCrypt** [gokadzev/Musify#156]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
- [X] I will fill out all

### Current Behavior

Multiple player buttons not working, see screenshots.

![IMG_20230211_023354](https://user-images.githubusercontent.com/121076677/218249481-f04da1e5-047d-4008-a418-513915e10b80.jpg)

![IMG_20230211_030220](https://user-images.githubusercontent.com/121076677/218250030-c508b124-a225-4a26-a7d4-b144dc983e14.jpg)

### Expected Behavior

All buttons work correctly.

### Steps To Reproduce

Play any song and use the buttons.

### Musify Version

V4.3.0

### Operating System Version

Android 13

**Comment by gokadzev** [comment]
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
> * [x]  I will fill out all
> 
> ### Current Behavior
> Multiple player buttons not working, see screenshots.
> 
> ![IMG_20230211_023354](https://user-images.githubusercontent.com/121076677/218249481-f04da1e5-047d-4008-a418-513915e10b80.jpg)
> 
> ![IMG_20230211_030220](https://user-images.githubusercontent.com/121076677/218250030-c508b124-a225-4a26-a7d4-b144dc983e14.jpg)
> 
> ### Expected Behavior
> All buttons work correctly.
> 
> ### Steps To Reproduce
> Play any song and use the buttons.
> 
> ### Musify Version
> V4.3.0
> 
> ### Operating System Version
> Android 13
> 
> ### Additional information
> _No response_

if you can test pre-release fully and tell me about the all problems which you will find (shortly: if you want to be tester who try to find all problems)  tell me and i will add pre-release on releases page for you and then wait for your feedback.

**Comment by gokadzev** [comment]
@DarkCrypt check everything and tell me if it works: https://github.com/gokadzev/Musify/releases/tag/master

**Comment by DarkCrypt** [comment]
Still issues, v4.4.0 Beta. Added all screenshots of notifications also.

![IMG_20230211_160509](https://user-images.githubusercontent.com/121076677/218283725-039e4d94-73ec-4026-a19c-a3e1a55e3de3.jpg)

1. Shuffle button doesn't highlight when pressed like others and doesn't work.
2. Not sure what this button does? Doesn't seem to do anything.
* Play button on left(not sure what it does) is gone, compare previous screenshot.
* **All other buttons work, even download!** 👍

![IMG_20230211_160736](https://user-images.githubusercontent.com/121076677/218284032-4849c166-f872-43a8-8465-7681dead9918.jpg)

No buttons work and no close button now, compare previous screenshot.
**Seekbar works.**

![Screenshot_2023-02-11-15-59-38-58_60d40bf597786c9bfd90ecfc534f1982](https://user-images.githubusercontent.com/121076677/218284167-d2e1a473-25e9-4fab-afa3-65fcd5ba285b.jpg)

**Play button works** but no other options.

![Screenshot_2023-02-11-15-59-50-58](https://user-images.githubusercontent.com/121076677/218284218-82f264c4-7d57-49b4-8bc5-4484e12388d7.jpg)

**Both buttons work** but no other options.

**Comment by gokadzev** [comment]
> Still issues, v4.4.0 Beta. Added all screenshots of notifications also.
> 
> ![IMG_20230211_160509](https://user-images.githubusercontent.com/121076677/218283725-039e4d94-73ec-4026-a19c-a3e1a55e3de3.jpg)
> 
> 1. Shuffle button doesn't highlight when pressed like others and doesn't work.
> 2. Not sure what this button does? Doesn't seem to do anything.
> 
> * Play button on left(not sure what it does) is gone, compare previous screenshot.
> * **All other buttons work, even download!** +1
> 
> ![IMG_20230211_160736](https://user-images.githubusercontent.com/121076677/218284032-4849c166-f872-43a8-8465-7681dead9918.jpg)
> 
> No buttons work and no close button now, compare previous screenshot. **Seekbar works.**
> 
> ![Screenshot_2023-02-11-15-59-38-58_60d40bf597786c9bfd90ecfc534f1982](https://user-images.githubusercontent.com/121076677/218284167-d2e1a473-25e9-4fab-afa3-65fcd5ba285b.jpg)
> 
> **Play button works** but no other options.
> 
> ![Screenshot_2023-02-11-15-59-50-58](https://user-images.githubusercontent.com/121076677/218284218-82f264c4-7d57-49b4-8bc5-4484e12388d7.jpg)
> 
> **Both buttons work** but no other options.

on the firs screenshot, second button generates random song before current song ends (before 5 seconds), i will check what's wrong with the shuffle button.

with the new implementation previous and next buttons are available only for local songs (with play all button), since youtube doesn't provide pre-generated static links for us we can't add all songs at once in queue (but from player page, i managed it with custom implementation so they work)

about one button which disappeared, that was sponsorblock feature which i removed.

if notification appears (which wasn't appearing or appearing but with big delay) and most of player buttons are fixed, i think we should prefer the new implementation.

**Comment by DarkCrypt** [comment]
Ok, yeah notifications appeared instantly and more player buttons are functional. Let's give it a shot.

**Comment by DarkCrypt** [comment]
The only player button issues with v4.4.0: 

Shuffle button not working(which you're trying to figure out), it does highlight when pressed.

Mute button works but doesn't highlight when pressed.

**Comment by gokadzev** [comment]
> The only player button issues with v4.4.0:
> 
> Shuffle button not working(which you're trying to figure out), it does highlight when pressed.
> 
> Mute button works but doesn't highlight when pressed.

About the mute button, it's known for me. shuffle should work with only local songs (with the Play All button) since it uses queue

**Comment by DarkCrypt** [comment]
I have a list of 10 songs in user liked songs. I hit play all button to start the playlist and then hit shuffle after 1st song started playing. I let it play 6 songs before I stopped it because it was playing songs straight down the list as normal and didn't shuffle. App should of shuffled after 1st song.
