### ISSUE TITLE
Playlists not working

### ISSUE THREAD

**Issue by test2a** [gokadzev/Musify#157]
When first song starts to play, it ends but it plays again without going to next song.

Clicking on any other song or playlist, the first song plays. 

Sharing screen record in a bit. 

Also, a question, does the search use YouTube or Spotify or other music app search ?

**Comment by gokadzev** [comment]
> When first song starts to play, it ends but it plays again without going to next song.
> 
> Clicking on any other song or playlist, the first song plays.
> 
> Sharing screen record in a bit.
> 
> Also, a question, does the search use YouTube or Spotify or other music app search ?

Hello, you need to play it with "play all" button, otherwise it plays single song. The search function uses YouTube.

**Comment by test2a** [comment]
Looks like I was on 4.3.0. Updated to latest from github and that worked.
