### ISSUE TITLE
Bug: i need to uninstall old version to install latest version

### ISSUE THREAD

**Issue by max5354** [gokadzev/Musify#17]
I have always need to uninstall installed app to install latest app. It's confusing😂😂 look i already installed musify app. But if i trying to install new update then it gives error "app not installed" so i need to uninstall old version and after install new update than after it works properly. So plz solve this bug. It's happening with musify app only.

**Comment by gokadzev** [comment]
> I have always need to uninstall installed app to install latest app. It's confusingjoyjoy look i already installed musify app. But if i trying to install new update then it gives error "app not installed" so i need to uninstall old version and after install new update than after it works properly. So plz solve this bug. It's happening with musify app only.

i'm informed about this, i just don't know why this is happening.

**Comment by citizenserious** [comment]
At izzys repo there is a new signaturen with every new version, therefore I have to reinstall it to update, maybe this is related?

**Comment by gokadzev** [comment]
> At izzys repo there is a new signaturen with every new version, therefore I have to reinstall it to update, maybe this is related? "The new version is signed with a different key to the old one"

Thank you for useful information, since i know the reason of this, i'm closing the issue.
