### ISSUE TITLE
[Bug] musify not play local song

### ISSUE THREAD

**Issue by NSTAdventure** [gokadzev/Musify#170]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
- [X] I will fill out all

### Current Behavior

Musify will never play my specific music 
That already downloaded using others tools

### Expected Behavior

It should play any local music.

### Steps To Reproduce

1. Open musify go to setting
2. Change local music folder to folder contain music
3. Try to play music that not downloaded using musify and musify refuse to play it 

### Musify Version

4.5.0

### Operating System Version

Android 10

### Additional information

![Screenshot_2023-02-17-07-37-55-53](https://user-images.githubusercontent.com/50813528/219520442-a210a21c-ecce-4c72-876a-1d0ff087ebb6.jpg)
Ss of musify refuse to load "specific" of my downloaded music (from others sc)

Here music that it won't play on musify app 
https://file.io/9Q0klwiPbda5

Other music that stored locally on my devices regadless how i can download it are able to play in musify

**Comment by gokadzev** [comment]
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
> * [x]  I will fill out all
> 
> ### Current Behavior
> Musify will never play downloaded song from / using other tools or app even the file music is mp3
> 
> ### Expected Behavior
> It should play any local music regadless from where or what tools i use to download
> 
> ### Steps To Reproduce
> 1. Open musify go to setting
> 2. Change local music folder to folder contain music
> 3. Try to play music that not downloaded using musify and musify refuse to play it
> 
> ### Musify Version
> 4.5.0
> 
> ### Operating System Version
> Android 10
> 
> ### Additional information
> ![Screenshot_2023-02-17-07-37-55-53](https://user-images.githubusercontent.com/50813528/219520442-a210a21c-ecce-4c72-876a-1d0ff087ebb6.jpg) Ss of musify refuse to load my music that downloaded using other tools beside musify

Hello, i use Android 12 and it plays even non-mp3 files. could you send me the logs to see why does it happen?

**Comment by NSTAdventure** [comment]
> > ### Acknowledgements
> > 
> > * [x]   I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> > * [x]   I have written a short but informative title.
> > * [x]   I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
> > * [x]   I will fill out all
> > 
> > ### Current Behavior
> > Musify will never play downloaded song from / using other tools or app even the file music is mp3
> > ### Expected Behavior
> > It should play any local music regadless from where or what tools i use to download
> > ### Steps To Reproduce
> > 
> > 1. Open musify go to setting
> > 2. Change local music folder to folder contain music
> > 3. Try to play music that not downloaded using musify and musify refuse to play it
> > 
> > ### Musify Version
> > 4.5.0
> > ### Operating System Version
> > Android 10
> > ### Additional information
> > ![Screenshot_2023-02-17-07-37-55-53](https://user-images.githubusercontent.com/50813528/219520442-a210a21c-ecce-4c72-876a-1d0ff087ebb6.jpg) Ss of musify refuse to load my music that downloaded using other tools beside musify
> 
> Hello, i use Android 12 and it plays even non-mp3 files. could you send me the logs to see why does it happen?

Aaaaaa dev how i can get the log? Without adb i hope

**Comment by gokadzev** [comment]
also check the latest version

**Comment by DarkCrypt** [comment]
The only way to not use adb is a rooted device like gokadzev said. App logger still requires adb to grant READ_LOGS permission for non rooted device. Adb using computer to device is actually really easy. I went through all this myself not long ago.

**Comment by DarkCrypt** [comment]
@NSTAdventure
I'm super curious... if the newest version doesn't work, try old [v2.0](https://github.com/gokadzev/Musify/releases/tag/2.0.0) and see if local and downloaded songs appear in app. So far this is the last version that worked for me. I can't be the only one.

**Comment by DarkCrypt** [comment]
@NSTAdventure 
Thumbs up... does that mean you tried old v2.0 and it worked for you?

**Comment by NSTAdventure** [comment]
> @NSTAdventure Thumbs up... does that mean you tried old v2.0 and it worked for you?

I still trying for now 
But these settings page is annoying 
How i can change local folder in that version?

**Comment by DarkCrypt** [comment]
I'm not the dev, gokadzev is. I was just wondering if that older version would work for you like it worked for me. I apologize for the bad recommendation.

**Comment by NSTAdventure** [comment]
> I'm not the dev, gokadzev is.

Ok sorry i thought you was dev too

>I was just wondering if that older version would work for you like it worked for me. I apologize for the bad recommendation.

It's ok

Anyway is there a ADB app that can catch log in android? (Foss one i hope)

**Comment by DarkCrypt** [comment]
It's all good friend. I like to try to help people anyway I can but unfortunately sometimes it doesn't work out like I hoped, haha.

To help answer your question, [Matlog](https://github.com/pluxoid/matlog) is a great FOSS logcat reader. Of course logs work best for rooted devices because of system level access. If your device is non rooted you will need to do a simple adb command to grant access for the logcat app to read logs. You will only need grant access 1 time and then your good to go.

**Comment by NSTAdventure** [comment]
>You will only need grant access 1 time and then your good to go.

Access granted what next?

**Comment by DarkCrypt** [comment]
Ok, after granting access with adb...when you open Matlog it'll ask you eveytime to allow one time access or don't allow. You can read the info to see why but hit allow. Now it'll load(sometimes it takes a few secs to kick in) and you'll start seeing it logging. It's insane, there's alot going on.

In the top bar you'll see pause(which controls play too) and a 3 dot dropdown menu with options. You can save logs as a zip file or txt file. I usually save logs as txt and send them to devs. You can also open saved logs and view them with Matlog.

Once you hit allow and it starts logging you can go open whatever app you need logs for and reproduce the issue. Matlog should log all the activity your doing. When your done hit pause in Matlog so it doesn't keep logging and save the log with whatever name you want to call it. Then send it to dev. (Matlog will save logs to Matlog folder in storage)

To be honest, I don't have much experience with log readers on device. I usually do adb logs with computer.

**Comment by DarkCrypt** [comment]
Adb logs with computer is pretty easy. Since you already have adb and know how to connect device with USB debugging to grant access to Matlog, I could easily walk you through adb logs on computer if you'd like?

**Comment by NSTAdventure** [comment]
> Adb logs with computer is pretty easy. Since you already have adb and know how to connect device with USB debugging to grant access to Matlog, I could easily walk you through adb logs on computer if you'd like?

Setup donei just need to try figure out before catching any logs 

Note:
OEM rom may affect this

**Comment by NSTAdventure** [comment]
Issues revamped

**Comment by DarkCrypt** [comment]
> Setup donei just need to try figure out before catching any logs
>
> Note:
> OEM rom may affect this

Ok, you really only need to know step 3-5. But I included all steps just because...

1. (You already know this step)
Connect device to computer and enable USB debugging in order to communicate with adb. Some devices also need to disable permission monitoring(before enabling USB debugging).
2. (You already know this step too)
Open Powershell or whatever you need to do to access adb to type commands.
3. To make sure device is communicating with adb type this command and hit enter:

adb devices

The output should tell you that your device is connected.
4. Now you can start collecting logs. Type this command and hit enter:

adb shell logcat > whatevertextyouwant.txt

*Adb will instantly start collecting logs*. After starting this command you can go open whatever app you need logs for and reproduce the issue.

5. After you are done collecting logs, stop logcat process by pressing ctrl + c. Adb will save the logs as whatever txt file you named it to your computer.
6. Send txt file to dev.

**Comment by gokadzev** [comment]
@NSTAdventure Try to change the name of the music file, if it doesn't work then send me a logs.

**Comment by DarkCrypt** [comment]
@NSTAdventure
> Try to change the name of the music file, if it doesn't work then send me a logs.

Adding to gokadzev's comment...
You're issue was initially posted for v4.5.0. Gokadzev did come out with a newer release, [v4.7.0](https://github.com/gokadzev/Musify/releases), which includes a bunch of fixes for all devices. You can give that release a try and see if it's better for you. I think he's working on another upcoming release as well.

Like gokadzev said, you may have to edit the filename of songs for them to appear in app. This works for me with v4.7.0.

**Comment by gokadzev** [comment]
closing this issue because of no response, feel free to reopen it with the logs related to your problem

**Comment by NSTAdventure** [comment]
> @NSTAdventure
> > Try to change the name of the music file, if it doesn't work then send me a logs.
> 
> Adding to gokadzev's comment...
> You're issue was initially posted for v4.5.0. Gokadzev did come out with a newer release which includes a bunch of fixes for all devices. You can give that release a try and see if it's better for you.
> 
> Like gokadzev said, you may have to edit the filename of songs for them to appear in app. This works for me.

I willing to giving logcat but my darn borrowed laptop will never want to working together to me 
![IMG20230321183148.jpg](https://user-images.githubusercontent.com/50813528/226594255-974d8ae8-c7ae-40b7-87fa-ea83a658a4a1.jpg)

This happened every day every darn day 🗿

**Comment by gokadzev** [comment]
> > @NSTAdventure
> > > Try to change the name of the music file, if it doesn't work then send me a logs.
> > 
> > 
> > Adding to gokadzev's comment...
> > You're issue was initially posted for v4.5.0. Gokadzev did come out with a newer release which includes a bunch of fixes for all devices. You can give that release a try and see if it's better for you.
> > Like gokadzev said, you may have to edit the filename of songs for them to appear in app. This works for me.
> 
> I willing to giving logcat but my borrowed laptop will never want to working together to me ![IMG_20230321_183526](https://user-images.githubusercontent.com/50813528/226598481-a691fc67-7891-4641-be76-b573d8011039.jpg)
> 
> So i will provide log from matlog libre instead [2023-03-21-19-00-05.txt](https://github.com/gokadzev/Musify/files/11028001/2023-03-21-19-00-05.txt)
> 
> @gokadzev

Unfortunately there's nothing related to Musify in this logs.
