### ISSUE TITLE
[Bug] opening app info on startup

### ISSUE THREAD

**Issue by ThaRealJozef** [gokadzev/Musify#175]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
- [X] I will fill out all

### Current Behavior

When i open the app it redirects me to the app info (uninstall, force close, permissions, etc...), then i have to press back to access the app. 

### Expected Behavior

Open the app normally. 

### Musify Version

all of them

### Operating System Version

Android 13

**Comment by gokadzev** [comment]
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
> * [x]  I will fill out all
> 
> ### Current Behavior
> When i open the app it redirects me to the app info (uninstall, force close, permissions, etc...), then i have to press back to access the app.
> 
> ### Expected Behavior
> Open the app normally.
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Musify Version
> all of them
> 
> ### Operating System Version
> Android 13
> 
> ### Additional information
> _No response_

It happens when you have declined asked permissions, make sure you've given all necessary permissions.

**Comment by DarkCrypt** [comment]
V4.6.1 is doing this before and after granting permissions. Every single time opening app. I included this issue in comment [#127](https://github.com/gokadzev/Musify/issues/127#issuecomment-1442498336), number 3.

**Comment by gokadzev** [comment]
@ThaRealJozef @DarkCrypt check the latest beta version and tell me if it's fixed: https://github.com/gokadzev/Musify/releases/tag/master

**Comment by BNX070** [comment]
> @ThaRealJozef @DarkCrypt check the latest beta version and tell me if it's fixed: https://github.com/gokadzev/Musify/releases/tag/master

Finally! A working version for AOSP.
Thank You <3

**Comment by DarkCrypt** [comment]
Yes, this issue is fixed. App not going to app info screen anymore.
