### ISSUE TITLE
Download feature doesn't work

### ISSUE THREAD

**Issue by RodrigoZid** [gokadzev/Musify#184]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
- [X] I will fill out all

### Current Behavior

When I select the option to download a music track, it keeps asking for the folder but doesn't download the track. The same thing happens when I go to settings and select the download folder, it asks for the folder over and over again.

### Expected Behavior

It should start downloading after selecting the folder.

### Musify Version

4.8.0

### Operating System Version

Android 12

**Comment by gokadzev** [comment]
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
> * [x]  I will fill out all
> 
> ### Current Behavior
> When I select the option to download a music track, it keeps asking for the folder but doesn't download the track. The same thing happens when I go to settings and select the download folder, it asks for the folder over and over again.
> 
> ### Expected Behavior
> It should start downloading after selecting the folder.
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Musify Version
> 4.8.0
> 
> ### Operating System Version
> Android 12
> 
> ### Additional information
> _No response_

Hello, i need logs to see what's the problem

**Comment by gokadzev** [comment]
also make sure you choose folder like a "Music" for download or create new one.
