### ISSUE TITLE
[Bug] <Title null  and Download error >

### ISSUE THREAD

**Issue by Tysina** [gokadzev/Musify#185]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
- [X] I will fill out all

### Current Behavior

![Screenshot_20230311-030033](https://user-images.githubusercontent.com/77760220/224543011-92d9f431-4264-4af4-927c-ab1d8a157712.jpg)
![Screenshot_20230311-030204](https://user-images.githubusercontent.com/77760220/224543018-468e37a0-dcd0-4f92-aac1-e2a616927bef.jpg)

The Download future is not working properly for both up-dating  the app Both updating the app and downloading music are having problems with the Download future. After downloading, a failure message appears. Moreover, it occasionally fails to function at all.

### Expected Behavior

It shouldn't show null in the song title  or fail to download music and app update . 

### Steps To Reproduce

1. Open the app 
2. click any song 
3. Click the download icon to download 
4. Wait 
5. And you will see the message 

### Musify Version

V4.8.0

### Operating System Version

Android 12

### Additional information

Please add  in-app update after Downloading the apk

**Comment by gokadzev** [comment]
You need to clear app cache (as i mentioned #184) and it will be fixed. about download make sure your music download folder is "Music" and app download folder is "Documents" or "Downloads"

**Comment by Tysina** [comment]
The solution is not work, it still show null .

**Comment by gokadzev** [comment]
> The solution is not work, it still show null .

try to redownload the app
