### ISSUE TITLE
Bug: notification seekbar don't showing

### ISSUE THREAD

**Issue by max5354** [gokadzev/Musify#19]
Seekbar of notification is not showing. Inow there's a seekbar but it's not showing properly means seekbar's color is not changing with album art.
![Screenshot_20220619-190405](https://user-images.githubusercontent.com/90886938/174483998-5ce75c12-94d0-44c6-a3db-83270d48368d.jpg)

**Comment by gokadzev** [comment]
@max5354 that's plugin related, i can't do anything with that. also it works for me (Android 11- Android 12)

https://github.com/ryanheise/just_audio
