### ISSUE TITLE
[Feature] <Can I contribute to translation into Arabic?>

### ISSUE THREAD

**Issue by muhammadbahaa2001** [gokadzev/Musify#190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

UI Improvements

### Credits

Me

### Pain

I understand English but I perfer to see Arabic in Musify.

### Suggested Solution

I can add Arabic just if you agree.

**Comment by gokadzev** [comment]
@muhammadbahaa2001 sure, i'm just not sure if it works without any changes, since Arabic writing is from right to left but anyway, open pull request with Arabic translations and then we will see what we need :)

**Comment by muhammadbahaa2001** [comment]
OK, how can I start? Shouldn't I have string.xml or something similar? I added the Arabic language to many other open source projects, and all that happened was that the interface became horizontally flipped (the positions of the menus and buttons were swapped, and everything is fine and correct).

**Comment by gokadzev** [comment]
> @gokadzev OK, how can I start? Shouldn't I have string.xml or something similar? By this way I added the Arabic language to many other open source projects, and all that happened was that the interface became horizontally inverted (the positions of the menus and buttons were swapped, and everything is fine and correct and no need to change anything).

yes, so this is your template : https://github.com/gokadzev/Musify/blob/master/lib/localization/app_en.arb

add file app_ar.arb in localizations folder, copy and paste everything from template and change only second side. i will do everything else after you finish and make a pull requests

**Comment by gokadzev** [comment]
@muhammadbahaa2001 try this build and tell me how correct arabic language is showed: https://github.com/gokadzev/Musify/releases/tag/master
