### ISSUE TITLE
[Bug] Multiple Downloads Fail over LTE

### ISSUE THREAD

**Issue by DeMoN100** [gokadzev/Musify#195]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
- [X] I will fill out all

### Current Behavior

When queueing more then one download all downloads will fail. First download begins for a few minutes then just fails every download.

### Expected Behavior

First one downloads, next one starts then downloads.

### Steps To Reproduce

Queue multiple downloads any song.

### Musify Version

4.8.0

### Operating System Version

Android 13

**Comment by gokadzev** [comment]
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
> * [x]  I will fill out all
> 
> ### Current Behavior
> When queueing more then one download all downloads will fail. First download begins for a few minutes then just fails every download.
> 
> ### Expected Behavior
> First one downloads, next one starts then downloads.
> 
> ### Steps To Reproduce
> Queue multiple downloads any song.
> 
> ### Musify Version
> 4.8.0
> 
> ### Operating System Version
> Android 13
> 
> ### Additional information
> _No response_

currently app doesn't support multiple downloads feature, this can be added for V5.0.0 too, will see...

**Comment by gokadzev** [comment]
Update: i tried to download 4 songs at the same time and it worked.

**Comment by DeMoN100** [comment]
What service do you have maybe it's got something to do with working with specific providers?

**Comment by gokadzev** [comment]
Closing the issue, because it works for me and i think it's something related to the provider. If you feel that's not right, feel free to reopen issue and tell me more details why do you think so :)
