### ISSUE TITLE
[Bug] .MP3 filetype error.

### ISSUE THREAD

**Issue by DeMoN100** [gokadzev/Musify#196]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
- [X] I will fill out all

### Current Behavior

This has happened with every song I try to download. i'm not sure if this happens with other formats or not.
I always have to convert the file to fix this.

Every mp3 I download initially does not work. No music player will be able to play them & I have to use an online converter or Axiom to convert it. Sometimes these mp3s will convert & I convert them to mp3 the ffmpeg liblame format & then they work just fine.

Other times they won't convert at all & just keeo returning the error mp3 @ 0xe8ad0000 header missing while decoding stream #0:0: Invalid data found when processing input.

### Expected Behavior

Mp3's encoded in the liblame ffmpeg fornat as referenced here.

http://ffmpeg.org/ffmpeg-codecs.html#libmp3lame-1

### Steps To Reproduce

Download a song on wifi.
try to play on any music player.

### Musify Version

4.8.0

### Operating System Version

Android 13

### Additional information

I think this has to do with the way you have the mp3's encoded.

**Comment by DeMoN100** [comment]
I uploaded an mp3 from the Musify app that I downloaded incase you want to analyze it. It expires in 14 days if you need me to reupload it or send you a different one that didn't work I can.

https://transfer.sh/KRNQ0z/70s-greatest-hits-best-oldies-songs-of-1970s-oldies-but-goodies.mp3

**Comment by gokadzev** [comment]
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
> * [x]  I will fill out all
> 
> ### Current Behavior
> This has happened with every song I try to download. i'm not sure if this happens with other formats or not. I always have to convert the file to fix this.
> 
> Every mp3 I download initially does not work. No music player will be able to play them & I have to use an online converter or Axiom to convert it. Sometimes these mp3s will convert & I convert them to mp3 the ffmpeg liblame format & then they work just fine.
> 
> Other times they won't convert at all & just keeo returning the error mp3 @ 0xe8ad0000 header missing while decoding stream #0:0: Invalid data found when processing input.
> 
> ### Expected Behavior
> Mp3's encoded in the liblame ffmpeg fornat as referenced here.
> 
> http://ffmpeg.org/ffmpeg-codecs.html#libmp3lame-1
> 
> ### Steps To Reproduce
> Download a song on wifi. try to play on any music player.
> 
> ### Musify Version
> 4.8.0
> 
> ### Operating System Version
> Android 13
> 
> ### Additional information
> I think this has to do with the way you have the mp3's encoded.

Yes, this issue is known for me but since Musify is able to play these downloaded files, i haven't changed anything + i wanted to have support for lower android devices too (which isn't possible with ffmpeg). will see, maybe it can be added for V5.0.0

**Comment by DeMoN100** [comment]
Well having ffmpeg isn't really what's causing this I recommend encoding them in the LAME Mp3 fornat which you can get the resources here.

https://lame.sourceforge.io/
https://sourceforge.net/projects/lame/

If it helps better to just analyze the encoding of one that already works & just rewrite it I suppose you could download any song online in mp3.
Here's one https://oshi.at/msME
