### ISSUE TITLE
Bug: lyrics is not showing

### ISSUE THREAD

**Issue by max5354** [gokadzev/Musify#20]
Look i played one song that have lyrics in youtube music and youtube so as a result i can see that songs lyrics. But when played that song in musify app than it don't showing that songs lyrics. So in short lyrics button is not working properly or lyrics button don't fetching lyrics.

**Comment by gokadzev** [comment]
> Look i played one song that have lyrics in youtube music and youtube so as a result i can see that songs lyrics. But when played that song in musify app than it don't showing that songs lyrics. So in short lyrics button is not working properly or lyrics button don't fetching lyrics.

app doesn't use youtube or youtube music for lyrics, so it's normal.
