### ISSUE TITLE
Can't play all songs of suggested playlists, making them useless

### ISSUE THREAD

**Issue by Screenshared** [gokadzev/Musify#21]
Basically all playlists can't be played now as play all button has been removed for performance issues.
It worked alright for me, but without that , i have to manually play all songs.

**Comment by gokadzev** [comment]
> Basically all playlists can't be played now as play all button has been removed for performance issues. It worked alright for me, but without that , i have to manually play all songs.

actually, it isn't removed permanently.it was working good before but since last change it needed refactor, after refactor one playlist needed minutes to load so i preferred to remove it, i will try to add it back soon as possible.
