### ISSUE TITLE
[Bug] In-App Updater Android 13

### ISSUE THREAD

**Issue by DarkCrypt** [gokadzev/Musify#212]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
- [X] I will fill out all

### Current Behavior

Every time I open the app I'm asked to select a download folder to download an app update. I select folder for download and app tells me downloading update but always fails. This process reciprocates on every app launch.

### Expected Behavior

App should only ask to select download folder for app update at first launch, not every time the app is opened. If there's an actual app update to download, app should download update properly and not fail. There should be no app update at this time since app is up to date with most recent version.

### Steps To Reproduce

Reproduce:
1. Open app
2. App asks to select download folder for app update.
3. Select folder and app says downloading update.
4. Download notification says failed.
5. Process reciprocates on every app launch.

### Musify Version

V5.1.0

### Operating System Version

Android 13

### Additional information

This issue is a fresh install of V5.1.0 on Android 13 from releases page.

**Comment by gokadzev** [comment]
@DarkCrypt Hello, can you try to reopen the app now?

**Comment by DarkCrypt** [comment]
Reopened app and issue is fixed. That was fast! Thank you friend.
