### ISSUE TITLE
Recommended songs not playing

### ISSUE THREAD

**Issue by lovwanshichetan** [gokadzev/Musify#245]
### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
- [X] I will fill out all

### Current Behavior

Some "Recommended for you" songs aren't playing even after tapping multiple times.
I had attached an video recording of same. 
Also, why there is not bug report section in app itself?

https://github.com/gokadzev/Musify/assets/98891600/61a29762-5945-4061-acb9-6138668c75c1

### Expected Behavior

1. Songs should be played on just on tap.
2. App should have log catcher or bug report section.

### Steps To Reproduce

1. Click any song in "recommended for you" section.
2. If it not play try again.
3. If not then try others.
4. Last song will definitely get played unlike top ones.

### Musify Version

v5.3.0

### Operating System Version

Android 12

**Comment by gokadzev** [comment]
@lovwanshichetan It works, try clearing the app cache with in-built feature.

**Comment by lovwanshichetan** [comment]
It still not worked. I guess it's OneUI issue.

**Comment by gokadzev** [comment]
About logger, There are already added some error notifications but currently i can't add log reader/exporter feature. I'm not able to add a lots of things because of the time and low spec PC. contributions are always welcome.

**Comment by gokadzev** [comment]
> It still not worked. I guess it's OneUI issue.

If you export logs with adb and give me, i will look and see what's the problem (if it's visible)
