### ISSUE TITLE
[Bug] UI unresponsive 

### ISSUE THREAD

**Issue by sahalkabeer** [gokadzev/Musify#247]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
- [X] I will fill out all

### Current Behavior

When click on a playlist or search it doesn't respond only the bottom navigation bar works. It works for a few minutes when i restart the app and again becomes unresponsive.

### Expected Behavior

To run smoothly like a normal app. 

### Steps To Reproduce

Add your own playlist from youtube 
Switch between tabs with navigation
Try to open another playlist you saved, it won't respond

### Musify Version

5.3.0

### Operating System Version

Android 12

### Additional information

S10 Exynos

**Comment by gokadzev** [comment]
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
> * [x]  I will fill out all
> 
> ### Current Behavior
> When click on a playlist or search it doesn't respond only the bottom navigation bar works. It works for a few minutes when i restart the app and again becomes unresponsive.
> 
> ### Expected Behavior
> To run smoothly like a normal app.
> 
> ### Steps To Reproduce
> Add your own playlist from youtube Switch between tabs with navigation Try to open another playlist you saved, it won't respond
> 
> ### Musify Version
> 5.3.0
> 
> ### Operating System Version
> Android 12
> 
> ### Additional information
> S10 Exynos

Described issue isn't active for me, could you try changing phone screen refresh rate and tell me if anything changes?

**Comment by sahalkabeer** [comment]
S10 comes with a 60Hz panel, can't change it.

**Comment by gokadzev** [comment]
> S10 comes with a 60Hz panel, can't change it.

It's okay. Could you try this version? : https://github.com/gokadzev/Musify/releases/tag/4.7.0 (Uninstall the current installed app because this version is older than the current one)

**Comment by sahalkabeer** [comment]
Here is a screen recording, as mentioned only the bottom navigation works.

**Comment by sahalkabeer** [comment]
> > S10 comes with a 60Hz panel, can't change it.
> 
> It's okay. Could you try this version? : https://github.com/gokadzev/Musify/releases/tag/4.7.0 (Uninstall the current installed app because this version is older)

I tried this version, same issue after couple of mins

**Comment by gokadzev** [comment]
It must be flutter problem which I can't fix (Maybe not with samsung but exynos chipset), because it doesn't happen on other devices.
