### ISSUE TITLE
add support proxy [ Feature request ]

### ISSUE THREAD

**Issue by Stu75e** [gokadzev/Musify#249]
add support proxy like socks5 or http in app 🙏
We have to bypass the entire device through a vpn tunnel. With this feature, we can use this feature only in this program.

**Comment by gokadzev** [comment]
Not possible. and even if it is, I'm sure it will cause tons of problems, since even now we have slow download problem and so on, I'd like to avoid adding this. Thank you for sharing your idea anyways.
