### ISSUE TITLE
[Feature] Sparepart Share result

### ISSUE THREAD

**Issue by axolotlextnd** [gokadzev/Musify#250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

UI Improvements

### Credits

Sandira

### Pain

I feel confused when using the search feature because music from YouTube Videos is mixed with music from YouTube Music

### Suggested Solution

make a difference tab between source from youtube video and youtube music

**Comment by gokadzev** [comment]
@axolotlextnd Hello, they aren't mixed. the app uses only one source and thats YouTube.
