### ISSUE TITLE
[Bug] <Dowloads are failing: failed status>

### ISSUE THREAD

**Issue by painkiller1717** [gokadzev/Musify#251]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
- [X] I will fill out all

### Current Behavior

I can't download songs. I could in the previous version but now when I try, starts download but then it failed. I already tried 5-6 times with differents songs.

Btw this is an amazing project💯 Congratulations and thank you!! 🙌👏🙏

### Expected Behavior

The expected behavior is the downloads being completed.

### Musify Version

v5.4.0

### Operating System Version

Android 12

**Comment by gokadzev** [comment]
@painkiller1717 Hello, does it show any error? and also which folder did you choose as a download folder?

**Comment by painkiller1717** [comment]
> @painkiller1717 Hello, does it show any error? and also which folder did you choose as a download folder?

Starts to download, but before it completes shows failed which substitute the progress bar on the notifications. My download folder is /storage/emulated/0/Music but I could download some songs in the previous version.

**Comment by gokadzev** [comment]
> > @painkiller1717 Hello, does it show any error? and also which folder did you choose as a download folder?
> 
> Starts to download, but before it completes shows failed which substitute the progress bar on the notifications. My download folder is /storage/emulated/0/Music but I could download some songs in the previous version.

Could you tell me which was the last version where you tested and it worked?

**Comment by painkiller1717** [comment]
> > > @painkiller1717 Hello, does it show any error? and also which folder did you choose as a download folder?
> > 
> > Starts to download, but before it completes shows failed which substitute the progress bar on the notifications. My download folder is /storage/emulated/0/Music but I could download some songs in the previous version.
> 
> Could you tell me which was the last version where you tested and it worked?

The previous version, 5.3.0 which was the first version when I saw your app

**Comment by gokadzev** [comment]
> > > > @painkiller1717 Hello, does it show any error? and also which folder did you choose as a download folder?
> > > 
> > > 
> > > Starts to download, but before it completes shows failed which substitute the progress bar on the notifications. My download folder is /storage/emulated/0/Music but I could download some songs in the previous version.
> > 
> > 
> > Could you tell me which was the last version where you tested and it worked?
> 
> The previous version, 5.3.0 which was the first version when I saw your app

Thank you for your response. It should be fixed in 5.5.0

**Comment by painkiller1717** [comment]
Great!! Thank you mate.
