### ISSUE TITLE
Don't work backup in Android 13

### ISSUE THREAD

**Issue by calatorius** [gokadzev/Musify#255]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

When I try to make a backup it give me that error:
![Screenshot_20230629_124710](https://github.com/gokadzev/Musify/assets/79602779/164aab29-f3fb-46e8-8932-78494977b550)
I tried in several locations, external memory, internal memory, always the same.
I can confirm the app have the permission to write media and when I select the folder I give the permission to manage that folder , so, that's no the problem.
In other thing when I make the backup in android 8 it works but the file have too much  information. I deleted search history, cache and all, and it repeats the same line several times.
https://pastebin.com/y1AZ2yAL
This is the backup with 5 song marked favourite and after clean cache and search history

### Expected Behavior

Resolve the probhem

### Musify Version

5.5.0

### Operating System Version

android 13

**Comment by marcossmtp** [comment]
same for me

**Comment by gokadzev** [comment]
It works, you just need to choose "Documents" folder, otherwise it won't work because of Android 13 restrictions.

**Comment by gokadzev** [comment]
> In other thing when I make the backup in android 8 it works but the file have too much information. I deleted search history, cache and all, and it repeats the same line several times. https://pastebin.com/y1AZ2yAL This is the backup with 5 song marked favourite and after clean cache and search history

About that, don't edit backup content. it's not cache, the app doesn't backup cache, all these info are user and settings info.

**Comment by marcossmtp** [comment]
yes, but in other apps I have in android 13 when they need to store something it ask for permission to write in the folder and it writte without problem in any folder of the phone. 
In other case I think @calatorius is refering that deleting history search and only having 5 songs is a lot of information repeated, I see the same template in my case. Why if history search is deleted appears repeated many times the same entry?

**Comment by calatorius** [comment]
Yes, I was refering at the amount of the same data repeated when I deleted the search history.
And like it said by @marcossmtp perhaps if the app get the permission of storage and not media it allows to choose the folder to download songs and backups.

**Comment by gokadzev** [comment]
About repeating data I need more information, because I really didn't understand the problem. About access on other folders too, I prefer to follow Android restrictions and give app control on folders according to the android rules, we already had some permission and download connected issues and I don't want to mess up things again.

**Comment by calatorius** [comment]
> About repeating data I need more information, because I really didn't understand the problem. About access on other folders too, I prefer to follow Android restrictions and give app control on folders according to the android rules, we already had some permission and download connected issues and I don't want to mess up things again.

This two screenshots are after clear history search and the song destiny is all I have onlv added one time to favorites.
![Screenshot_20230629-214355_MiXplorer](https://github.com/gokadzev/Musify/assets/79602779/688e5d1c-ec39-46e2-9a77-b96ce417e417)
![Screenshot_20230629-214438_MiXplorer](https://github.com/gokadzev/Musify/assets/79602779/d6bcca7b-3223-4cde-aaad-faf1c1df3ad2)

**Comment by gokadzev** [comment]
> > About repeating data I need more information, because I really didn't understand the problem. About access on other folders too, I prefer to follow Android restrictions and give app control on folders according to the android rules, we already had some permission and download connected issues and I don't want to mess up things again.
> 
> This two screenshots are after clear history search and the song destiny is all I have onlv added one time to favorites. ![Screenshot_20230629-214355_MiXplorer](https://user-images.githubusercontent.com/79602779/249881275-688e5d1c-ec39-46e2-9a77-b96ce417e417.jpg) ![Screenshot_20230629-214438_MiXplorer](https://user-images.githubusercontent.com/79602779/249881365-d6bcca7b-3223-4cde-aaad-faf1c1df3ad2.jpg)

Does it show this song several time in the app after restoring this backup file too?

**Comment by marcossmtp** [comment]
no, only in the backup, that's why I can understand why it is repeated several times in the backup in favorites and in search history , more if I make the backup after delete all search history.

**Comment by calatorius** [comment]
yes its my case too

**Comment by gokadzev** [comment]
> no, only in the backup, that's why I can understand why it is repeated several times in the backup in favorites and in search history , more if I make the backup after delete all search history.

If it's only in backup file content and it doesn't affect data when you restore in the app, then there's nothing to worry about

**Comment by calatorius** [comment]
ok, it was only curiosity about the reason of that.
Thanks

**Comment by gokadzev** [comment]
> ok, it was only curiosity about the reason of that. Thanks

Actually I don't know which encoder or file opener did you use to open backup file that way but by default when I tried to open it there were lot's of cubes with text, I think because of in-built encryption of Musify storage implementation that uses hive. There's possibility that it's duplicated because of your file-opener and decoder, if there were really saved repeated same data in backup file it would be appeared in the app too.

**Comment by calatorius** [comment]
i use mixplorer to edit the file, and the file is 21.3kb that matchs with the text that shows, and it would be too much for no history search and only 5 songs in favorites.
But I'm with you that if not affected at the app only all is ok.

**Comment by marcossmtp** [comment]
well I have a backup of 15 songs in favourites and it grow from 20kb to 600kb, why as much information about.
Its not possible use json or yaml instead of hive format to store backups?
It would more clear and really less space of storage

**Comment by calatorius** [comment]
yes, I'm in the same oppinion.

**Comment by gokadzev** [comment]
I will definitely review the backup implementation and everything to check if I missed anything. If I find nothing, then I will think about a new solution.

**Comment by marcossmtp** [comment]
ok thanks

**Comment by gokadzev** [comment]
So, I'm checking now, and it works correctly. The reason why it's a bit bigger than it should be is that when you like a song, it adds recently played songs as well, and both recently played and liked songs are backed up.

**Comment by gokadzev** [comment]
Backed up 2 liked songs (+2 recently played songs), and the backup file is 1.39KB. It's possible that JSON or YAML files will be bigger than that due to additional symbols and other factors.

As a solution, I see two options: either removing recently played songs from the backup, or modifying the code so that when you like a song, it won't be added to the recently played list.

**Comment by gokadzev** [comment]
That's it, all necessary changes are made. Backup file size will be less than half of current file size in the next release.

**Comment by marcossmtp** [comment]
very nice to heard that
thank you very much

**Comment by marcossmtp** [comment]
> Backed up 2 liked songs (+2 recently played songs), and the backup file is 1.39KB. It's possible that JSON or YAML files will be bigger than that due to additional symbols and other factors.

json and yaml has the advantage of clear format to read it and can access your data more easier than with hiven database format, but probably it fill more space about symbols.
yaml is really a very human readable format.
But it was only a idea if database app continues with problems with the backup. Happy to heard that all is ok.
Thanks one more time

**Comment by gokadzev** [comment]
> > Backed up 2 liked songs (+2 recently played songs), and the backup file is 1.39KB. It's possible that JSON or YAML files will be bigger than that due to additional symbols and other factors.
> 
> json and yaml has the advantage of clear format to read it and can access your data more easier than with hiven database format, but probably it fill more space about symbols. yaml is really a very human readable format. But it was only a idea if database app continues with problems with the backup. Happy to heard that all is ok. Thanks one more time

I'm sure it will lead to lots of problems, including instability and I/O issues. Otherwise, I would definitely consider this feedback and implement it. Since the whole app is working with this implementation without any major problems, it's better if we leave it as it is.

**Comment by marcossmtp** [comment]
> > > Backed up 2 liked songs (+2 recently played songs), and the backup file is 1.39KB. It's possible that JSON or YAML files will be bigger than that due to additional symbols and other factors.
> > 
> > json and yaml has the advantage of clear format to read it and can access your data more easier than with hiven database format, but probably it fill more space about symbols. yaml is really a very human readable format. But it was only a idea if database app continues with problems with the backup. Happy to heard that all is ok. Thanks one more time
> 
> I'm sure it will lead to lots of problems, including instability and I/O issues. Otherwise, I would definitely consider this feedback and implement it. Since the whole app is working with this implementation without any major problems, it's better if we leave it as it is.
> 

ok
the important thing is that things works not the method used to work.
So, It's nice that the backup now works correctly now.
