### ISSUE TITLE
Fastlane changelogs too long

### ISSUE THREAD

**Issue by IzzySoft** [gokadzev/Musify#262]
Fastlane changelogs are limited to 500 char each. Your latest 2 for `en-US` exceed that limit. Please make sure to stay within :wink: Thanks!

**Comment by gokadzev** [comment]
> Fastlane changelogs are limited to 500 char each. Your latest 2 for `en-US` exceed that limit. Please make sure to stay within wink Thanks!

Sorry, it's corrected now. I guess I don't need to write a full changelog in general, since it's available on GitHub too. It's impossible to write a detailed changelog in just 500 characters.

**Comment by IzzySoft** [comment]
Sure. Fastlane per-release changelogs are intended to just hold the "most interesting" parts, They are usually shown "inline" (e.g. the official F-Droid client shows them directly appended to the description). Whoever wants the full details can of course come here for them. Thanks!

**Comment by IzzySoft** [comment]
Thanks!

**Comment by IzzySoft** [comment]
@gokadzev Oops, this time it's the short description, which will be truncated to 80 chars – making this an "all-in-one A" :see_no_evil:

**Comment by gokadzev** [comment]
> @gokadzev Oops, this time it's the short description, which will be truncated to 80 chars – making this an "all-in-one A" 🙈

Changed :white_check_mark: Thanks!

**Comment by IzzySoft** [comment]
Thanks!
