### ISSUE TITLE
[Bug] Playlists do not refresh

### ISSUE THREAD

**Issue by VSvir** [gokadzev/Musify#263]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

When I add new music to my playlists, it doesn't show up in Musify, neither do deleted songs disappear from a playlist. Reopening the program or readding a playlist doesn't help

![Снимок экрана 2023-07-18 191326](https://github.com/gokadzev/Musify/assets/90447390/82253719-f128-490f-b4bb-9ce78930a290)
![0iw1oHPIIIs](https://github.com/gokadzev/Musify/assets/90447390/1782503b-ea15-4b9e-ad47-656c6a840078)

### Expected Behavior

Newly added music should appear in playlist and deleted songs should be withdrawn

### Steps To Reproduce

1. Add user's playlist via playlist ID
2. Add some songs to the playlist
3. Newly added songs won't be shown in Musify (it seems like the first added song will appear if a playlist was empty before, but others won't)
4. Try to delete some songs, and they'll still be in playlist in Musify

### Musify Version

v6.0.0

### Operating System Version

Android 12

**Comment by gokadzev** [comment]
> ### Acknowledgements
> * [x]  I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
> * [x]  I will fill out all the sections in this issue report.
> 
> ### Current Behavior
> When I add new music to my playlists, it doesn't show up in Musify, neither do deleted songs disappear from a playlist. Reopening the program or readding a playlist doesn't help
> 
> ![Снимок экрана 2023-07-18 191326](https://user-images.githubusercontent.com/90447390/254327739-82253719-f128-490f-b4bb-9ce78930a290.png) ![0iw1oHPIIIs](https://user-images.githubusercontent.com/90447390/254328085-1782503b-ea15-4b9e-ad47-656c6a840078.jpg)
> 
> ### Expected Behavior
> Newly added music should appear in playlist and deleted songs should be withdrawn
> 
> ### Steps To Reproduce
> 1. Add user's playlist via playlist ID
> 2. Add some songs to the playlist
> 3. Newly added songs won't be shown in Musify (it seems like the first added song will appear if a playlist was empty before, but others won't)
> 4. Try to delete some songs, and they'll still be in playlist in Musify
> 
> ### Musify Version
> v6.0.0
> 
> ### Operating System Version
> Android 12
> 
> ### Additional Information
> _No response_

Hello, it's because of caches. As a temporary solution, clear the cache using the built-in feature, and it will update the list. I think I will add an "Update caches" or something similar on the playlist page to be able to update it without clearing all caches.
