### ISSUE TITLE
[Feature] Return to previous screen via bottom tab

### ISSUE THREAD

**Issue by VSvir** [gokadzev/Musify#264]
### Is there an existing issue for this?

- [X] I have searched the existing issues and confirmed that this feature is not already requested.

### Category of the Feature

UI Improvements

### Credits

-

### Pain

When using this app, I intuitively try to return to section's main screen by tapping its icon on the bottom tab, but now it does nothing and I need to change sections or tap a return arrow

### Suggested Solution

Make current section's icon interactive so it would return you to main screen of section. e.g. when I'm in _More/Recently Played_ and tap _More_, I return back to _More_ page

**Comment by gokadzev** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues and confirmed that this feature is not already requested.
> 
> ### Category of the Feature
> UI Improvements
> 
> ### Credits
> 
> ### Pain
> When using this app, I intuitively try to return to section's main screen by tapping its icon on the bottom tab, but now it does nothing and I need to change sections or tap a return arrow
> 
> ### Suggested Solution
> Make current section's icon interactive so it would return you to main screen of section. e.g. when I'm in _More/Recently Played_ and tap _More_, I return back to _More_ page
> 
> ### Useful Resources/References
> _No response_

But it has a back button on the app bar as it's a sub-page of the "More" category. The bottom bar is used to move between main pages.

**Comment by VSvir** [comment]
I know there's a back button at the top, but imho it's not really convenient to reach for it whenever you need to go back. Of course, it may be just me as no one seemed to complain

**Comment by gokadzev** [comment]
@VSvir Hello, It will be available in the next release :)
