### ISSUE TITLE
Bottom music controller

### ISSUE THREAD

**Issue by MehdiAhmadiyan** [gokadzev/Musify#269]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

Hello, Good time
I have faced an issue that is related to bottom music controller
Whenever you play a song and minimise the page, there is something appeared in bottom that you can either pause the music or maximize it again
But neither pause button nor maximize button work 

### Expected Behavior

The buttons should do their job as it's set before

### Musify Version

v6.0.0

### Operating System Version

Android 13

**Comment by gokadzev** [comment]
@MehdiAhmadiyan Hello, could you attach the screenshots? to be clear what you mean

**Comment by MehdiAhmadiyan** [comment]
> 

![Screenshot_20230724-163818_Musify](https://github.com/gokadzev/Musify/assets/110778376/566b40f5-3503-4cbb-806d-b70391df4adf)
When you play a music, you can then minimize it as you can see in photo
There is two approach for doing that
The first is to press on minimize button on the top left
The second is two do it with the back navigation of your phone
When you use the second approach, the app just freeze and nothing work instead the music keep playing

**Comment by MehdiAhmadiyan** [comment]
> 

How can I find the logs?

**Comment by gokadzev** [comment]
@MehdiAhmadiyan Before logs, please any version before V6.0.0 and tell me if it's the same
