### ISSUE TITLE
[Question] Music is low quality

### ISSUE THREAD

**Issue by mkujer** [gokadzev/Musify#272]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

If you open the app and download a song it will be downloaded in a very low quality bitrate  < 150kbps. No matter the choice of file format. 

### Expected Behavior

Download a song and enjoy it in full quality

### Steps To Reproduce

1. open Musify
2. download any song with any file Format
3. song will be low quality

### Musify Version

v6.0.0

### Operating System Version

Android 13

### Additional Information

I suspect the low quality of the songs is an result of the main source of music (YouTube) musify uses. YouTube doesnt support flac files or for the matter of fact doesnt support full quality 320kbps MP3.
All downloads as a result will end up with an subpar audio birate and not be full quality.

**Comment by gokadzev** [comment]
@mkujer Hello, you're absolutely right. Downloaded files have low quality but using app implementation, it's better when you play these files or stream music online in Musify. About FLAC it's mentioned in F.A.Q too that it's for some compatibility and not having any quality effect.

**Comment by gokadzev** [comment]
> > @mkujer Hello, you're absolutely right. Downloaded files have low quality, but using the app implementation, it's better when you play these files or stream music online in Musify. As for FLAC, it's mentioned in the F.A.Q that it's for improving compatibility and does not have any impact on the audio quality.
> 
> Umm i didn't understand what you said actually?

I mean max quality is 256kbps, flac and other things are just for changing file extension for different purposes, it has nothing with audio file quality.

**Comment by vehosah** [comment]
> > > @mkujer Hello, you're absolutely right. Downloaded files have low quality, but using the app implementation, it's better when you play these files or stream music online in Musify. As for FLAC, it's mentioned in the F.A.Q that it's for improving compatibility and does not have any impact on the audio quality.
> > 
> > 
> > Umm i didn't understand what you said actually?
> 
> I mean max quality is 256kbps, flac and other things are just for changing file extension for different purposes, it has nothing with audio file quality.

I don't know the, delete the options for flac

**Comment by gokadzev** [comment]
> > > > @mkujer Hello, you're absolutely right. Downloaded files have low quality, but using the app implementation, it's better when you play these files or stream music online in Musify. As for FLAC, it's mentioned in the F.A.Q that it's for improving compatibility and does not have any impact on the audio quality.
> > > 
> > > 
> > > Umm i didn't understand what you said actually?
> > 
> > 
> > I mean max quality is 256kbps, flac and other things are just for changing file extension for different purposes, it has nothing with audio file quality.
> 
> I don't know then, delete the options for flac

It is already deleted if you're using the latest version :)
