### ISSUE TITLE
Android TV support 

### ISSUE THREAD

**Issue by RobotsAreCrazy** [gokadzev/Musify#280]
### Is there an existing issue for this?

- [X] I have searched the existing issues and confirmed that this feature is not already requested.

### Credits

RobotsAreCrazy

### Pain

Support for android TV as currently only meant for phones etc

### Suggested Solution

Please can you add support for installing on Android TV so it is in landscape if used on that platform?

Thankyou

**Comment by ashes-xda** [comment]
That Would be awesome

**Comment by DarkCrypt** [comment]
There's support for d-pad navigation in Flutter.

I found an old Spotify tv mod that's working on Android TV 10 if anyone wants to try it out.

**Comment by DarkCrypt** [comment]
All very good points.

> I can't test it

You can't test on physical device or emulator?

**Comment by gokadzev** [comment]
> All very good points.
> 
> > I can't test it
> 
> You can't test on physical device or emulator?

Maybe only responsiveness, remote controls and Android TV specific things no.
