### ISSUE TITLE
[Feature] (persistante) music queue / local playlist 

### ISSUE THREAD

**Issue by fanf** [gokadzev/Musify#284]
### Is there an existing issue for this?

- [X] I have searched the existing issues and confirmed that this feature is not already requested.

### Credits

Me

### Pain

I'm not able to put several music in queue, search add new, dort, etc. I generally want to listen to more than one song, or listening to one hive me idea for other. 

### Suggested Solution

Mvp: Create a local playlist and UX to manage it, at least :
- add item to playlist just after the currently playing
- add item in last position
- sort (drag'n'drop or up/down arrows, whichever the simplest)
- delete item

Nice to have : 
- persist current queue between stop/start of app
- name and save as a local playlist
- transform recently played song as local playlist
- export and share as YouTube playlist

**Comment by S0nter** [comment]
I think that this is a nice feature to have. I can also add that automatic queue initialising would be nice to have at the main page and at the search page.


What I mean is:
1) You launch app
2) You click on a song from `Recommended to you` page
3) App adds all songs from `Recommended to you` to a queue/playlist
4) App plays the song that you've chosen from the playlist so you can play previous and next song from `Recommended to you`

**Comment by gokadzev** [comment]
> I think that this is a nice feature to have. I can also add that automatic queue initialising would be nice to have at the main page and at the search page.
> 
> What I mean is:
> 
> 1. You launch app
> 2. You click on a song from `Recommended to you` page
> 3. App adds all songs from `Recommended to you` to a queue/playlist
> 4. App plays the song that you've chosen from the playlist so you can play previous and next song from `Recommended to you`

It will be available in the next version :)

**Comment by gokadzev** [comment]
I think I can freely close this issue, as most of the requested features have been added. In case of any additions (new ideas) or missed points, feel free to open a new issue.
