### ISSUE TITLE
[Bug] Interface freezing when playing music 

### ISSUE THREAD

**Issue by exadeci** [gokadzev/Musify#290]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

Play any music
The app interface freezes 

### Expected Behavior

I should be able to use the app 

### Musify Version

6.4.0

### Operating System Version

Android 13

### Additional Information

TQ3A.230901.001 Pixel 6

**Comment by gokadzev** [comment]
@exadeci Hello, I will make changes about display modes but I'm not sure if it will solve your problem as this problem doesn't exist when i test the app. If you will be able to test several bugs, we may be able to fix this problem.

**Comment by shubham21155102** [comment]
hey @gokadzev I am facing problem its saying flutter_diplay_mode not available Error: MissingPluginException(No implementation found for method getSupportedModes on channel flutter_display_mode)
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49  throw_
packages/flutter/src/services/platform_channel.dart 308:7                     _invokeMethod
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
dart-sdk/lib/async/zone.dart 1661:54                                          runUnary
dart-sdk/lib/async/future_impl.dart 156:18                                    handleValue
dart-sdk/lib/async/future_impl.dart 840:44                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 869:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 641:5                                     [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 715:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:15           <fn>

**Comment by gokadzev** [comment]
> hey @gokadzev I am facing problem its saying flutter_diplay_mode not available Error: MissingPluginException(No implementation found for method getSupportedModes on channel flutter_display_mode) dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49 throw_ packages/flutter/src/services/platform_channel.dart 308:7 _invokeMethod dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50 dart-sdk/lib/async/zone.dart 1661:54 runUnary dart-sdk/lib/async/future_impl.dart 156:18 handleValue dart-sdk/lib/async/future_impl.dart 840:44 handleValueCallback dart-sdk/lib/async/future_impl.dart 869:13 _propagateToListeners dart-sdk/lib/async/future_impl.dart 641:5 [_completeWithValue] dart-sdk/lib/async/future_impl.dart 715:7 callback dart-sdk/lib/async/schedule_microtask.dart 40:11 _microtaskLoop dart-sdk/lib/async/schedule_microtask.dart 49:5 _startMicrotaskLoop dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:15

Which platform? WEB?

**Comment by exadeci** [comment]
@gokadzev https://photos.app.goo.gl/2zDhV32tnAQJqgrp6
Here's how it looks

**Comment by shubham21155102** [comment]
@gokadzev web
chrome

**Comment by gokadzev** [comment]
> @gokadzev https://photos.app.goo.gl/2zDhV32tnAQJqgrp6 Here's how it looks

Does it happen only on the playlist page

**Comment by gokadzev** [comment]
> @gokadzev web chrome

use PC-BETA branch and put display_mode code in condition if(isAndroid).

**Comment by gokadzev** [comment]
@exadeci Could you try [this build](https://github.com/gokadzev/Musify/releases/download/master/Musify.apk) and tell me if it's the same?

**Comment by shubham21155102** [comment]
@gokadzev I also used android phone but git the error 
Launching lib/main.dart on I2018 in debug mode...
main.dart:1
Exception: Gradle build failed to produce an .apk file. It's likely that this file was generated under /Users/shubham/Desktop/shubham/Musify/build, but the tool couldn't find it.
Exited

**Comment by exadeci** [comment]
> @exadeci Could you try [this build](https://github.com/gokadzev/Musify/releases/download/master/Musify.apk) and tell me if it's the same?

Works great thanks

**Comment by gokadzev** [comment]
> > @exadeci Could you try [this build](https://github.com/gokadzev/Musify/releases/download/master/Musify.apk) and tell me if it's the same?
> 
> Works great thanks

Perfect! You will receive the next version with this and other changes :)
