### ISSUE TITLE
[Bug] Musify freezes or becomes unresponsive randomly

### ISSUE THREAD

**Issue by Panak252** [gokadzev/Musify#300]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

When I launch a fresh instance of the app, it works okay. If I go to the about page in the settings tab, and then go back, the app won't scroll up or down. This happens if I search for a song, play it, go in player view (shows album art, download, etc.), and then go back, the app won't respond to anything I do, although I can play-pause from the player popup within android.

### Expected Behavior

If I search for a song, play it, go in player view (with the big album art, download button, etc.), and exit that view, I should still be able to navigate the app.

### Steps To Reproduce

1. Launch new instance of the app.

2.1 Go to the about page in the settings tab, and then go back

3.1 The app won't scroll up or down.

1. Launch new instance of the app.

2.2 Search for a song, play it, go in player view (shows album art, download, etc.), and then go back.

3.2 The app won't respond to anything besides interaction from the player popup within android.

### Musify Version

6.5.2

### Operating System Version

OneUI 5.1, Android 13

### Additional Information

Installed from Droid-ify
Device: S22 Ultra

**Comment by gokadzev** [comment]
@Panak252 Hello, I tried everything what you've mentioned in your issue and even more with different refresh rates and I don't have that issue. To be able what's happening on your device while using the app, I will need you to know how to take logs from the app and then take logs from given debug app.

**Comment by Panak252** [comment]
Definitely, I'm all ears.

**Comment by gokadzev** [comment]
> Definitely, I'm all ears. Tell me the debug app to install, and anything else I may need to know to provide you with the logs on my device.

Great, some information about how to log (https://github.com/gokadzev/Musify/issues/170#issuecomment-1452765058) / what's not mentioned here is how to download and install sdk platform tools but this one is easier so try this (if it won't work, you need to install sdk platform tools then): https://androidmtk.com/download-minimal-adb-and-fastboot-tool

Debug app: https://github.com/gokadzev/Musify/releases/tag/master

**Comment by gokadzev** [comment]
Any news here?

**Comment by sagar676** [comment]
I am also facing this issue app won't scroll up and down randomly when we go to playing screen and come back again go to search and paying screen and back randomly it stuck

**Comment by gokadzev** [comment]
> I am also facing this issue app won't scroll up and down randomly when we go to playing screen and come back again go to search and paying screen and back randomly it stuck

Does it still happen in the latest version?

**Comment by sagar676** [comment]
Yes i tried on yesterdays version it still happen using below steps it can be easily reproduce, i tested on oneplus 5t and oneplust 8t

1. Open app
2. Tap on any suggested playlist
3. Tap on any one song list inside playlist 
4. once song started open the tap on up arrow to open music player in full view 
5. go back till dashboard and try open music player using up arrow and come back repeate only 5th step 3-4 times ui got stuck 


there are multiple situation when ui get stuck only one out of them i given step above

**Comment by gokadzev** [comment]
> Yes i tried on yesterdays version it still happen using below steps it can be easily reproduce, i tested on oneplus 5t and oneplust 8t
> 
> 1. Open app
> 2. Tap on any suggested playlist
> 3. Tap on any one song list inside playlist
> 4. once song started open the tap on up arrow to open music player in full view
> 5. go back till dashboard and try open music player using up arrow and come back repeate only 5th step 3-4 times ui got stuck
> 
> there are multiple situation when ui get stuck only one out of them i given step above

It doesn't happen in my case, I wonder where is the problem. Could you tell me your total RAM and screen refresh rate? Also is there any chance to take logs?

**Comment by sagar676** [comment]
Oneplus 8t is with 12GB RAM and 120hz refresh rate

https://github.com/gokadzev/Musify/assets/12659828/b965c0cd-afdb-404d-a99f-60c33ecc30ba

Copy Logs (0) showing 0 but if there is any other way i can help in it.

My device is oneplust 8t with 12GB of ram and 120hz screen refresh rate. i have shown in video about the version i am using its 6.7.1

**Comment by gokadzev** [comment]
> Oneplus 8t is with 12GB RAM and 120hz refresh rate
> 
>  bug.mp4 
> Copy Logs (0) showing 0 but if there is any other way i can help in it.
> 
> My device is oneplust 8t with 12GB of ram and 120hz screen refresh rate. i have shown in video about the version i am using its 6.7.1

Could you tell me if it's the same in the latest version?

**Comment by sagar676** [comment]
I have tested on Version 6.8.0 it still freeze the ui after restart it start working and again after some navigation randomly freeze the ui

**Comment by sagar676** [comment]
No swipe to go back is not working

**Comment by gokadzev** [comment]
> No swipe to go back is not working. In latest version freeze of ui frequency is decreased

Okay, after my changes swipe to go back is working. about UI freezes I expect it to be decreased more or disappear at all in the next version.

**Comment by sagar676** [comment]
Ok I will test in next version and update my experience here

**Comment by gokadzev** [comment]
> Ok I will test in next version and update my experience here

Okay, let me know if the problem still exists.

**Comment by gokadzev** [comment]
@sagar676 @Panak252 Any change?

**Comment by gokadzev** [comment]
> When I use gesture navigation after 4-5 navigation ui freeze but when I don't use guesture it doesn't freeze

So strange. It's either my navigator (but it should have a problem on my device too) or it's Flutter itself.

**Comment by gokadzev** [comment]
Unfortunately, I tested Musify on three devices (different brands), and neither did it lag nor become unresponsive. Additionally, I don't see anything wrong in the code.This is the case where I need anything related to the issue (besides screenrecording) to make changes according to it.

**Comment by gokadzev** [comment]
@VulcanElf @sagar676 @Panak252, I forgot to ask, what audio quality have you set?

**Comment by gokadzev** [comment]
@VulcanElf @sagar676 

Could you try and tell me if it's the same here?:

https://github.com/gokadzev/Musify/releases/tag/master

**Comment by gokadzev** [comment]
@VulcanElf @sagar676 Okay, the latest version is really worthy to check. I hope there isn't freezing problem active anymore

**Comment by azooz137** [comment]
this is still happening to me in 7.4.0
things i noticed:
this only happens in some places of the app (for example User liked playlists menu and ) when i swipe from left to the right side of the screen to return, swiping from the right to the left and using return button at the top left is fine and does not cause the bug for me.
one thing i noticed as well is that the last return transmission animation before the app freezes is different from the usual one.
i tested this on 2 devices:
1: galaxy s23 ultra
2. galaxy a52 5g
both running android 14

**Comment by gokadzev** [comment]
> this is still happening to me in 7.4.0 things i noticed: this only happens in some places of the app (for example User liked playlists menu) when i swipe from left to the right side of the screen to return, swiping from the right to the left and using return button at the top left is fine and does not cause the bug for me. one thing i noticed as well is that the last return transmission animation before the app freezes is different from the usual one. i tested this on 2 devices: 1: galaxy s23 ultra 2. galaxy a52 5g both running android 14

Any changes in the latest version?

**Comment by gokadzev** [comment]
@sagar676 @VulcanElf @azooz137 @Panak252 Please check now

**Comment by azooz137** [comment]
nothing changed for me on 7.5.0 still same issue

**Comment by gokadzev** [comment]
> nothing changed for me on 7.5.0 still same issue

I don't know what else it could be then. I've changed almost everything that could be blamed for that issue.

**Comment by azooz137** [comment]
this issue is now completely fixed after the 7.5.1 update.

**Comment by gokadzev** [comment]
> this issue is now completely fixed after the 7.5.1 update.

Great, thanks!
