### ISSUE TITLE
Somebody is stealing your code

### ISSUE THREAD

**Issue by iamsdx** [gokadzev/Musify#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues and confirmed that this feature is not already requested.

### Credits

Cody

### Pain

https://play.google.com/store/apps/details?id=com.milople.melodymix

### Suggested Solution

report to google

**Comment by gokadzev** [comment]
Oh, again. Thank you for informing me. I will also post in discussions to make more people aware and report it.

**Comment by onthejobtraining** [comment]
https://play.google.com/store/apps/details?id=com.musify.online_music_player_download

https://play.google.com/store/apps/details?id=com.pixelcodes.music_player

**Comment by gokadzev** [comment]
> https://play.google.com/store/apps/details?id=com.musify.online_music_player_download
> 
> https://play.google.com/store/apps/details?id=com.pixelcodes.music_player

They had also stolen our app logo. As long as they only have our app name and not the logo anymore, it's not a problem for us. However, they are still using other open-source code without giving proper credits.

**Comment by gokadzev** [comment]
Seems like Google isn't going to take down that app, It already has 1K installs. 🤔

**Comment by louxyy** [comment]
As you pointed out on one of your pages, the license does not allow publishing your source code on a close source repository. The license is supposed to protect your code. 
I find the behavior unbelievable and unacceptable of this guy. You develop an application for yourself first and you offer it to us free of charge, add-free and with source code !  You update your application to improve it, to fix bugs...
But there are people who publish your code... pffff. I don't understand what's going on in this guy's head. Does he have a problem? 

You'd have to write comments for the app on the playstore to denounce it, and hope that the author can't delete them... 

Good luck to you and happy new year 2024 ! :smiley:

**Comment by avagraphique** [comment]
Perhaps you can file a complaint?
https://support.google.com/googleplay/android-developer/answer/9888072#zippy=%2Cexamples-of-common-violations
