### ISSUE TITLE
[Bug] Download button not visible for any song

### ISSUE THREAD

**Issue by AdiPathak97** [gokadzev/Musify#309]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

Download button is not present in song list beside the star and plus buttons.

Screenshot:
![Screenshot_20231117-043515](https://github.com/gokadzev/Musify/assets/36631927/411fde62-f081-4878-87b9-797e4c0f0a44)

### Expected Behavior

Download button should be present on the right for each row containing song name.

### Musify Version

v6.7.1

### Operating System Version

Android 14

### Additional Information

I use GrapheneOS, don't know if relevant. Didn't face this a couple weeks back, was able to download songs normally.

**Comment by gokadzev** [comment]
> ### Acknowledgements
> * [x]  I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
> * [x]  I will fill out all the sections in this issue report.
> 
> ### Current Behavior
> Download button is not present in song list beside the star and plus buttons.
> 
> Screenshot: ![Screenshot_20231117-043515](https://user-images.githubusercontent.com/36631927/283750093-411fde62-f081-4878-87b9-797e4c0f0a44.png)
> 
> ### Expected Behavior
> Download button should be present on the right for each row containing song name.
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Musify Version
> v6.7.1
> 
> ### Operating System Version
> Android 14
> 
> ### Additional Information
> I use GrapheneOS, don't know if relevant. Didn't face this a couple weeks back, was able to download songs normally.

The download feature has been removed since version 6.7.0.
