### ISSUE TITLE
Backup/restore is still not working

### ISSUE THREAD

**Issue by max5354** [gokadzev/Musify#31]
Backup/restore is still not working in latest version

If We press "restore" button than nothing is happening. It show that "data restored" but not restoring anything.

**Expected behavior**
It should restore data.

**Smartphone 
 - Device: [e.g. Samsung Galaxy j8]
 - OS: [Android 10]
 - App Version [v1.6.0]

**Comment by gokadzev** [comment]
> Backup/restore is still not working in latest version
> 
> If We press "restore" button than nothing is happening. It show that "data restored" but not restoring anything.
> 
> **Expected behavior** It should restore data.
> 
> **Smartphone
> 
> * Device: [e.g. Samsung Galaxy j8]
> * OS: [Android 10]
> * App Version [v1.6.0]

i've answered on previous issue, if you don't want to be closed your issue automatically, dont clear anything, just change answer lines which you want to change
