### ISSUE TITLE
the problem with debug mode.

### ISSUE THREAD

**Issue by abuhabban** [gokadzev/Musify#315]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

i am trying to run the app in android studio after cloning ftronm github but it says daemon failed but it build the debug.apk file in outputs. But not running in live debug mode.

### Expected Behavior

it should install and open app in debug mode.

### Musify Version

latest

### Operating System Version

androuid 13

**Comment by gokadzev** [comment]
@abuhabban Hello, if you use command way, run this: flutter run --flavor github

if not, choose build type debug and flavor github from android studio

**Comment by abuhabban** [comment]
> @abuhabban Hello, if you are using the command line, run this: `flutter run --flavor github`.
> 
> If not, choose the build type "debug" and flavor "github" from Android Studio.

![20231129_182200](https://github.com/gokadzev/Musify/assets/70461458/b71857af-660d-45a6-9824-762ef4c72183)

**Comment by abuhabban** [comment]
> > > @abuhabban Hello, if you are using the command line, run this: `flutter run --flavor github`.
> > > If not, choose the build type "debug" and flavor "github" from Android Studio.
> > 
> > 
> > ![20231129_182200](https://private-user-images.githubusercontent.com/70461458/286599997-b71857af-660d-45a6-9824-762ef4c72183.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjI3NDYsIm5iZiI6MTcwMTI2MjQ0NiwicGF0aCI6Ii83MDQ2MTQ1OC8yODY1OTk5OTctYjcxODU3YWYtNjYwZC00NWE2LTk4MjQtNzYyZWY0YzcyMTgzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDEyNTQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNTAwMjM4MzU2MGY0MWNhMmE3NzQzMjI3NTBhYjczMGI0NDhmYjQxMTM4ODc4MGU0MTk1ZDMyNTM0YzYxODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uWh76-aiMohM-5rBNkTx7z9xKygCz1a243m2pF-b9c0)
> 
> Please also show me which flavor you have chosen there.

how to chose flavor

**Comment by gokadzev** [comment]
> > > > @abuhabban Hello, if you are using the command line, run this: `flutter run --flavor github`.
> > > > If not, choose the build type "debug" and flavor "github" from Android Studio.
> > > 
> > > 
> > > ![20231129_182200](https://private-user-images.githubusercontent.com/70461458/286599997-b71857af-660d-45a6-9824-762ef4c72183.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjI3NDYsIm5iZiI6MTcwMTI2MjQ0NiwicGF0aCI6Ii83MDQ2MTQ1OC8yODY1OTk5OTctYjcxODU3YWYtNjYwZC00NWE2LTk4MjQtNzYyZWY0YzcyMTgzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDEyNTQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNTAwMjM4MzU2MGY0MWNhMmE3NzQzMjI3NTBhYjczMGI0NDhmYjQxMTM4ODc4MGU0MTk1ZDMyNTM0YzYxODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uWh76-aiMohM-5rBNkTx7z9xKygCz1a243m2pF-b9c0)
> > 
> > 
> > Please also show me which flavor you have chosen there.
> 
> how to chose flavor

"... select Build > select Build Variant in the menu bar (or click Build Variants within the windows bar), then select a build variant from the menu." ([source](https://medium.com/simform-engineering/basic-use-of-android-product-flavors-build-variants-315a4e11e435))

**Comment by abuhabban** [comment]
> > > > > @abuhabban Hello, if you are using the command line, run this: `flutter run --flavor github`.
> > > > > If not, choose the build type "debug" and flavor "github" from Android Studio.
> > > > 
> > > > 
> > > > ![20231129_182200](https://private-user-images.githubusercontent.com/70461458/286599997-b71857af-660d-45a6-9824-762ef4c72183.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjI3NDYsIm5iZiI6MTcwMTI2MjQ0NiwicGF0aCI6Ii83MDQ2MTQ1OC8yODY1OTk5OTctYjcxODU3YWYtNjYwZC00NWE2LTk4MjQtNzYyZWY0YzcyMTgzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDEyNTQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNTAwMjM4MzU2MGY0MWNhMmE3NzQzMjI3NTBhYjczMGI0NDhmYjQxMTM4ODc4MGU0MTk1ZDMyNTM0YzYxODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uWh76-aiMohM-5rBNkTx7z9xKygCz1a243m2pF-b9c0)
> > > 
> > > 
> > > Please also show me which flavor you have chosen there.
> > 
> > 
> > how to chose flavor
> 
> "... select Build > select Build Variant in the menu bar (or click Build Variants within the windows bar), then select a build variant from the menu." ([source](https://medium.com/simform-engineering/basic-use-of-android-product-flavors-build-variants-315a4e11e435))

This is a new thing to me let me study this for today. By the way thanks.

**Comment by gokadzev** [comment]
> > > 
> > > how to chose flavor
> > 
> > 
> > "... select Build > select Build Variant in the menu bar (or click Build Variants within the windows bar), then select a build variant from the menu." ([source](https://medium.com/simform-engineering/basic-use-of-android-product-flavors-build-variants-315a4e11e435))
> 
> This is a new thing to me let me study this for today. By the way thanks.

It's okay. 

![image](https://github.com/gokadzev/Musify/assets/79704324/75d48b7d-8e16-4c9d-b70b-2dd966cf07fb)


app build variant should be githubDebug (build variant option should be on the left side as it's shown in the screenshot)

**Comment by abuhabban** [comment]
> > > > how to chose flavor
> > > 
> > > 
> > > "... select Build > select Build Variant in the menu bar (or click Build Variants within the windows bar), then select a build variant from the menu." ([source](https://medium.com/simform-engineering/basic-use-of-android-product-flavors-build-variants-315a4e11e435))
> > 
> > 
> > This is a new thing to me let me study this for today. By the way thanks.
> 
> It's okay.
> 
> ![image](https://private-user-images.githubusercontent.com/79704324/286603831-75d48b7d-8e16-4c9d-b70b-2dd966cf07fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjM3MDQsIm5iZiI6MTcwMTI2MzQwNCwicGF0aCI6Ii83OTcwNDMyNC8yODY2MDM4MzEtNzVkNDhiN2QtOGUxNi00YzlkLWI3MGItMmRkOTY2Y2YwN2ZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDEzMTAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkOTI3Mzc5ZGZmZjhkNmJhNzg1ZjJhNzI3NGFmOTZhZjVkNDgwYTU1YjkzNDBhNjg0NDJlZDM1YzBkOWI4Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iycQ_KFt-3xzAQsazf9iMDlhXDTJb6mdUu-toWiaEso)
> 
> app build variant should be githubDebug (build variant option should be on the left side as it's shown in the screenshot)

there is no build variant option in musify pro
![IMG-20231129-WA0003](https://github.com/gokadzev/Musify/assets/70461458/fa812a2b-8df5-4964-b15d-a705aac5c289)
![IMG-20231129-WA0004](https://github.com/gokadzev/Musify/assets/70461458/3366fb91-e38c-4932-b891-370064c31ecb)
ject while  in my project modulus it has build variant option.

**Comment by gokadzev** [comment]
> > > > > how to chose flavor
> > > > 
> > > > 
> > > > "... select Build > select Build Variant in the menu bar (or click Build Variants within the windows bar), then select a build variant from the menu." ([source](https://medium.com/simform-engineering/basic-use-of-android-product-flavors-build-variants-315a4e11e435))
> > > 
> > > 
> > > This is a new thing to me let me study this for today. By the way thanks.
> > 
> > 
> > It's okay.
> > ![image](https://private-user-images.githubusercontent.com/79704324/286603831-75d48b7d-8e16-4c9d-b70b-2dd966cf07fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjM3MDQsIm5iZiI6MTcwMTI2MzQwNCwicGF0aCI6Ii83OTcwNDMyNC8yODY2MDM4MzEtNzVkNDhiN2QtOGUxNi00YzlkLWI3MGItMmRkOTY2Y2YwN2ZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDEzMTAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkOTI3Mzc5ZGZmZjhkNmJhNzg1ZjJhNzI3NGFmOTZhZjVkNDgwYTU1YjkzNDBhNjg0NDJlZDM1YzBkOWI4Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iycQ_KFt-3xzAQsazf9iMDlhXDTJb6mdUu-toWiaEso)
> > app build variant should be githubDebug (build variant option should be on the left side as it's shown in the screenshot)
> 
> there is no build variant option in musify pro ![IMG-20231129-WA0003](https://private-user-images.githubusercontent.com/70461458/286606969-fa812a2b-8df5-4964-b15d-a705aac5c289.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjQzNjYsIm5iZiI6MTcwMTI2NDA2NiwicGF0aCI6Ii83MDQ2MTQ1OC8yODY2MDY5NjktZmE4MTJhMmItOGRmNS00OTY0LWIxNWQtYTcwNWFhYzVjMjg5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDEzMjEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMzE3NGQwYmEyMWY1ZmU5MjI0ZTQ0ZjBmYjYxOTkwNTU2NmFmMmUxMTczYjgxOTk1YzU2NGFkYThkZTY4ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p5Hmkjt1dKRhEWxff6krrxtAEEjntYT5z9uPXTrpkF8) ![IMG-20231129-WA0004](https://private-user-images.githubusercontent.com/70461458/286606986-3366fb91-e38c-4932-b891-370064c31ecb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjQzNjYsIm5iZiI6MTcwMTI2NDA2NiwicGF0aCI6Ii83MDQ2MTQ1OC8yODY2MDY5ODYtMzM2NmZiOTEtZTM4Yy00OTMyLWI4OTEtMzcwMDY0YzMxZWNiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDEzMjEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYjhhOTI2NWY4YWYzM2FlMTdmNDZmMmI3ZDUyY2NkNmNlNzQwNzFiY2ZkOWUxMDdlN2M4OGRiN2EwZjBiNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3I5gJuIfVYaIeswBp6qJtahw3m0W73cBSAMJJGvwReM) ject while in my project modulus it has build variant option.

Try to open only Android folder instead of Musify folder. I just checked and it shows. Also don't forget to sync the project with gradle files.

**Comment by gokadzev** [comment]
Did it work?

**Comment by abuhabban** [comment]
> Did it work?

lots of try....
![IMG-20231129-WA0008](https://github.com/gokadzev/Musify/assets/70461458/acb4de38-8a11-4880-976e-4920e64073f4)
![IMG-20231129-WA0007](https://github.com/gokadzev/Musify/assets/70461458/2e184756-e623-40ab-b65d-f4eb271e3aa1)
![IMG-20231129-WA0006](https://github.com/gokadzev/Musify/assets/70461458/932bbc4d-fb6e-4955-8675-18f7c94d50a7)
![IMG-20231129-WA0005](https://github.com/gokadzev/Musify/assets/70461458/83b5b947-3550-47b6-a8dc-1de0fd84905d)

I learned how to sync with gradle.
also changed directory of musify from d to c drive.
google search  {
flutten clean
resync gradle}
and lots more nothing worked.
But Thanks for your Support and soon i will be a contributer in this project to learn and enhance my knowledge.

**Comment by abuhabban** [comment]
It worked
![IMG-20231130-WA0000](https://github.com/gokadzev/Musify/assets/70461458/f00da54c-0879-4e8d-bd61-6e6c1ee32630)

**Comment by gokadzev** [comment]
> It worked ![IMG-20231130-WA0000](https://private-user-images.githubusercontent.com/70461458/286818128-f00da54c-0879-4e8d-bd61-6e6c1ee32630.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMjI2NDIsIm5iZiI6MTcwMTMyMjM0MiwicGF0aCI6Ii83MDQ2MTQ1OC8yODY4MTgxMjgtZjAwZGE1NGMtMDg3OS00ZThkLWJkNjEtNmU2YzFlZTMyNjMwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA1MzIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzMmRlY2U5NWUxY2QxZThmMGU0OGQyMWEzNmRiYjU3M2RjNzFhYWYwNGVjY2RmMDEwNWJhNTIzMjhlNGFlN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ISYlciBUMJr3PfFzIQe15FRe7vTLAEnSQaIMPR5Pzic)

Perfect! 🔥

**Comment by abuhabban** [comment]
![Screenshot_20231130_101025](https://github.com/gokadzev/Musify/assets/70461458/678d2ab7-56d9-4b0d-acff-c1b3a1b82c9e)
in my physical phone.
it fixed this using singlechildscrollview  is there any other good method.

**Comment by abuhabban** [comment]
also give me your telegram username so i can easily contact you if you can.

**Comment by gokadzev** [comment]
> also give me your telegram username so i can easily contact you if you can.

@vgok2023
