### ISSUE TITLE
Where should the folder musify be located?

### ISSUE THREAD

**Issue by Screenshared** [gokadzev/Musify#32]
**Describe the bug**
I tried to backup user data, with archive permission granted, but i don't see any musify folder in my storage.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy S22]
 - OS: [e.g. Android 12]
 - App Version [ v1.16]

**Additional context**

**Comment by gokadzev** [comment]
> **Describe the bug** I tried to backup user data, with archive permission granted, but i don't see any musify folder in my storage.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. Samsung Galaxy S22]
> * OS: [e.g. Android 12]
> * App Version [ v1.16]
> 
> **Additional context** Add any other context about the problem here.
@Screenshared 

it should be in root folder
