### ISSUE TITLE
More languages

### ISSUE THREAD

**Issue by OmarNazzal150** [gokadzev/Musify#320]
### Is there an existing issue for this?

- [x] I have searched the existing issues and confirmed that this feature is not already requested.

### Category of the Feature

Unable to categorize

### Credits

By my self

### Pain

Nothing. Just add languages

### Suggested Solution

Can you add more languages. Note: All of this is generated by AI except for urdu

### Useful Resources/References

Russian   { “about”: “О”, “accentChangeMsg”: “Цвет акцента изменен”, “accentColor”: “Цвет акцента”, “add”: “Добавить”, “addToPlaylist”: “Добавить в плейлист”, “addedSuccess”: “Успешно добавлено”, “album”: “Альбом”, “appUpdateAvailableAndDownloading”: “Доступно обновление приложения и загрузка”, “appUpdateIsAvailable”: “Доступно обновление приложения”, “audioQuality”: “Качество звука”, “audioQualityMsg”: “Качество звука изменено”, “backedupSuccess”: “Резервное копирование успешно выполнено”, “backupError”: “Ошибка при резервном копировании данных”, “backupUserData”: “Резервное копирование пользовательских данных”, “becomeSponsor”: “Стать спонсором”, “cacheMsg”: “Кэш очищен”, “cancel”: “Отмена”, “chooseBackupDir”: “Выберите директорию для резервного копирования”, “chooseRestoreDir”: “Выберите директорию для восстановления файла”, “clear”: “Очистить”, “clearCache”: “Очистить кэш”, “clearSearchHistory”: “Очистить историю поиска”, “confirm”: “Подтвердить”, “confirmation”: “Подтверждение”, “copyLogs”: “Копировать журналы”, “copyLogsNoLogs”: “Журналы для копирования не найдены”, “copyLogsSuccess”: "Журналы успешно скопированы. ", “customPlaylistAddInstruction”: “Если вы добавляете плейлист YouTube, заполните только поле ID плейлиста YouTube, если вы создаете свой собственный плейлист, оставьте поле ID плейлиста YouTube пустым и заполните только: Название, Ссылка на изображение (необязательно), Описание (необязательно)”, “customPlaylistDesc”: “Описание пользовательского плейлиста”, “customPlaylistImgUrl”: “Ссылка на изображение пользовательского плейлиста”, “customPlaylistName”: “Название пользовательского плейлиста”, “downloadAppUpdate”: “Загрузить обновление приложения”, “dynamicColor”: “Динамический цвет акцента (Android 12+)”, “error”: “Что-то пошло не так”, “errorWhileRequestingPerms”: “Ошибка при запросе разрешений”, “home”: “Главная”, “language”: “Язык”, “languageMsg”: “Язык изменен”, “licenses”: “Лицензии”, “lyrics”: “Текст песни”, “lyricsNotAvailable”: “Текст песни недоступен ;(”, “more”: “Больше”, “noLikedPlaylists”: “Вы еще не понравились ни одному плейлисту”, “notYTlist”: “Это не ID плейлиста YouTube”, “nothingFound”: “Ничего не найдено”, “nowPlaying”: “Сейчас играет”, “others”: “Другие”, “pages”: “Страницы”, “playlist”: “Плейлист”, “playlistUpdated”: “Плейлист успешно обновлен”, “playlists”: “Плейлисты”, “provideIdOrNameError”: “Пожалуйста, укажите либо ID YouTube, либо название пользовательского плейлиста”, “queueInitText”: “Инициализация очереди…”, “recentlyPlayed”: “Недавно проигранные”, “recommendedForYou”: “Рекомендовано для вас”, “remove”: “Удалить”, “removePlaylistQuestion”: “Вы уверены, что хотите удалить этот плейлист?”, “removeSearchQueryQuestion”: “Вы уверены, что хотите удалить этот поисковый запрос?”, “restoreError”: “Ошибка при восстановлении данных”, “restoreUserData”: “Восстановить пользовательские данные”, “restoredSuccess”: “Успешно восстановлено”, “search”: “Поиск”, “searchHistoryMsg”: “История поиска очищена”, “settingChangedMsg”: “Настройка изменена”, “settings”: “Настройки”, “songRemoved”: “Песня успешно удалена!”, “songs”: “песни”, “sponsorProject”: “Спонсировать проект”, “suggestedArtists”: “Предложенные исполнители”, “suggestedPlaylists”: “Предложенные плейлисты”, “themeMode”: “Режим темы”, “tools”: “Инструменты”, “undo”: “отменить”, “userLikedPlaylists”: “Плейлисты, которые понравились пользователю”, “userLikedSongs”: “Песни, которые понравились пользователю”, “userPlaylists”: “Плейлисты пользователя”, “yourFavoriteSongsHere”: “Ваши любимые песни здесь”, “youtubePlaylistID”: “ID плейлиста YouTube” }

Italian    { “about”: “Informazioni”, “accentChangeMsg”: “Il colore dell’accento è stato modificato”, “accentColor”: “Colore dell’accento”, “add”: “Aggiungi”, “addToPlaylist”: “Aggiungi alla playlist”, “addedSuccess”: “Aggiunto con successo”, “album”: “Album”, “appUpdateAvailableAndDownloading”: “L’aggiornamento dell’app è disponibile e in download”, “appUpdateIsAvailable”: “L’aggiornamento dell’app è disponibile”, “audioQuality”: “Qualità audio”, “audioQualityMsg”: “La qualità audio è stata modificata”, “backedupSuccess”: “Backup effettuato con successo”, “backupError”: “Errore durante il backup dei dati”, “backupUserData”: “Backup dei dati utente”, “becomeSponsor”: “Diventa uno sponsor”, “cacheMsg”: “Cache svuotata”, “cancel”: “Annulla”, “chooseBackupDir”: “Scegli la cartella di backup”, “chooseRestoreDir”: “Scegli la cartella di ripristino”, “clear”: “Pulisci”, “clearCache”: “Svuota cache”, “clearSearchHistory”: “Cancella cronologia delle ricerche”, “confirm”: “Conferma”, “confirmation”: “Conferma”, “copyLogs”: “Copia i log”, “copyLogsNoLogs”: “Nessun log trovato da copiare”, “copyLogsSuccess”: "Log copiati con successo. ", “customPlaylistAddInstruction”: “Se aggiungi una playlist di YouTube, riempi solo il campo ID playlist di YouTube, se crei la tua playlist lascia vuoto l’ID playlist di YouTube e riempi solo: Nome, Link immagine (opzionale), Descrizione (opzionale)”, “customPlaylistDesc”: “Descrizione della playlist personalizzata”, “customPlaylistImgUrl”: “Link dell’immagine della playlist personalizzata”, “customPlaylistName”: “Nome della playlist personalizzata”, “downloadAppUpdate”: “Scarica l’aggiornamento dell’app”, “dynamicColor”: “Colore dell’accento dinamico (Android 12+)”, “error”: “Qualcosa è andato storto”, “errorWhileRequestingPerms”: “Errore durante la richiesta dei permessi”, “home”: “Home”, “language”: “Lingua”, “languageMsg”: “La lingua è stata modificata”, “licenses”: “Licenze”, “lyrics”: “Testi”, “lyricsNotAvailable”: “Nessun testo disponibile ;(”, “more”: “Altro”, “noLikedPlaylists”: “Non hai ancora messo mi piace a nessuna playlist”, “notYTlist”: “Questo non è un ID di una playlist di YouTube”, “nothingFound”: “Niente trovato”, “nowPlaying”: “In riproduzione”, “others”: “Altri”, “pages”: “Pagine”, “playlist”: “Playlist”, “playlistUpdated”: “Playlist aggiornata con successo”, “playlists”: “Playlist”, “provideIdOrNameError”: “Per favore fornisci o un ID di YouTube o un nome di una playlist personalizzata”, “queueInitText”: “Inizializzazione della coda…”, “recentlyPlayed”: “Ascoltati di recente”, “recommendedForYou”: “Consigliati per te”, “remove”: “Rimuovi”, “removePlaylistQuestion”: “Sei sicuro di voler rimuovere questa playlist?”, “removeSearchQueryQuestion”: “Sei sicuro di voler rimuovere questa query di ricerca?”, “restoreError”: “Errore durante il ripristino dei dati”, “restoreUserData”: “Ripristina i dati utente”, “restoredSuccess”: “Ripristinato con successo”, “search”: “Cerca”, “searchHistoryMsg”: “Cronologia delle ricerche cancellata”, “settingChangedMsg”: “Impostazione modificata”, “settings”: “Impostazioni”, “songRemoved”: “Canzone rimossa con successo!”, “songs”: “canzoni”, “sponsorProject”: “Sponsorizza il progetto”, “suggestedArtists”: “Artisti suggeriti”, “suggestedPlaylists”: “Playlist suggerite”, “themeMode”: “Modalità tema”, “tools”: “Strumenti”, “undo”: “annulla”, “userLikedPlaylists”: “Playlist piaciute all’utente”, “userLikedSongs”: “Canzoni piaciute all’utente”, “userPlaylists”: “Playlist dell’utente”, “yourFavoriteSongsHere”: “Le tue canzoni preferite qui”, “youtubePlaylistID”: “ID playlist di YouTube” }

Urdu  Not Yet
   
  

Hungarian   { “about”: “Ról ről”, “accentChangeMsg”: “A hangsúlyos szín megváltozott”, “accentColor”: “Hangsúlyos szín”, “add”: “Hozzáad”, “addToPlaylist”: “Hozzáadás a lejátszási listához”, “addedSuccess”: “Sikeresen hozzáadva”, “album”: “Album”, “appUpdateAvailableAndDownloading”: “Az alkalmazás frissítése elérhető és letöltődik”, “appUpdateIsAvailable”: “Az alkalmazás frissítése elérhető”, “audioQuality”: “Hangminőség”, “audioQualityMsg”: “A hangminőség megváltozott”, “backedupSuccess”: “Sikeresen biztonsági mentve”, “backupError”: “Hiba az adatmentés közben”, “backupUserData”: “Felhasználói adatok biztonsági mentése”, “becomeSponsor”: “Legyen szponzor”, “cacheMsg”: “A gyorsítótár törölve”, “cancel”: “Mégse”, “chooseBackupDir”: “Válassza ki a biztonsági mentés könyvtárát”, “chooseRestoreDir”: “Válassza ki a visszaállítási fájl könyvtárát”, “clear”: “Töröl”, “clearCache”: “Gyorsítótár törlése”, “clearSearchHistory”: “Keresési előzmények törlése”, “confirm”: “Megerősít”, “confirmation”: “Megerősítés”, “copyLogs”: “Naplók másolása”, “copyLogsNoLogs”: “Nincsenek másolható naplók”, “copyLogsSuccess”: "A naplók sikeresen másolva. ", “customPlaylistAddInstruction”: “Ha YouTube lejátszási listát ad hozzá, töltse ki csak a YouTube lejátszási lista azonosító mezőt, ha saját lejátszási listát készít, hagyja üresen a YouTube lejátszási lista azonosító mezőt, és töltse ki csak: Név, Kép link (opcionális), Leírás (opcionális)”, “customPlaylistDesc”: “Egyéni lejátszási lista leírása”, “customPlaylistImgUrl”: “Egyéni lejátszási lista kép linkje”, “customPlaylistName”: “Egyéni lejátszási lista neve”, “downloadAppUpdate”: “Az alkalmazás frissítésének letöltése”, “dynamicColor”: “Dinamikus hangsúlyos szín (Android 12+)”, “error”: “Valami hiba történt”, “errorWhileRequestingPerms”: “Hiba a jogosultságok kérése közben”, “home”: “Kezdőlap”, “language”: “Nyelv”, “languageMsg”: “A nyelv megváltozott”, “licenses”: “Engedélyek”, “lyrics”: “Dalszöveg”, “lyricsNotAvailable”: “Nincs elérhető dalszöveg ;(”, “more”: “Több”, “noLikedPlaylists”: “Még nem kedvelt egyetlen lejátszási listát sem”, “notYTlist”: “Ez nem YouTube lejátszási lista azonosító”, “nothingFound”: “Nem találtam semmit”, “nowPlaying”: “Most játszik”, “others”: “Egyebek”, “pages”: “Oldalak”, “playlist”: “Lejátszási lista”, “playlistUpdated”: “A lejátszási lista sikeresen frissítve”, “playlists”: “Lejátszási listák”, “provideIdOrNameError”: “Kérjük, adjon meg vagy egy YouTube azonosítót, vagy egy egyéni lejátszási lista nevet”, “queueInitText”: “A sor inicializálása…”, “recentlyPlayed”: “Nemrég játszott”, “recommendedForYou”: “Ajánlott Önnek”, “remove”: “Eltávolít”, “removePlaylistQuestion”: “Biztosan el akarja távolítani ezt a lejátszási listát?”, “removeSearchQueryQuestion”: “Biztosan el akarja távolítani ezt a keresési lekérdezést?”, “restoreError”: “Hiba az adatok visszaállítása közben”, “restoreUserData”: “Felhasználói adatok visszaállítása”, “restoredSuccess”: “Sikeresen visszaállítva”, “search”: “Keresés”, “searchHistoryMsg”: “A keresési előzmények törölve”, “settingChangedMsg”: “A beállítás megváltozott”, “settings”: “Beállítások”, “songRemoved”: “A dal sikeresen eltávolítva!”, “songs”: “dalok”, “sponsorProject”: “Támogassa a projektet”, “suggestedArtists”: “Javasolt előadók”, “suggestedPlaylists”: “Javasolt lejátszási listák”, “themeMode”: “Téma mód”, “tools”: “Eszközök”, “undo”: “visszavon”, “userLikedPlaylists”: “A felhasználó által kedvelt lejátszási listák”, “userLikedSongs”: “A felhasználó által kedvelt dalok”, “userPlaylists”: “Felhasználói lejátszási listák”, “yourFavoriteSongsHere”: “A kedvenc dalai itt”, “youtubePlaylistID”: “YouTube lejátszási lista azonosító” }

Romanian   { “about”: “Despre”, “accentChangeMsg”: “Culoarea accentului a fost schimbată”, “accentColor”: “Culoarea accentului”, “add”: “Adaugă”, “addToPlaylist”: “Adaugă la playlist”, “addedSuccess”: “Adăugat cu succes”, “album”: “Album”, “appUpdateAvailableAndDownloading”: “Actualizarea aplicației este disponibilă și se descarcă”, “appUpdateIsAvailable”: “Actualizarea aplicației este disponibilă”, “audioQuality”: “Calitatea audio”, “audioQualityMsg”: “Calitatea audio a fost schimbată”, “backedupSuccess”: “Copiat cu succes”, “backupError”: “Eroare la copierea datelor”, “backupUserData”: “Copiază datele utilizatorului”, “becomeSponsor”: “Devino sponsor”, “cacheMsg”: “Cache-ul a fost golit”, “cancel”: “Anulează”, “chooseBackupDir”: “Alege directorul de copiere”, “chooseRestoreDir”: “Alege directorul de restaurare”, “clear”: “Șterge”, “clearCache”: “Șterge cache-ul”, “clearSearchHistory”: “Șterge istoricul căutărilor”, “confirm”: “Confirmă”, “confirmation”: “Confirmare”, “copyLogs”: “Copiază jurnalele”, “copyLogsNoLogs”: “Nu s-au găsit jurnale de copiat”, “copyLogsSuccess”: "Jurnalele au fost copiate cu succes. ", “customPlaylistAddInstruction”: “Dacă adaugi un playlist YouTube, completează doar câmpul ID playlist YouTube, dacă creezi propriul tău playlist lasă câmpul ID playlist YouTube gol și completează doar: Nume, Link imagine (opțional), Descriere (opțional)”, “customPlaylistDesc”: “Descrierea playlistului personalizat”, “customPlaylistImgUrl”: “Linkul imaginii playlistului personalizat”, “customPlaylistName”: “Numele playlistului personalizat”, “downloadAppUpdate”: “Descarcă actualizarea aplicației”, “dynamicColor”: “Culoare accent dinamică (Android 12+)”, “error”: “Ceva nu a mers bine”, “errorWhileRequestingPerms”: “Eroare la solicitarea permisiunilor”, “home”: “Acasă”, “language”: “Limbă”, “languageMsg”: “Limba a fost schimbată”, “licenses”: “Licențe”, “lyrics”: “Versuri”, “lyricsNotAvailable”: “Nu există versuri disponibile ;(”, “more”: “Mai mult”, “noLikedPlaylists”: “Nu ai apreciat niciun playlist încă”, “notYTlist”: “Acesta nu este un ID de playlist YouTube”, “nothingFound”: “Nu s-a găsit nimic”, “nowPlaying”: “Acum se redă”, “others”: “Altele”, “pages”: “Pagini”, “playlist”: “Playlist”, “playlistUpdated”: “Playlistul a fost actualizat cu succes”, “playlists”: “Playlisturi”, “provideIdOrNameError”: “Te rog să furnizezi fie un ID YouTube, fie un nume de playlist personalizat”, “queueInitText”: “Inițializare coadă…”, “recentlyPlayed”: “Redate recent”, “recommendedForYou”: “Recomandate pentru tine”, “remove”: “Elimină”, “removePlaylistQuestion”: “Ești sigur că vrei să elimini acest playlist?”, “removeSearchQueryQuestion”: “Ești sigur că vrei să elimini această interogare de căutare?”, “restoreError”: “Eroare la restaurarea datelor”, “restoreUserData”: “Restaurează datele utilizatorului”, “restoredSuccess”: “Restaurat cu succes”, “search”: “Caută”, “searchHistoryMsg”: “Istoricul căutărilor a fost șters”, “settingChangedMsg”: “Setarea a fost modificată”, “settings”: “Setări”, “songRemoved”: “Melodia a fost eliminată cu succes!”, “songs”: “melodii”, “sponsorProject”: “Sponsorizează proiectul”, “suggestedArtists”: “Artiști sugerați”, “suggestedPlaylists”: “Playlisturi sugerate”, “themeMode”: “Modul tematic”, “tools”: “Unelte”, “undo”: “anulează”, “userLikedPlaylists”: “Playlisturi apreciate de utilizator”, “userLikedSongs”: “Melodii apreciate de utilizator”, “userPlaylists”: “Playlisturi ale utilizatorului”, “yourFavoriteSongsHere”: “Melodiile tale preferate aici”, “youtubePlaylistID”: “ID playlist YouTube” }

Turkish   { “about”: “Hakkında”, “accentChangeMsg”: “Vurgu rengi değiştirildi”, “accentColor”: “Vurgu rengi”, “add”: “Ekle”, “addToPlaylist”: “Çalma listesine ekle”, “addedSuccess”: “Başarıyla eklendi”, “album”: “Albüm”, “appUpdateAvailableAndDownloading”: “Uygulama güncellemesi mevcut ve indiriliyor”, “appUpdateIsAvailable”: “Uygulama güncellemesi mevcut”, “audioQuality”: “Ses kalitesi”, “audioQualityMsg”: “Ses kalitesi değiştirildi”, “backedupSuccess”: “Başarıyla yedeklendi”, “backupError”: “Veri yedekleme hatası”, “backupUserData”: “Kullanıcı verilerini yedekle”, “becomeSponsor”: “Sponsor ol”, “cacheMsg”: “Önbellek temizlendi”, “cancel”: “İptal”, “chooseBackupDir”: “Yedekleme Dizini Seç”, “chooseRestoreDir”: “Geri Yükleme Dosyası Dizini Seç”, “clear”: “Temizle”, “clearCache”: “Önbelleği temizle”, “clearSearchHistory”: “Arama Geçmişini Temizle”, “confirm”: “Onayla”, “confirmation”: “Onaylama”, “copyLogs”: “Günlükleri kopyala”, “copyLogsNoLogs”: “Kopyalanacak günlük bulunamadı”, “copyLogsSuccess”: "Günlükler başarıyla kopyalandı. ", “customPlaylistAddInstruction”: “YouTube çalma listesi eklerseniz, sadece YouTube çalma listesi kimliği alanını doldurun, kendi çalma listenizi oluşturursanız YouTube çalma listesi kimliğini boş bırakın ve sadece şunları doldurun: Ad, Resim bağlantısı (isteğe bağlı), Açıklama (isteğe bağlı)”, “customPlaylistDesc”: “Özel çalma listesi açıklaması”, “customPlaylistImgUrl”: “Özel çalma listesi resim bağlantısı”, “customPlaylistName”: “Özel çalma listesi adı”, “downloadAppUpdate”: “Uygulama güncellemesini indir”, “dynamicColor”: “Dinamik vurgu rengi (Android 12+)”, “error”: “Bir şeyler ters gitti”, “errorWhileRequestingPerms”: “İzin istenirken hata oluştu”, “home”: “Ana Sayfa”, “language”: “Dil”, “languageMsg”: “Dil değiştirildi”, “licenses”: “Lisanslar”, “lyrics”: “Şarkı sözleri”, “lyricsNotAvailable”: “Şarkı sözü mevcut değil ;(”, “more”: “Daha fazla”, “noLikedPlaylists”: “Henüz beğendiğiniz bir çalma listeniz yok”, “notYTlist”: “Bu bir YouTube çalma listesi kimliği değil”, “nothingFound”: “Hiçbir şey bulunamadı”, “nowPlaying”: “Şimdi çalıyor”, “others”: “Diğerleri”, “pages”: “Sayfalar”, “playlist”: “Çalma listesi”, “playlistUpdated”: “Çalma listesi başarıyla güncellendi”, “playlists”: “Çalma listeleri”, “provideIdOrNameError”: “Lütfen bir YouTube kimliği veya özel çalma listesi adı girin”, “queueInitText”: “Kuyruk başlatılıyor…”, “recentlyPlayed”: “Son Çalınanlar”, “recommendedForYou”: “Sizin için önerilenler”, “remove”: “Kaldır”, “removePlaylistQuestion”: “Bu çalma listesini kaldırmak istediğinizden emin misiniz?”, “removeSearchQueryQuestion”: “Bu arama sorgusunu kaldırmak istediğinizden emin misiniz?”, “restoreError”: “Veri geri yükleme hatası”, “restoreUserData”: “Kullanıcı verilerini geri yükle”, “restoredSuccess”: “Başarıyla geri yüklendi”, “search”: “Ara”, “searchHistoryMsg”: “Arama geçmişi temizlendi”, “settingChangedMsg”: “Ayar değiştirildi”, “settings”: “Ayarlar”, “songRemoved”: “Şarkı başarıyla kaldırıldı!”, “songs”: “şarkılar”, “sponsorProject”: “Projeye sponsor ol”, “suggestedArtists”: “Önerilen sanatçılar”, “suggestedPlaylists”: “Önerilen çalma listeleri”, “themeMode”: “Tema modu”, “tools”: “Araçlar”, “undo”: “geri al”, “userLikedPlaylists”: “Kullanıcının beğendiği çalma listeleri”, “userLikedSongs”: “Kullanıcının beğendiği şarkılar”, “userPlaylists”: “Kullanıcı çalma listeleri”, “yourFavoriteSongsHere”: “Favori şarkılarınız burada”, “youtubePlaylistID”: “YouTube çalma listesi kimliği” }

**Comment by gokadzev** [comment]
@OmarNazzal150 It's not a good idea to add a multitude of languages if it's unnecessary. I added around 22 languages, and it wasn't required. Moreover, nobody, except for me, was translating them, which was quite laborious.

**Comment by OmarNazzal150** [comment]
So I can only request once, not multiple languages is that right

**Comment by gokadzev** [comment]
> So I can only request once, not multiple languages is that right

No, you can request languages if:

- You know that language well and can translate yourself
- Language is often-used and not considered as unnecessary for at the moment
- If you will be active contributor/translator (Making pull requests as soon as translations are updated)
