### ISSUE TITLE
[Bug] Cannot add Youtube playlist by id

### ISSUE THREAD

**Issue by iniOr** [gokadzev/Musify#325]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

When try to add id from this playlist : https://www.youtube.com/watch?v=j1tqE1y-aqI&list=OLAK5uy_mO9ic23lmE4O2bsjD0DwTNDrYI7JBHv80

So id : `OLAK5uy_mO9ic23lmE4O2bsjD0DwTNDrYI7JBHv80`

Get error "not a yt playlist", trying with another playlist works : `PL4ELCxhcCUmZv58ASoIjjPyzwppluNWTe`

### Expected Behavior

Adding a playlist by id should works for any playlist on youtube.

### Steps To Reproduce

1. Open the app
2. try to add playlist by id
3. get message "not a playlist"

### Musify Version

7.0.1

### Device And Operating System

Samsung galaxy S23 Ultra

### Android Version You Use

Android 14

### Additional Information

App installed from F-droid.

**Comment by gokadzev** [comment]
> ### Acknowledgements
> * [x]  I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
> * [x]  I will fill out all the sections in this issue report.
> 
> ### Current Behavior
> When try to add id from this playlist : https://www.youtube.com/watch?v=j1tqE1y-aqI&list=OLAK5uy_mO9ic23lmE4O2bsjD0DwTNDrYI7JBHv80
> 
> So id : `OLAK5uy_mO9ic23lmE4O2bsjD0DwTNDrYI7JBHv80`
> 
> Get error "not a yt playlist", trying with another playlist works : `PL4ELCxhcCUmZv58ASoIjjPyzwppluNWTe`
> 
> ### Expected Behavior
> Adding a playlist by id should works for any playlist on youtube.
> 
> ### Steps To Reproduce
> 1. Open the app
> 2. try to add playlist by id
> 3. get message "not a playlist"
> 
> ### Musify Version
> 7.0.1
> 
> ### Device And Operating System
> Samsung galaxy S23 Ultra
> 
> ### Android Version You Use
> Android 14
> 
> ### Additional Information
> App installed from F-droid.

Thanks for reporting, will be fixed in the next version
