### ISSUE TITLE
[Bug] F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [gokadzev/Musify#328]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/5803659496#L660

**Comment by gokadzev** [comment]
> ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/5803659496#L660

Thank you for informing! My bad, I released version which broke things so I had to delete as soon as possible and release new one with additional commits but I forgot to recreate tag so it has previous commit as the latest commit (which was removed with force push)

**Comment by gokadzev** [comment]
Okay I will re-release 7.1.1 again.

**Comment by gokadzev** [comment]
@licaon-kter That's it, it shouldn't have any problem anymore.

**Comment by licaon-kter** [comment]
Let me check...brb

**Comment by licaon-kter** [comment]
Good, thanks https://gitlab.com/fdroid/fdroiddata/-/commit/10f6f4298fd0c99a517eb4ecdb3be43726b188a7

**Comment by gokadzev** [comment]
@licaon-kter Sorry for the tagging, as its last version is 7.1.2 on F-droid, which was released a month ago. Are there any problems connected with building again?

**Comment by licaon-kter** [comment]
Not that I know, but will take a look

**Comment by licaon-kter** [comment]
7.2.0 was still versionCode 77 like 7.1.2 (by mistake) hence no new version

**Comment by gokadzev** [comment]
> 7.2.0 was still versionCode 77 like 7.1.2 (you forgot to bump it to 78 I guess) hence no **new** version detected...

Oh yes, In the one version I forgot to bump versionCode. Is there any problem now or it will detect version code 80 itself?

**Comment by gokadzev** [comment]
@licaon-kter Any issue from my side?

```
2024-01-22 08:48:07,376 DEBUG: ..got package=None, version=None, vercode=None
2024-01-22 08:48:07,376 DEBUG: ...couldn't get autoname
```

**Comment by licaon-kter** [comment]
```
...
2024-01-25 13:36:04,353 INFO: ...updating to version 7.4.0 (82)
2024-01-25 13:36:04,354 INFO: ...auto-generating build for 7.4.0
...
```

autoupdate works fine, just have patience :)

**Comment by gokadzev** [comment]
Version 7.4.0 doesn't request any permissions, especially storage read/write permissions, but the F-Droid build still requests them (as indicated in the info page). Should I add or remove lines in the F-Droid separate manifest? Although, it shouldn't be added automatically only for F-Droid builds, so I wonder why it is included.

```
...
- read the contents of your shared storage
Allows the app to read the contents of your shared storage.
(12L)
...
```

**Comment by licaon-kter** [comment]
https://gitlab.com/fdroid/fdroiddata/-/jobs/6519094608#L768

oh, we need 17 now, let's add it


fail to repro?  https://gitlab.com/fdroid/fdroiddata/-/jobs/6520020801#L694

`Binary files libflutter.so and ... differ` means that we didn't use the same Flutter version, but I see we extracted 3.19.5 just fine: https://gitlab.com/fdroid/fdroiddata/-/jobs/6520020801#L378 per https://github.com/gokadzev/Musify/blob/2024.3.31/pubspec.yaml#L12

@gokadzev which Flutter version did you use?

**Comment by gokadzev** [comment]
> https://gitlab.com/fdroid/fdroiddata/-/jobs/6519094608#L768
> 
> oh, we need 17 now, let's add it
> 
> fail to repro? https://gitlab.com/fdroid/fdroiddata/-/jobs/6520020801#L694
> 
> `Binary files libflutter.so and ... differ` means that we didn't use the same Flutter version, but I see we extracted 3.19.5 just fine: https://gitlab.com/fdroid/fdroiddata/-/jobs/6520020801#L378 per https://github.com/gokadzev/Musify/blob/2024.3.31/pubspec.yaml#L12
> 
> @gokadzev which Flutter version did you use?

I indeed used 3.19.5, I haven't changed anything than JAVA version which you meant that you have already corrected. I have no idea what's the problem

**Comment by gokadzev** [comment]
I can try adding a dummy commit and trigger the workflow to be updated release apks if you want.

**Comment by gokadzev** [comment]
> Yes, please

Should I change the version too? As I need to recreate the tag.

**Comment by gokadzev** [comment]
> you can tell us the commit and attach the APK here (rename as ZIP, do not archive), it's enough to test

Sorry, I don't get it. The situation is like this:
- I can't build release apk locally witht the same key as I don't have it, Initially I created the key after creating this repository and configured it for Github workflows so I don't have it anymore.
- Neither I can run release workflow manually as with my configuration it runs only when commit name includes certain update text.
- I can undo commits and force-push the last two commits so it will run workflow but the problem will be unmatched commits between tag commit and release apk commit so it will give us error again. That's why I thought about recreating tag.

or we just can skip this version and add next version (In case of need, that's not a problem for me)

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/jobs/6562547797 2024.4.5 also failed.

**Comment by gokadzev** [comment]
> https://gitlab.com/fdroid/fdroiddata/-/jobs/6562547797 2024.4.5 also failed.

Definitely something with Fdroid workflow, I haven't changed anything than: JAVA version, ndk version and I turned on splits/abi filter in build.gradle.

I will check again carefully but I think in this case I will need help to find out what's the problem.

**Comment by gokadzev** [comment]
Unfortunately, I tried to figure out what's the difference between fdroid workflow and github fdroid workflow, but I found nothing.

These are the only changes I made after 7.6.2: https://github.com/gokadzev/Musify/compare/7.6.2...2024.4.5

**Comment by gokadzev** [comment]
Hi @IzzySoft, Sorry for tagging. Could you help me fix this problem?

**Comment by IzzySoft** [comment]
Sorry, but I'm no Android developer – so no. If Licaon has no clue there why a build fails, I'm even less likely to know.

But wait, it's not the build itself that fails, it's the RB check. And it's a Flutter app, plus the errors reported are in libs. That's usually either due to the embedded paths (Flutter embeds the full path into libs, and if directory structures are different thus the binaries are, too) or to different Flutter versions. I cannot tell you how to fix that, though. You two have consulted [HOWTO: diff & fix APKs for Reproducible Builds](https://gitlab.com/fdroid/wiki/-/wikis/HOWTO:-diff-&-fix-APKs-for-Reproducible-Builds#differing-so-files-can-be-hard-to-fix) already, haven't you?

**Comment by gokadzev** [comment]
> Sorry, but I'm no Android developer – so no. If Licaon has no clue there why a build fails, I'm even less likely to know.
> 
> But wait, it's not the build itself that fails, it's the RB check. And it's a Flutter app, plus the errors reported are in libs. 

I'm aware of it, I thought it would be more workflow problem than code itself. I'll check again by myself what happens then.

**Comment by IzzySoft** [comment]
No, no workflow issue. It's producing the APK alright, but it's not identical to yours (differences in those `*.so` files). Someone more familiar with reproducible builds than I am could probably get more details of it, by taking both APKs and comparing those `*.so` files.

@licaon-kter you or linsui were using diffoscope, that should help you with that.

**Comment by gokadzev** [comment]
Okay, so I have several doubts about the problem.

- Does fdroid use the same NDK version as Musify? (I changed it recently - ea0d5c7c0efc59f6da844e3352a3b261720e75e9)
- I upgraded gradle too but it should have nothing to do with that as I had done this before too.
- I add splits abi in build.gradle in order to avoid multiple run commands for non-fdroid build workflow (but splits are enabled for fdroid builds too now - 9ce80cf7d204d35ef9f5220134c84c632af06423)

**Comment by gokadzev** [comment]
> Sorry, but I'm no Android developer – so no. If Licaon has no clue there why a build fails, I'm even less likely to know.
> 
> But wait, it's not the build itself that fails, it's the RB check. And it's a Flutter app, plus the errors reported are in libs. That's usually either due to the embedded paths (Flutter embeds the full path into libs, and if directory structures are different thus the binaries are, too) or to different Flutter versions. I cannot tell you how to fix that, though. You two have consulted [HOWTO: diff & fix APKs for Reproducible Builds](https://gitlab.com/fdroid/wiki/-/wikis/HOWTO:-diff-&-fix-APKs-for-Reproducible-Builds#differing-so-files-can-be-hard-to-fix) already, haven't you?

Idk if I'll be able to do it but how to get fdroid release apk to check difference

**Comment by licaon-kter** [comment]
@gokadzev we can check or you can open a MR updating the recipe and the CI will do it for you :wink: 

Are you ready? Which commit and where's the APK? :stuck_out_tongue:

**Comment by gokadzev** [comment]
> @gokadzev we can check or you can open a MR updating the recipe and the CI will do it for you 😉
> 
> Are you ready? Which commit and where's the APK? 😛


This one, it's the latest one that failed. https://github.com/gokadzev/Musify/releases/tag/2024.4.5

I'm sure flutter version is the same, I doubt about ndk version change but I'm not sure if it matters for fdroid workflow. So if it's possible please tell me how to obtain additional information about differences between above mentioned release and that one fdroid built from source

**Comment by gokadzev** [comment]
> @gokadzev we can check or you can open a MR updating the recipe and the CI will do it for you 😉
> 
> Are you ready? Which commit and where's the APK? 😛

> @gokadzev we can check or you can open a MR updating the recipe and the CI will do it for you 😉
> 
> Are you ready? Which commit and where's the APK? 😛


This one, it's the latest one that failed. https://github.com/gokadzev/Musify/releases/tag/2024.4.5

@licaon-kter  I'm sure flutter version is the same, I doubt about ndk version change but I'm not sure if it matters for fdroid workflow. So if it's possible please tell me how to obtain additional information about differences between above mentioned release and that one fdroid built from source

**Comment by gokadzev** [comment]
I hope I understood correctly what you've asked.

**Comment by licaon-kter** [comment]
Will test asap

One advantage of the MR is that the CI gives you an APK so you can just `apktool d` then `diffoscope` it vs yours.

**Comment by gokadzev** [comment]
> Will test asap
> 
> One advantage of the MR is that the CI gives you an APK so you can just `apktool d` then `diffoscope` it vs yours.

I tried diffoscope, nothing useful.

I'd like to ask you if we can add ndk version in the fdroid workflow, I highly suspect it's the cause of fails and I changed it because one of the plugins require it to be minimum:

```
android {
  ndkVersion "25.1.8937393"
  ...
}
```

**Comment by licaon-kter** [comment]
Added the NDK, still fails:
```
==== detail begin ====
verification of APK with copied signature failed
Comparing reference APK to APK with copied signature...
Unexpected diff output:
Binary files /tmp/tmp88s4me_0/unsigned_binaries_com.gokadzev.musify.fdroid_91.binary/content/lib/arm64-v8a/libapp.so and /tmp/tmp88s4me_0/_tmp_tmp88s4me_0_sigcp_com.gokadzev.musify.fdroid_91/content/lib/arm64-v8a/libapp.so differ
Binary files /tmp/tmp88s4me_0/unsigned_binaries_com.gokadzev.musify.fdroid_91.binary/content/lib/arm64-v8a/libflutter.so and /tmp/tmp88s4me_0/_tmp_tmp88s4me_0_sigcp_com.gokadzev.musify.fdroid_91/content/lib/arm64-v8a/libflutter.so differ
Binary files /tmp/tmp88s4me_0/unsigned_binaries_com.gokadzev.musify.fdroid_91.binary/content/lib/armeabi-v7a/libapp.so and /tmp/tmp88s4me_0/_tmp_tmp88s4me_0_sigcp_com.gokadzev.musify.fdroid_91/content/lib/armeabi-v7a/libapp.so differ
Binary files /tmp/tmp88s4me_0/unsigned_binaries_com.gokadzev.musify.fdroid_91.binary/content/lib/armeabi-v7a/libflutter.so and /tmp/tmp88s4me_0/_tmp_tmp88s4me_0_sigcp_com.gokadzev.musify.fdroid_91/content/lib/armeabi-v7a/libflutter.so differ
Binary files /tmp/tmp88s4me_0/unsigned_binaries_com.gokadzev.musify.fdroid_91.binary/content/lib/x86_64/libapp.so and /tmp/tmp88s4me_0/_tmp_tmp88s4me_0_sigcp_com.gokadzev.musify.fdroid_91/content/lib/x86_64/libapp.so differ
Binary files /tmp/tmp88s4me_0/unsigned_binaries_com.gokadzev.musify.fdroid_91.binary/content/lib/x86_64/libflutter.so and /tmp/tmp88s4me_0/_tmp_tmp88s4me_0_sigcp_com.gokadzev.musify.fdroid_91/content/lib/x86_64/libflutter.so differ
==== detail end ====
```

... `libflutter.so differ` means _we didn't use the same Flutter version_

can you share the output of running `flutter doctor -v` ?

**Comment by gokadzev** [comment]
> Added the NDK, still fails:
> 
> ```
> ==== detail begin ====
> verification of APK with copied signature failed
> Comparing reference APK to APK with copied signature...
> Unexpected diff output:
> Binary files /tmp/tmp88s4me_0/unsigned_binaries_com.gokadzev.musify.fdroid_91.binary/content/lib/arm64-v8a/libapp.so and /tmp/tmp88s4me_0/_tmp_tmp88s4me_0_sigcp_com.gokadzev.musify.fdroid_91/content/lib/arm64-v8a/libapp.so differ
> Binary files /tmp/tmp88s4me_0/unsigned_binaries_com.gokadzev.musify.fdroid_91.binary/content/lib/arm64-v8a/libflutter.so and /tmp/tmp88s4me_0/_tmp_tmp88s4me_0_sigcp_com.gokadzev.musify.fdroid_91/content/lib/arm64-v8a/libflutter.so differ
> Binary files /tmp/tmp88s4me_0/unsigned_binaries_com.gokadzev.musify.fdroid_91.binary/content/lib/armeabi-v7a/libapp.so and /tmp/tmp88s4me_0/_tmp_tmp88s4me_0_sigcp_com.gokadzev.musify.fdroid_91/content/lib/armeabi-v7a/libapp.so differ
> Binary files /tmp/tmp88s4me_0/unsigned_binaries_com.gokadzev.musify.fdroid_91.binary/content/lib/armeabi-v7a/libflutter.so and /tmp/tmp88s4me_0/_tmp_tmp88s4me_0_sigcp_com.gokadzev.musify.fdroid_91/content/lib/armeabi-v7a/libflutter.so differ
> Binary files /tmp/tmp88s4me_0/unsigned_binaries_com.gokadzev.musify.fdroid_91.binary/content/lib/x86_64/libapp.so and /tmp/tmp88s4me_0/_tmp_tmp88s4me_0_sigcp_com.gokadzev.musify.fdroid_91/content/lib/x86_64/libapp.so differ
> Binary files /tmp/tmp88s4me_0/unsigned_binaries_com.gokadzev.musify.fdroid_91.binary/content/lib/x86_64/libflutter.so and /tmp/tmp88s4me_0/_tmp_tmp88s4me_0_sigcp_com.gokadzev.musify.fdroid_91/content/lib/x86_64/libflutter.so differ
> ==== detail end ====
> ```
> 
> ... `libflutter.so differ` means _we didn't use the same Flutter version_
> 
> can you share the output of running `flutter doctor -v` ?

run: https://github.com/gokadzev/Musify/actions/runs/8568008460/job/23480973634

![image](https://github.com/gokadzev/Musify/assets/79704324/b2b344fe-9dec-4d9b-8a18-1b5fb2c8952d)

**Comment by IzzySoft** [comment]
> ... `libflutter.so` differ means we didn't use the same Flutter version

If you've ruled out Flutter's embedded build path that is, [see here](https://gitlab.com/fdroid/wiki/-/wikis/HOWTO:-diff-&-fix-APKs-for-Reproducible-Builds#differing-so-files-can-be-hard-to-fix).

**Comment by licaon-kter** [comment]
@IzzySoft the paths are in the built `libapp.so` files, and we take care of the paths too: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.gokadzev.musify.fdroid.yml#L1011-L1015

now, of course there's the possibility that @gokadzev changed their local paths, but, I want to see `libflutter.so` being fixed first

@gokadzev wow, so same Flutter version indeed :(

**Comment by gokadzev** [comment]
Does Fdroid has any problem with ABI split?

**Comment by gokadzev** [comment]
@licaon-kter I reverted one commit (which provided native support for splitting per ABI). I can't check today if it will match the F-Droid build (the one it will generate in the future), right? Since it synchronizes after a few days.

**Comment by licaon-kter** [comment]
We can test, if we know the exact commit and have an APK built from that commit to compare against

**Comment by gokadzev** [comment]
> We can test, if we know the exact commit and have an APK built from that commit to compare against

Oh, great. I'll run a pre-release workflow (which is almost the same except I can run it manually and It doesn't create tag itself) and be right back with the apk and commit hash

**Comment by gokadzev** [comment]
@licaon-kter 

APK: https://github.com/gokadzev/Musify/releases/download/master/Musify_fdroid.apk
Commit: https://github.com/gokadzev/Musify/commit/6bbe7957a361e18bb13b448db131c105d5090aec

**Comment by gokadzev** [comment]
@licaon-kter

**Comment by gokadzev** [comment]
> @licaon-kter
> 
> APK: https://github.com/gokadzev/Musify/releases/download/master/Musify_fdroid.apk Commit: [6bbe795](https://github.com/gokadzev/Musify/commit/6bbe7957a361e18bb13b448db131c105d5090aec)

@licaon-kter Hello, any news?

**Comment by gokadzev** [comment]
@licaon-kter @linsui any problem if I revert to the old app versioning? (Except the need of reinstalling the app, as it can't be updated)

**Comment by gokadzev** [comment]
@licaon-kter I even released new version to make checking process easier, could you please check and notify me if it matches now?

**Comment by gokadzev** [comment]
> We can test, if we know the exact commit and have an APK built from that commit to compare against

Matched successfully: https://f-droid.org/repo/com.gokadzev.musify.fdroid_92.log.gz

just it still is not visible in releases

**Comment by licaon-kter** [comment]
Was just published, yes ;)

**Comment by gokadzev** [comment]
> Was just published, yes ;)

This time, F-Droid updated the workflow file, but CI has never run for V8.

**Comment by licaon-kter** [comment]
@gokadzev I can see the CI here: https://gitlab.com/fdroid/fdroiddata/-/jobs/6784392431

and its artefacts: https://gitlab.com/fdroid/fdroiddata/-/jobs/6784392431/artifacts/browse/tmp/

what do you mean?

**Comment by gokadzev** [comment]
> @gokadzev I can see the CI here: https://gitlab.com/fdroid/fdroiddata/-/jobs/6784392431
> 
> and its artefacts: https://gitlab.com/fdroid/fdroiddata/-/jobs/6784392431/artifacts/browse/tmp/
> 
> what do you mean?

Neither I wasn't able to find CI nor its update on [Fdroid](https://f-droid.org/packages/com.gokadzev.musify.fdroid/) so I thought it was skipped.

**Comment by licaon-kter** [comment]
Checkupdate job batches multiple apps, so if one app that should build before your app fails then the pipeline is stopped and your app is not tried. It's a possibility. :)

**Comment by gokadzev** [comment]
> Checkupdate job batches multiple apps, so if one app that should build before your app fails then the pipeline is stopped and your app is not tried. It's a possibility. :)

In this case my app was built correctly, I didn't get your point.
