### ISSUE TITLE
Feature to delete a  user playlist

### ISSUE THREAD

**Issue by Screenshared** [gokadzev/Musify#34]
Add the feature to let user delete personal playlist he added with YouTube link

**Comment by gokadzev** [comment]
> Add the feature to let user delete personal playlist he added with YouTube link

@Screenshared user playlist can be deleted with long press on it

**Comment by Screenshared** [comment]
It  doesn't work

**Comment by gokadzev** [comment]
> It doesn't work

@Screenshared 

1. go to settings
2. choose User Playlists
3. press and hold on playlist which you want to be removed

**Comment by gokadzev** [comment]
> It doesn't work. Nothing appears or delete

okay, thanks. i will check and fix if it won't work.

**Comment by gokadzev** [comment]
> It still doesn't work even with 1.8 Redmi note 7 android 10

i've checked several times and it does. you need to hold instead of click from User Playlists page
