### ISSUE TITLE
There is no download button ,it is in the screenshots [Bug] <title>

### ISSUE THREAD

**Issue by YousefGad** [gokadzev/Musify#345]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

No download button

### Expected Behavior

I just want to download music and play them offline

### Musify Version

7.5.0

### Device And Operating System

Redmi note 10 mojito/sunny

### Android Version You Use

Android 13

**Comment by gokadzev** [comment]
> ### Acknowledgements
> * [x]  I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
> * [x]  I will fill out all the sections in this issue report.
> 
> ### Current Behavior
> No download button
> 
> ### Expected Behavior
> I just want to download music and play them offline
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Musify Version
> 7.5.0
> 
> ### Device And Operating System
> Redmi note 10 mojito/sunny
> 
> ### Android Version You Use
> Android 13
> 
> ### Additional Information
> _No response_

Screenshots were taken from Version 7.0.0. Since 7.1.1, the "Download" feature has been replaced by the "Offline" feature. You can now make songs available offline and listen to them without an internet connection using Musify.
