### ISSUE TITLE
[Feature] youtube account login and sync

### ISSUE THREAD

**Issue by gmankab** [gokadzev/Musify#347]
### Is there an existing issue for this?

- [X] I have searched the existing issues and confirmed that this feature is not already requested.

### Category of the Feature

UX Improvements

### Credits

idk

### Pain

app has no sync

### Suggested Solution

youtube account login and sync please

### Useful Resources/References

idk

**Comment by gokadzev** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues and confirmed that this feature is not already requested.
> 
> ### Category of the Feature
> UX Improvements
> 
> ### Credits
> idk
> 
> ### Pain
> app has no sync
> 
> ### Suggested Solution
> youtube account login and sync please
> 
> ### Useful Resources/References
> idk

Neither plugin gives me the possibility of that, nor would I prefer using YouTube for that when Spotify exists.
