### ISSUE TITLE
How do i know i am playing from the downloaded songs?

### ISSUE THREAD

**Issue by ryanjoejames** [gokadzev/Musify#35]
When i click download, nothing happens?
Cannot locate the folder as well.

How do i know i am playing from the downloaded songs?
Any means to differentiate if i streaming or playing from local storage?

**Comment by gokadzev** [comment]
> When i click download, nothing happens? Cannot locate the folder as well.
> 
> How do i know i am playing from the downloaded songs? Any means to differentiate if i streaming or playing from local storage?

@ryanjoejames app supports streaming only, you can't play downloaded songs with Musify. you can listen it online or download them.

downloaded songs will be added in "Music" folder

**Comment by gokadzev** [comment]
i will add this issue as feature request for offline music listen support.
