### ISSUE TITLE
Radio or similar songs support 

### ISSUE THREAD

**Issue by sggo15** [gokadzev/Musify#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues and confirmed that this feature is not already requested.

### Category of the Feature

Logical Improvements

### Credits

Me

### Pain

When I search and play a single song, after it ends, songs of the same genre or similar do not play. 
I mean song radio support 
Thanks

### Suggested Solution

Can you add radio feature like yt music?

### Useful Resources/References

Idk

**Comment by sggo15** [comment]
Sorry if I did any mistake or wasted your time.

**Comment by gokadzev** [comment]
> Sorry if I did any mistake or wasted your time.

No, it's all good. You can freely share your ideas here. Don't close it, I will consider your suggestion.

**Comment by sggo15** [comment]
Do you understand what I mean? 

For example, I played a single Indian song by searching, and after it ends, similar Indian songs do not play. in queue 
Hope u understood .

**Comment by gokadzev** [comment]
> Do you understand what I mean?
> 
> For example, I played a single Indian song by searching, and after it ends, similar Indian songs do not play. in queue Hope u understood .

Yeah, the initial version of this feature already exists on the 'now playing' page, where you have the autoplay next icon (located at the bottom, the last one). However, the similarity of the next song is in doubt (similar to the recommendations on the homepage), so the algorithm can be improved.

**Comment by gokadzev** [comment]
> > > Do you understand what I mean?
> > > For example, I played a single Indian song by searching, and after it ends, similar Indian songs do not play. in queue Hope u understood .
> > 
> > 
> > Yeah, the initial version of this feature already exists on the 'now playing' page, where you have the autoplay next icon (located at the bottom, the last one). However, the similarity of the next song is in doubt (similar to the recommendations on the homepage), so the algorithm can be improved.
> 
> Can't we get the radio list from a song using yt music api? or reverse engg. it?

Will be pretty difficult, as I don't use yt music api.

**Comment by gokadzev** [comment]
In the latest version I added "default algorithm recommendations" so you can use it for getting better suggestions.
