### ISSUE TITLE
Differentiate between streaming or playing from local storage

### ISSUE THREAD

**Issue by ryanjoejames** [gokadzev/Musify#36]
Differentiate between streaming or playing from local storage

**Comment by gokadzev** [comment]
> Differentiate between streaming or playing from local storage

you can listen music online or download them but you can't listen downloaded songs with our app.

**Comment by gokadzev** [comment]
> Does it show also external sd audio files?

yes, it's showing external storage audio files currently. that may be reason why it won't show downloaded songs from app. if that will happen, you can move Musify downloaded songs from internal storage to external storage (it's located in Musify/Songs folder)
