### ISSUE TITLE
Ability to Change Region and other related Features.

### ISSUE THREAD

**Issue by 1YuvrajS** [gokadzev/Musify#367]
### Is there an existing issue for this?

- [X] I have searched the existing issues and confirmed that this feature is not already requested.

### Category of the Feature

Code Refactor, Unable to categorize

### Credits

Me

### Pain

- [ ] Allow us/users to change the Spotify region, where we wanted to listen.
- [ ] Downloading Any song to storage, it doesn't come with applied tag metadata ( Info and Artwork ) but I have to it manually.
- [ ] Spotify Sign in for Library Histories etc.
- [ ] It doesn't give more Spotify like Home screen, what we wanted to look for.

### Suggested Solution

Nil

**Comment by gokadzev** [comment]
Musify doesn't use anything of Spotify at the moment. I'd suggest you checking #340
