### ISSUE TITLE
[Feature] There Should be an IOS Version of this App

### ISSUE THREAD

**Issue by Prrimcord** [gokadzev/Musify#368]
### Is there an existing issue for this?

- [X] I have searched the existing issues and confirmed that this feature is not already requested.

### Category of the Feature

Unable to categorize

### Credits

Me

### Pain

I think this should be multi-platform and there should be an ios version and android version both at the same time.

### Suggested Solution

I just request you to show me how to build the ios version, so that i can test it on my iphone!

### Useful Resources/References

none

**Comment by gokadzev** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues and confirmed that this feature is not already requested.
> 
> ### Category of the Feature
> Unable to categorize
> 
> ### Credits
> Me
> 
> ### Pain
> I think this should be multi-platform and there should be an ios version and android version both at the same time.
> 
> ### Suggested Solution
> I just request you to show me how to build the ios version, so that i can test it on my iphone!
> 
> ### Useful Resources/References
> none

The running code is the same. just install flutter on your mac and run with the command:

```bash

flutter run --flavor github

```


Several people tried to build the iOS version, but there were some issues I couldn't assist with due to lack of access to a Mac or iPhone.

**Comment by Prrimcord** [comment]
> > ### Is there an existing issue for this?
> > 
> > * [x]   I have searched the existing issues and confirmed that this feature is not already requested.
> > 
> > ### Category of the Feature
> > Unable to categorize
> > ### Credits
> > Me
> > ### Pain
> > I think this should be multi-platform and there should be an ios version and android version both at the same time.
> > ### Suggested Solution
> > I just request you to show me how to build the ios version, so that i can test it on my iphone!
> > ### Useful Resources/References
> > none
> 
> The running code is the same. just install flutter on your mac and run with the command:
> 
> ```shell
> flutter run --flavor github
> ```
> 
> Several people tried to build the iOS version, but there were some issues I couldn't assist with due to lack of access to a Mac or iPhone.

Ok Thanks for the help!
