### ISSUE TITLE
[Bug] It doesn't let me build the release apk

### ISSUE THREAD

**Issue by Prrimcord** [gokadzev/Musify#369]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

![Screenshot 2024-03-29 022838](https://github.com/gokadzev/Musify/assets/103951992/5d35b76f-ddd0-42a8-84d9-6978d5de8225)

### Expected Behavior

It should let me build it but it always shows this error

### Steps To Reproduce

1.Open the folder
2.Open the terminal
3.Type Flutter build apk

### Musify Version

2024.3.24

### Device And Operating System

Android API 34 Google Play | x86_64

### Android Version You Use

Android 14

**Comment by gokadzev** [comment]
It says the error, you need to have a key.jks in android/app and change its properties in build.gradle or easier way: just use build > generate signed app from android studio.
