### ISSUE TITLE
Icon appears tiny in notification area.

### ISSUE THREAD

**Issue by BloodRaven0** [gokadzev/Musify#37]
**Describe the bug**
The monochrome icon that appears in the notification area and on the actual notification is like 3 times smaller than the space allows.

**Expected behavior**
It should be bigger, taking up as much space as other icons.

**Screenshots**
![Screenshot_20220623-201815_OctoDroid](https://user-images.githubusercontent.com/42444745/175357483-1a6a4ceb-5b39-4d78-9409-af23de74d91d.png)
![Screenshot_20220623-201841_OctoDroid](https://user-images.githubusercontent.com/42444745/175357504-34d83538-5831-4e2d-b7a2-b197d9bd0438.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Poco X3 NFC]
 - OS: [e.g. Android 10, Resurrection Remix 8.6.9]
 - App Version [e.g. v1.2.0, 1.8.0]

**Comment by gokadzev** [comment]
> **Describe the bug** The monochrome icon that appears in the notification area and on the actual notification is like 3 times smaller than the space allows.
> 
> **Expected behavior** It should be bigger, taking up as much space as other icons.
> 
> **Screenshots** ![Screenshot_20220623-201815_OctoDroid](https://user-images.githubusercontent.com/42444745/175357483-1a6a4ceb-5b39-4d78-9409-af23de74d91d.png) ![Screenshot_20220623-201841_OctoDroid](https://user-images.githubusercontent.com/42444745/175357504-34d83538-5831-4e2d-b7a2-b197d9bd0438.png)
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. Poco X3 NFC]
> * OS: [e.g. Android 10, Resurrection Remix 8.6.9]
> * App Version [e.g. v1.2.0, 1.8.0]

it should be your font fault, icon size is good.

**Comment by BloodRaven0** [comment]
@gokadzev I don't think font has any bearing on the size of icons. None of the other apps' icons have ever appeared this way on my device.

**Comment by gokadzev** [comment]
> @gokadzev I don't think font has any bearing on the size of icons. None of the other apps' icons have ever appeared this way on my device.

i will review but if plugin hasn't configuration feature for icon size, i can't do anything with that

**Comment by gokadzev** [comment]
> @gokadzev I don't think font has any bearing on the size of icons. None of the other apps' icons have ever appeared this way on my device.

font hasn't. just your font size is large so i thought that may be reason why icon seems like small but i will review if i can increase it.
