### ISSUE TITLE
[Feature] ability to search in playlists and offline songs also sort by alphabetical order or date

### ISSUE THREAD

**Issue by robinix** [gokadzev/Musify#374]
### Is there an existing issue for this?

- [X] I have searched the existing issues and confirmed that this feature is not already requested.

### Category of the Feature

UI Improvements

### Credits

tesseract

### Pain

Being able to search big playlists and not manually finding songs is a big improvement also finding songs on user offline songs while not having internet access, ability to sort by multiple options like date added , alphabetical order or custom order

### Suggested Solution

A field to search for songs in playlists and a button with sorting options

**Comment by gokadzev** [comment]
@robinix 
> Being able to search big playlists and not manually finding songs 
> finding songs on user offline songs while not having internet access

Both of them are already available, I don't know what you mean.

**Comment by gokadzev** [comment]
If the issue is about adding a sort option, please don't include more features (especially already included ones) too. (You can use edit feature to correct it)

**Comment by robinix** [comment]
@gokadzev I think you misunderstood me, the only available searching option in the app is searching for songs in the general database, there is no way to search your playlist while being offline or online, I attached two referenced images
![Uploading Screenshot_20240402_18
![Screenshot_20240402_183159_Spotify](https://github.com/gokadzev/Musify/assets/16867292/4ec9c526-72cf-44d0-bdee-b870a12a9a83)
3103_Spotify.jpg…]()

**Comment by robinix** [comment]
![Screenshot_20240402_183103_Spotify](https://github.com/gokadzev/Musify/assets/16867292/18696107-5e4e-49c0-aacd-334b36c6f7b2)

**Comment by robinix** [comment]
![Screenshot_20240402_183159_Spotify](https://github.com/gokadzev/Musify/assets/16867292/7b47d025-b7a4-4a78-80e9-88d30554a1c3)

**Comment by gokadzev** [comment]
> @gokadzev I think you misunderstood me, the only available searching option in the app is searching for songs in the general database, there is no way to search for songs in your manually created playlist while being offline or online, I attached two referenced images

Okay thanks, now it's clear.

**Comment by gokadzev** [comment]
Sorting with artist and song title added. Suggestion is partially done. About search bar in playlists, I will think about that.
