### ISSUE TITLE
[Feature] Continous play of next songs in playlist after playback ends

### ISSUE THREAD

**Issue by Maxisixo** [gokadzev/Musify#376]
### Is there an existing issue for this?

- [X] I have searched the existing issues and confirmed that this feature is not already requested.

### Category of the Feature

Logical Improvements, More Efficiency

### Credits

Maxisixo

### Pain

Right now when a song in your playlist ends, playback stops and it doesn't automatically play the next song in playlist.

### Suggested Solution

Add the ability for next songs in playlist to be played in order automatically after playback ends. Being able to manually pick the next songs also would be good

**Comment by gokadzev** [comment]
It's already added, but the thing is, you need to play the playlist using the play button and not by selecting any song from the playlis

**Comment by Maxisixo** [comment]
@gokadzev  Would it be possible to implement it the way i mentioned? For large playlists you usually don't start from the top and choose a specific song to start from there, continuous playback in order and a way to make a custom queue would be nice, thank you for the amazing app

**Comment by gokadzev** [comment]
> @gokadzev Would it be possible to implement it the way i mentioned? For large playlists you usually don't start from the top and choose a specific song to start from there, continuous playback in order.

I just got an idea, so I guess you can expect it in the next release. 

> continuous playback in order and a way to make a custom queue would be nice

Although custom queue won't be implemented as there are other alternatives such as liking songs, creating custom playlists that can handle the same functionality.

**Comment by Maxisixo** [comment]
Appreciate it 🙏

**Comment by gokadzev** [comment]
Done in
