### ISSUE TITLE
[Bug] "Add to playlist" overflows

### ISSUE THREAD

**Issue by euuurgh** [gokadzev/Musify#381]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

When there are more than 11 playlists, the "+" button of songs opens the "Add to playlist menu", but the 12th playlist overflows and can not get clicked on, as that results in the menu being closed without the song being added to the playlist

### Expected Behavior

Be able to scroll to the desired playlist, all the contents being within the bounds of the menu

### Steps To Reproduce

Create 12 playlists (depending on screen height, this might be more)
Go to a song
Click the plus
observe menu overflowing

### Musify Version

2024.4.5

### Device And Operating System

Xiaomi Mi A2 Lite

### Android Version You Use

Android 12

**Comment by gokadzev** [comment]
> ### Acknowledgements
> * [x]  I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
> * [x]  I will fill out all the sections in this issue report.
> 
> ### Current Behavior
> When there are more than 11 playlists, the "+" button of songs opens the "Add to playlist menu", but the 12th playlist overflows and can not get clicked on, as that results in the menu being closed without the song being added to the playlist
> 
> ### Expected Behavior
> Be able to scroll to the desired playlist, all the contents being within the bounds of the menu
> 
> ### Steps To Reproduce
> Create 12 playlists (depending on screen height, this might be more) Go to a song Click the plus observe menu overflowing
> 
> ### Musify Version
> 2024.4.5
> 
> ### Device And Operating System
> Xiaomi Mi A2 Lite
> 
> ### Android Version You Use
> Android 12
> 
> ### Additional Information
> _No response_

Thanks! I noticed it several days ago, and I already have a fix for that. It will be fixed in the next release.

**Comment by euuurgh** [comment]
Awesome, thanks, and great work with the project otherwise!

**Comment by gokadzev** [comment]
Fixed with 3c6635e
