### ISSUE TITLE
[Bug] Modo aleatorio

### ISSUE THREAD

**Issue by Pejino** [gokadzev/Musify#383]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

El modo aleatorio de reproducción se desactiva al cerrar la aplicación. Además, cuando la reproducción aleatoria selecciona la última canción de la lista de reproducción, y ésta llega al final, la aplicación deja de reproducir. 

### Expected Behavior

Sería ideal que el modo aleatorio tuviera un botón para comenzar a reproducir sin tener que seleccionar el primer tema. Y que no dejara de reproducir en ningún momento. Que una vez reproducidas todas las canciones de la lista, continuara seleccionando al azar. 

### Steps To Reproduce

1 abro la aplicación
2 selecciono lista de reproducción
3 selecciono canción en la lista
4 activo modo aleatorio

### Musify Version

8.0.0.

### Device And Operating System

Xiaomi Poco F5 pro

### Android Version You Use

Android 14

### Additional Information

Gracias por su trabajo!

**Comment by gokadzev** [comment]
I think we can freely close it as completed :)
