### ISSUE TITLE
[Feature] album search

### ISSUE THREAD

**Issue by GamzeeRakoon** [gokadzev/Musify#387]
### Is there an existing issue for this?

- [X] I have searched the existing issues and confirmed that this feature is not already requested.

### Category of the Feature

UI Improvements, Logical Improvements, UX Improvements

### Credits

me

### Pain

i would like to listen to albums but can only search up individual songs and then listen to them

### Suggested Solution

add albums support which looks at metadata and automatically adds to them to the correct album

**Comment by gokadzev** [comment]
> add albums support which looks at metadata and automatically adds to them to the correct album

The problem is that YouTube doesn't provide metadata such as albums, release years, artist names and etc... Even the artist names are provided by my custom implementation. we only get the song name in one line.

**Comment by iparks99** [comment]
Can you use something like MusicBrainz to grab metadata that YouTube doesn't provide?

**Comment by gokadzev** [comment]
> Can you use something like MusicBrainz to grab metadata that YouTube doesn't provide?

Even if I did such a thing, YouTube still doesn't provide albums, so it would be totally useless. Such features require platform integrations with services like YouTube Music or Spotify. I neither have enough time to start integrating them, nor is it worth it. I have already spent enough time on this project with no benefits.
