### ISSUE TITLE
[Bug] The app crashes on 1st song

### ISSUE THREAD

**Issue by MateMorei** [gokadzev/Musify#388]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

Hi, whenever I play the first song for the first time I run the app, Musify crashes. My phone locks and takes quite time to run the app properly. This issue magnified when the bug made my phone reboot.

Sorry about my English.

### Expected Behavior

Hope this bug can be solved some time because the app is amazing.

### Musify Version

8.0.0

### Device And Operating System

Samsung A21s

### Android Version You Use

Android 12

**Comment by gokadzev** [comment]
> My phone locks and takes quite time to run the app properly. This issue magnified when the bug made my phone reboot.

Strange, any chance you use custom rom? sounds system-related problem as casual bug even with crash shouldn't do that.

**Comment by MateMorei** [comment]
Hi. I don't use a custom ROM but as you mention it could be a
system-related problem, I took my phone to service a couple months ago to
change its screen module cause it had fallen and broken before. Since that,
sometimes it works weirdly, so perhaps it's that. I'll keep an eye on it.

Thank you in advance.

**Comment by gokadzev** [comment]
> Hi. I don't use a custom ROM but as you mention it could be a system-related problem, I took my phone to service a couple months ago to change its screen module cause it had fallen and broken before. Since that, sometimes it works weirdly, so perhaps it's that. I'll keep an eye on it. Thank you in advance. 

Is there any chance you could take logs using a PC if you have access to it?

**Comment by gokadzev** [comment]
@MateMorei Hi, is there any chance you could take logs using a PC if you have access to one? It's most likely something related to the OS, but I'd still like to see what exactly it is.

**Comment by gokadzev** [comment]
Closing the issue for now but still feel free to send logs here if you manage.
