### ISSUE TITLE
Brazilian Portuguese translation

### ISSUE THREAD

**Issue by JonatasVi** [gokadzev/Musify#39]
If possible, I would like to translate the application into Brazilian Portuguese, but I would like you to send me the files, which makes it easier

**Comment by gokadzev** [comment]
@JonatasVi change only second side like this "don't touch this" : "translate this"


[app_pt.txt](https://github.com/gokadzev/Musify/files/8988715/app_pt.txt)

**Comment by JonatasVi** [comment]
@gokadzev 
[app_pt.txt](https://github.com/gokadzev/Musify/files/9006398/app_pt.txt)
