### ISSUE TITLE
[Bug] YouTube updated their API

### ISSUE THREAD

**Issue by YUG38** [gokadzev/Musify#395]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

Meaning most stuff that runs on API won't work, for example playlist pulling from playlist ID

### Expected Behavior

N/A

### Steps To Reproduce

N/A

### Musify Version

8.2.0

### Device And Operating System

Realme N300

### Android Version You Use

Android 14

**Comment by gokadzev** [comment]
@YUG38 Hello, currently everything is working. What's the source of that information?

**Comment by YUG38** [comment]
@gokadzev SOOO, the thing is, yesterday, i tried to use my main FOSS app for yt music, and it was having issues with like "unkown" songs and playlist and stuff so then i tried other ones and ALL of them were having either same or similar issues so then i looked at their github "issues" and most of them had atleast one open with the issue mentioned and so then i found this one https://github.com/z-huang/InnerTune/issues/1295, and thats where i learned about it, and no musify wasnt working for me yesterday either

**Comment by gokadzev** [comment]
> @gokadzev SOOO, the thing is, yesterday, i tried to use my main FOSS app for yt music, and it was having issues with like "unkown" songs and playlist and stuff so then i tried other ones and ALL of them were having either same or similar issues so then i looked at their github "issues" and most of them had atleast one open with the issue mentioned and so then i found this one [z-huang/InnerTune#1295](https://github.com/z-huang/InnerTune/issues/1295), and thats where i learned about it, and no musify wasnt working for me yesterday either

Okay, thank you so much for informing :)

**Comment by YUG38** [comment]
@gokadzev Np :), FYI, everything that requires the API isnt working, just so you know you dont have to look for much 😛

**Comment by gokadzev** [comment]
> @gokadzev Np :), FYI, everything that requires the API isnt working, just so you know you dont have to look for much 😛

I just checked again, everything works in Musify. So I think I can freely close the issue
