### ISSUE TITLE
[Feature] Make the purpose of a music note button clear

### ISSUE THREAD

**Issue by S0nter** [gokadzev/Musify#398]
### Is there an existing issue for this?

- [X] I have searched the existing issues and confirmed that this feature is not already requested.

### Category of the Feature

UX Improvements

### Credits

me

### Pain

The purpose of this button on Now Playing page is not clear:
![image](https://github.com/gokadzev/Musify/assets/108224581/7a9d713c-0338-42f1-8c00-a27051c86631)

There is no tooltip to communicate that turning on this button will automatically play songs from [this playlist](https://www.youtube.com/playlist?list=PLgzTt0k8mXzEk586ze4BjvDXR7c-TUSnx).

I was able to understand the functionality of this button only after checking the [source code](https://github.com/gokadzev/Musify/blob/ff31044ae46e4dd57380866db7781bb204c1b7b3/lib/API/musify.dart#L408)

### Suggested Solution

Add a tooltip or a popup to make it clear what this button does.

**Comment by gokadzev** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues and confirmed that this feature is not already requested.
> 
> ### Category of the Feature
> UX Improvements
> 
> ### Credits
> me
> 
> ### Pain
> The purpose of this button on Now Playing page is not clear: ![image](https://private-user-images.githubusercontent.com/108224581/344958921-7a9d713c-0338-42f1-8c00-a27051c86631.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5Mjc1NjYsIm5iZiI6MTcxOTkyNzI2NiwicGF0aCI6Ii8xMDgyMjQ1ODEvMzQ0OTU4OTIxLTdhOWQ3MTNjLTAzMzgtNDJmMS04YzAwLWEyNzA1MWM4NjYzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQxMzM0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTViZGNiOWEwNmJmNjQxODU5ZjE5NTU5NmM1MzM4ZjA5ZmY1ZmU0NDRlMTViOTNiYmMyZDRkMTE5NDdjNmM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.J7xHD592SgWxiMeciRKKy5zHug3Xc8Gb9NTMezobQR4)
> 
> There is no tooltip to communicate that turning on this button will automatically play songs from [this playlist](https://www.youtube.com/playlist?list=PLgzTt0k8mXzEk586ze4BjvDXR7c-TUSnx).
> 
> I was able to understand the functionality of this button only after checking the [source code](https://github.com/gokadzev/Musify/blob/ff31044ae46e4dd57380866db7781bb204c1b7b3/lib/API/musify.dart#L408)
> 
> ### Suggested Solution
> Add a tooltip or a popup to make it clear what this button does.
> 
> ### Useful Resources/References
> _No response_

Generally I don't like tooltips, so I will move this option on settings page then.
