### ISSUE TITLE
Add this app to fdroid

### ISSUE THREAD

**Issue by CodeCubeNeo** [gokadzev/Musify#41]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gokadzev** [comment]
it's already added: https://apt.izzysoft.de/fdroid/index/apk/me.musify

**Comment by CodeCubeNeo** [comment]
I meant to add the app to the main fdroid repo, not through izzysoft
