### ISSUE TITLE
[Feature] <title>

### ISSUE THREAD

**Issue by TheGitGubGuy** [gokadzev/Musify#414]
### Is there an existing issue for this?

- [X] I have searched the existing issues and confirmed that this feature is not already requested.

### Category of the Feature

Unable to categorize

### Credits

My thoughts

### Pain

I don't like that I can't use the Google Play store to download this app. It's a really good happen though, but I just want it to be downloadable from the Play store. My initial thought is that this would be better for the project because more people will be able to access the app who aren't familiar with APK files.

### Suggested Solution

Is it possible for this app to be placed on the Google Play store? If not I want to know why can this be placed on the Play store.

### Useful Resources/References

https://play.google.com/console/signup

**Comment by gokadzev** [comment]
> I don't like that I can't use the Google Play store to download this app. It's a really good happen though, but I just want it to be downloadable from the Play store. My initial thought is that this would be better for the project because more people will be able to access the app who aren't familiar with APK files.

You have multiple options for downloading the app, even if you have no experience with APK files (just click and enable 'unknown sources' for installation). 

> ### Suggested Solution
>  If not I want to know why can this be placed on the Play store.

You can find the answer in #340. I don't generate any revenue, especially from this project, and I work on it for free. I'm also not a fan of using Google Play Store for free open-source projects, nor do I want to pay the $25 fee (which amounts to nearly 50-70% of the total sponsor contributions) or strictly follow to Google Play Store requirements.
