### ISSUE TITLE
whenever i try to click on the music  , it dosent plays

### ISSUE THREAD

**Issue by Spyder-6** [gokadzev/Musify#420]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

whenever i play on the music the music never plays like no existence of the player 

### Expected Behavior

should work normally

### Musify Version

8.50

### Device And Operating System

CMF Phone 1  nothing OS 2.6

### Android Version You Use

Android 14

**Comment by gokadzev** [comment]
It will be fixed in the next release

**Comment by Spyder-6** [comment]
thnx bro ur a saviour on god bro on god , may god bless u . btw whens the next update  release

**Comment by gokadzev** [comment]
> thnx bro ur a saviour on god bro on god , may god bless u . btw whens the next update release

Maximum 10-15 minutes

**Comment by gokadzev** [comment]
Done, Closing the issue as it's solved ✅
