### ISSUE TITLE
[Bug] <title>no longer plays anything 

### ISSUE THREAD

**Issue by Gambeck** [gokadzev/Musify#428]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

The app launches but won't play any song yes I have internet.  I've been using alternate music apps for now but really wish Musify would be working again. Note: there is another app similar to yours called Spotube and it also suffers from same issue and that app also pulls the songs from YouTube so I'm assuming it might not be an issue with your app but something YouTube might be doing to block apps that pull music from YouTube like your app and spotube app. Maybe another work around has to be found I don't know but I hope you can figure it out.

### Expected Behavior

Just look into it please 

### Musify Version

8.5.0

### Device And Operating System

Samsung S20 plus

### Android Version You Use

Android 13

**Comment by gokadzev** [comment]
@Gambeck Hello, a new build without any problems was released 5 days ago. I think you're using the F-Droid build, and since F-Droid takes time to sync and update builds, you will need to wait for it

**Comment by gokadzev** [comment]
> @Gambeck Hello, a new build without any problems was released 5 days ago. I think you're using the F-Droid build, and since F-Droid takes time to sync and update builds, you will need to wait for it

UPDATE: seems like fdroid updated builds too so v8.6.0 is available.
