### ISSUE TITLE
[Bug] <title>issue regarding music not playing 

### ISSUE THREAD

**Issue by Spyder-6** [gokadzev/Musify#431]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

Music not being played . 

### Expected Behavior

Should work normally 

### Musify Version

8.50

### Device And Operating System

CMF Phone 1  nothing OS 2.6

### Android Version You Use

Android 14

**Comment by alfred82santa** [comment]
Same here:

[2024-10-09 21:05:41.882163] Error while getting song streaming URL:YoutubeExplodeException: Video etVYIJ-azLw returned 403 (stream: 135
#0      StreamClient.getManifest.<anonymous closure> (package:youtube_explode_dart/src/videos/streams/stream_client.dart:46)
<asynchronous suspension>
#1      retry (package:youtube_explode_dart/src/retry.dart:16)
<asynchronous suspension>
#2      getAudioUrl (package:musify/API/musify.dart:584)
<asynchronous suspension>
#3      getSong (package:musify/API/musify.dart:566)
<asynchronous suspension>
#4      MusifyAudioHandler.playSong (package:musify/services/audio_service.dart:259)
<asynchronous suspension>
#5      MusifyAudioHandler.playPlaylistSong (package:musify/services/audio_service.dart:276)
<asynchronous suspension>

[2024-10-09 21:05:41.883194] Error playing song:YoutubeExplodeException: Video etVYIJ-azLw returned 403 (stream: 135
#0      StreamClient.getManifest.<anonymous closure> (package:youtube_explode_dart/src/videos/streams/stream_client.dart:46)
<asynchronous suspension>
#1      retry (package:youtube_explode_dart/src/retry.dart:16)
<asynchronous suspension>
#2      getAudioUrl (package:musify/API/musify.dart:584)
<asynchronous suspension>
#3      getSong (package:musify/API/musify.dart:566)
<asynchronous suspension>
#4      MusifyAudioHandler.playSong (package:musify/services/audio_service.dart:259)
<asynchronous suspension>
#5      MusifyAudioHandler.playPlaylistSong (package:musify/services/audio_service.dart:276)
<asynchronous suspension>

[2024-10-09 21:05:48.180599] Error while getting song streaming URL:YoutubeExplodeException: Video si5r94XuGdg returned 403 (stream: 135
#0      StreamClient.getManifest.<anonymous closure> (package:youtube_explode_dart/src/videos/streams/stream_client.dart:46)
<asynchronous suspension>
#1      retry (package:youtube_explode_dart/src/retry.dart:16)
<asynchronous suspension>
#2      getAudioUrl (package:musify/API/musify.dart:584)
<asynchronous suspension>
#3      getSong (package:musify/API/musify.dart:566)
<asynchronous suspension>
#4      MusifyAudioHandler.playSong (package:musify/services/audio_service.dart:259)
<asynchronous suspension>
#5      MusifyAudioHandler.playPlaylistSong (package:musify/services/audio_service.dart:276)
<asynchronous suspension>

[2024-10-09 21:05:48.181146] Error playing song:YoutubeExplodeException: Video si5r94XuGdg returned 403 (stream: 135
#0      StreamClient.getManifest.<anonymous closure> (package:youtube_explode_dart/src/videos/streams/stream_client.dart:46)
<asynchronous suspension>
#1      retry (package:youtube_explode_dart/src/retry.dart:16)
<asynchronous suspension>
#2      getAudioUrl (package:musify/API/musify.dart:584)
<asynchronous suspension>
#3      getSong (package:musify/API/musify.dart:566)
<asynchronous suspension>
#4      MusifyAudioHandler.playSong (package:musify/services/audio_service.dart:259)
<asynchronous suspension>
#5      MusifyAudioHandler.playPlaylistSong (package:musify/services/audio_service.dart:276)
<asynchronous suspension>

[2024-10-09 21:05:51.261299] Error while getting song streaming URL:YoutubeExplodeException: Video si5r94XuGdg returned 403 (stream: 135
#0      StreamClient.getManifest.<anonymous closure> (package:youtube_explode_dart/src/videos/streams/stream_client.dart:46)
<asynchronous suspension>
#1      retry (package:youtube_explode_dart/src/retry.dart:16)
<asynchronous suspension>
#2      getAudioUrl (package:musify/API/musify.dart:584)
<asynchronous suspension>
#3      getSong (package:musify/API/musify.dart:566)
<asynchronous suspension>
#4      MusifyAudioHandler.playSong (package:musify/services/audio_service.dart:259)
<asynchronous suspension>
#5      MusifyAudioHandler.playPlaylistSong (package:musify/services/audio_service.dart:276)
<asynchronous suspension>

[2024-10-09 21:05:51.262279] Error playing song:YoutubeExplodeException: Video si5r94XuGdg returned 403 (stream: 135
#0      StreamClient.getManifest.<anonymous closure> (package:youtube_explode_dart/src/videos/streams/stream_client.dart:46)
<asynchronous suspension>
#1      retry (package:youtube_explode_dart/src/retry.dart:16)
<asynchronous suspension>
#2      getAudioUrl (package:musify/API/musify.dart:584)
<asynchronous suspension>
#3      getSong (package:musify/API/musify.dart:566)
<asynchronous suspension>
#4      MusifyAudioHandler.playSong (package:musify/services/audio_service.dart:259)
<asynchronous suspension>
#5      MusifyAudioHandler.playPlaylistSong (package:musify/services/audio_service.dart:276)
<asynchronous suspension>

**Comment by Spyder-6** [comment]
To Alfred:
IS THIS THE FIX?

**Comment by gokadzev** [comment]
I love Google. (Fix is coming in 10 minutes unless you're using F-Droid build)
