### ISSUE TITLE
[Bug] Dynamic_color package issues

### ISSUE THREAD

**Issue by Zweihandeeer** [gokadzev/Musify#432]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

I'm testing the latest build. Somehow, i can't use anything related to Dynamic_color library. I had to comment all the codelines related to that package and also modify the following files so the app can run normally:

1. -main.dart
2. -app_themes.dart
3. -pubspec.yaml

### Expected Behavior

The thing is, when i do that, the only thing that works is the music search module and the music player. The settings module doesn't work at all, i mean:
1. The color themes doesn't change.
2. The music quality doesn't change.
3. The toggle buttons won't work as intended, they stay static.

### Musify Version

8.6.5

### Device And Operating System

Windows

### Android Version You Use

Android 14

**Comment by gokadzev** [comment]
> ### Acknowledgements
> * [x]  I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
> * [x]  I will fill out all the sections in this issue report.
> 
> ### Current Behavior
> I'm testing the latest build. Somehow, i can't use anything related to Dynamic_color library. I had to comment all the codelines related to that package and also modify the following files so the app can run normally:
> 
> 1. -main.dart
> 2. -app_themes.dart
> 3. -pubspec.yaml
> 
> ### Expected Behavior
> The thing is, when i do that, the only thing that works is the music search module and the music player. The settings module doesn't work at all, i mean:
> 
> 1. The color themes doesn't change.
> 2. The music quality doesn't change.
> 3. The toggle buttons won't work as intended, they stay static.
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Musify Version
> 8.6.5
> 
> ### Device And Operating System
> Windows
> 
> ### Android Version You Use
> Android 14
> 
> ### Additional Information
> _No response_

@Zweihandeeer You've listed unrelated problems with the dynamic_color package here. Are there any errors in the logs? I've tested it on different Android versions (currently testing on Android 14 as well) and even on non-Android devices, but nothing like that has occurred.
