### ISSUE TITLE
[Feature] Add Subsonic/Ampache API support

### ISSUE THREAD

**Issue by mitexleo** [gokadzev/Musify#434]
### Is there an existing issue for this?

- [X] I have searched the existing issues and confirmed that this feature is not already requested.

### Category of the Feature

Logical Improvements, Unable to categorize

### Credits

Only me

### Pain

Currently we can play song from our selfhosted streaming servers like Nextcloud Music, Ampache or Navidrome. 

### Suggested Solution

Add support for Subsonic and Ampache servers so that we can play music from our own servers. 

### Useful Resources/References

Nextcloud Music: https://apps.nextcloud.com/apps/music
Power Ampache 2: https://f-droid.org/packages/luci.sixsixsix.powerampache2.fdroid/

**Comment by gokadzev** [comment]
Sorry, too much work. I already spend much time on the project.
