### ISSUE TITLE
[Bug] custom Library not working/ not showing 

### ISSUE THREAD

**Issue by Spyder-6** [gokadzev/Musify#439]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

When I clicked on the my custom Library button ,  it just loads for infinite 

### Expected Behavior

It should have shown my custom music issued on that list

### Musify Version

Latest one

### Device And Operating System

CMF Phone 1  nothing OS 2.6

### Android Version You Use

Android 14

### Additional Information

Pls help

**Comment by gokadzev** [comment]
@Spyder-6 Does only user playlists have infinite loading spinner or the whole page? also could you check the logs on settings page if there's any?

**Comment by Spyder-6** [comment]
No only the user custom playlist
Everything else works

**Comment by Spyder-6** [comment]
It's saying no logs.

**Comment by gokadzev** [comment]
> No only the user custom playlist Everything else works

It seems an invalid playlist was added, that bypassed my basic validation logic. Okay, I'll take a look. Thanks!

**Comment by Spyder-6** [comment]
Thanks for helping.

**Comment by gokadzev** [comment]
@Spyder-6 If it's not a problem, could you make a backup and share it with me? I'll try to restore it and find the problem

**Comment by gokadzev** [comment]
> @Spyder-6 If it's not a problem, could you make a backup and share it with me? I'll try to restore it and find the problem

Alternatively, I can send a debug build with more loggers in different places if the first option doesn't seem suitable.

**Comment by gokadzev** [comment]
@Spyder-6 any news about this?

**Comment by Spyder-6** [comment]
What you mean by backup can u elaborate please.

**Comment by Spyder-6** [comment]
@gokadzev 

yo its saying i cant send hive files here

**Comment by gokadzev** [comment]
> @gokadzev
> 
> yo its saying i cant send hive files here

archive them as .zip (You can use Zarchiver app)

**Comment by Spyder-6** [comment]
check this man + i cant delete the old playlists too

**Comment by gokadzev** [comment]
Thanks! I'll check it now

**Comment by Spyder-6** [comment]
better

**Comment by gokadzev** [comment]
> better

A more respectful tone would be better. I'd like to remind you that I'm not being paid for this :)

**Comment by gokadzev** [comment]
fixed by e9e4e1169427c0e0e8b68aef0941f7e188716f17

**Comment by Spyder-6** [comment]
no no no sorry sorry i dididnt meant by that, i am  actualy not very good in english ,  i actually wanted to say that that would be better
 not anything bad 
 english is my secnd language

**Comment by Spyder-6** [comment]
> > better
> 
> A more respectful tone would be better. I'd like to remind you that I'm not being paid for this :)

english is not my first language ,
in my native language  better is said in a respectable tone
not in native english type

**Comment by gokadzev** [comment]
> > > better
> > 
> > 
> > A more respectful tone would be better. I'd like to remind you that I'm not being paid for this :)
> 
> english is not my first language , in my native language better is said in a respectable tone not in native english type

Oh, I see, thanks for explaining! No worries at all. I just come across people sometimes who are rude for no reason and think I’m obliged to do whatever they say, so I might have misread the tone. All good!
