### ISSUE TITLE
[Feature] Add Small Window feature

### ISSUE THREAD

**Issue by Korb** [gokadzev/Musify#440]
### Is there an existing issue for this?

- [X] I have searched the existing issues and confirmed that this feature is not already requested.

### Category of the Feature

UI Improvements, More Efficiency

### Credits

Google

### Pain

If the new songs playlist has a lot of tracks that I like and dislike, I often have to open the notification drawer or switch to Musify to see what track is currently playing. This could be avoided by using a floating widget. It's good that Google Android supports this feature out of the box, but the app side also needs support for this feature.

### Suggested Solution

The Small Window (aka **picture-in-picture** mode) feature allows you to display a window overlaying other apps and pin it to the edge of the screen as an always-on small label. The label can be freely moved along the side edges of the screen.

### Useful Resources/References

More details: Android Developers / Develop / Core areas / UI / Guides / [Support multi-window mode](https://developer.android.com/develop/ui/compose/layouts/adaptive/support-multi-window-mode)

**Comment by gokadzev** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues and confirmed that this feature is not already requested.
> 
> ### Category of the Feature
> UI Improvements, More Efficiency
> 
> ### Credits
> Google
> 
> ### Pain
> If the new songs playlist has a lot of tracks that I like and dislike, I often have to open the notification drawer or switch to Musify to see what track is currently playing. This could be avoided by using a floating widget. It's good that Google Android supports this feature out of the box, but the app side also needs support for this feature.
> 
> ### Suggested Solution
> The Small Window (aka **picture-in-picture** mode) feature allows you to display a window overlaying other apps and pin it to the edge of the screen as an always-on small label. The label can be freely moved along the side edges of the screen.
> 
> ### Useful Resources/References
> More details: Android Developers / Develop / Core areas / UI / Guides / [Support multi-window mode](https://developer.android.com/develop/ui/compose/layouts/adaptive/support-multi-window-mode)

Well, in that case I need to make the whole app compatible for smallest screen sizes, am I right?

**Comment by Korb** [comment]
> Well, in that case I need to make the whole app compatible for smallest screen sizes, am I right?

No. The app image is scaled while maintaining the aspect ratio. At least on Funtouch OS 14. In PiP mode, it has two states: **Mini window** and **Small window**. In the first, the app is visible, but you can't interact with it. In the second, the floating window is interactive to the same extent as the app is interactive when it's displayed in full screen mode.

@gokadzev, do you have a chance to see how this feature works in stock Android?

**Comment by gokadzev** [comment]
> > Well, in that case I need to make the whole app compatible for smallest screen sizes, am I right?
> 
> No. The app image is scaled while maintaining the aspect ratio. At least on Funtouch OS 14. In PiP mode, it has two states: **Mini window** and **Small window**. In the first, the app is visible, but you can't interact with it. In the second, the floating window is interactive to the same extent as the app is interactive when it's displayed in full screen mode.
> 
> @gokadzev, do you have a chance to see how this feature works in stock Android?

Yes, but PiP is used for video players, I don't understand how it's gonna work without rewriting UI to be compatible for that size

**Comment by gokadzev** [comment]
> > > Well, in that case I need to make the whole app compatible for smallest screen sizes, am I right?
> > 
> > 
> > No. The app image is scaled while maintaining the aspect ratio. At least on Funtouch OS 14. In PiP mode, it has two states: **Mini window** and **Small window**. In the first, the app is visible, but you can't interact with it. In the second, the floating window is interactive to the same extent as the app is interactive when it's displayed in full screen mode.
> > @gokadzev, do you have a chance to see how this feature works in stock Android?
> 
> Yes, but PiP is used for video players, I don't understand how it's gonna work without rewriting UI to be compatible for that size

@Korb Could you send screenshot how it looks with any other app? So I may understand exactly what we're talking about.

**Comment by Korb** [comment]
Sure.

Standard full-screen view of the application:
![Screenshot_20241117_130927](https://github.com/user-attachments/assets/f5bc4486-d95c-4332-a673-12bdd386b794)

Enabling PiP mode in the running apps manager:
![Screenshot_20241117_131607](https://github.com/user-attachments/assets/dc95384e-77d9-4a30-90b7-a5b426ec8501)

Small window mode:
![Screenshot_20241117_131000](https://github.com/user-attachments/assets/d6ea0f33-1e2a-4087-a048-538c14d08fdf)

Mini Window mode:
![Screenshot_20241117_131038](https://github.com/user-attachments/assets/2004d782-c499-46e0-8322-bf7c47741c16)

Sticker mode (not sure if that's what it's officially called):
![Screenshot_20241117_131009](https://github.com/user-attachments/assets/53482e99-0684-4b6c-bcb1-b6651fd16654)

**Comment by gokadzev** [comment]
As Musify is built with the Flutter framework. If Flutter doesn't support it, unfortunately I can't implement it. Here’s the issue related to it in the Flutter repository: https://github.com/flutter/flutter/issues/134405.

I checked, and in the manifest file, everything is added or enabled as we are using SDK 24.
