### ISSUE TITLE
[Feature] List display on android , tap icons take up too much space

### ISSUE THREAD

**Issue by avagraphique** [gokadzev/Musify#452]
### Is there an existing issue for this?

- [X] I have searched the existing issues and confirmed that this feature is not already requested.

### Category of the Feature

UX Improvements

### Credits

me

### Pain

I have Android 11 and the icons take up half the space in the list rows, it makes the lists almost unusable. 
![462565893_3641006952858716_4128703820077102988_n](https://github.com/user-attachments/assets/c46d8f9e-5dab-45f0-a151-9834ce6bf620)

Changing the accessibility font size setting changes the font size, but not the spacing in any way.

![462550936_428323357040670_7343704736902578063_n](https://github.com/user-attachments/assets/c00135fe-3ea3-4732-a91f-7992ceca837d)

### Suggested Solution

On this view, I mostly only want to know the image, Title/subline text and maybe the add to playlist (plus) icon. 

Suggestion 
- remove the Favorite icon (heart), Offline songs icon (.:!), so those could be omitted as they are on the main player view...
- Append  the duration time (1:23)  to the title or subline instead of a separate column in the row.

Alternative suggestion
- Append  the duration time (1:23)  to the title or subline instead of a separate column in the row.
- Move all the action icons (favorite, offline, add to playlist) to a single icon (vertical dots : maybe?) that will open a menu (lightboxed similar to add a playlist dialog) on tap

### Useful Resources/References

I am running Android 11 on a Moto G POwer (2021)

**Comment by gokadzev** [comment]
Oh well, that really does look bad. However, I'm not sure about removing the action buttons, as I wanted to make it easier for people to add songs to playlists. For example, if someone wants to add 10–15 songs from one playlist to their liked songs or custom playlists, they would need to play each song, open the full playing page, and like them one by one. That would be pretty inconvenient.

I'll think about what can be done about this.

**Comment by gokadzev** [comment]
Marking as done (commits that improve the situation 0dc32e29056168b5f0e1a06284fa2be63c4abf37, 296b8179de89191c1dee844cfb087198e9ecac41)

**Comment by avagraphique** [comment]
Thaks for your quick reply!

> Oh well, that really does look bad. However, I'm not sure about removing the action buttons, as I wanted to make it easier for people to add songs to playlists. For example, if someone wants to add 10–15 songs from one playlist to their liked songs or custom playlists, they would need to play each song, open the full playing page, and like them one by one. That would be pretty inconvenient.
> 

I get this for sure. In my situation though, if I search, I may not know the songs that come up in the result, and often need to listen to part of the song to decide if I want to add it to a playlist.

Another option for handling this is to move the butons underneath the test. This would make the rows (cards) taller and larger but afford more space for the text.

**Comment by gokadzev** [comment]
> Another option for handling this is to move the butons underneath the test. This would make the rows (cards) taller and larger but afford more space for the text.

My temporary solution was to move duration on the artwork image, reduce the spaces between the buttons, and regulate the sizes of the title and artist text. I think it’s a bit better now, but I’ll keep thinking about it. If you come across a better version or find any designs I could take inspiration from, feel free to share them.

**Comment by avagraphique** [comment]
Thank you!

**Comment by nerdCopter** [comment]
I was about to open a feature request for some icon-indicator showing if a song is already made available offline, but then i found this closed-issue.  I really like this older screenshot where user can see all 3 indicators without need for opening a sub-menu.  Maybe some compromise can be made where the icons are smaller and somehow fitted.  Maybe 3 vertical icons could take the space of the single 3-dots icon.  I am unsure, but the old UI speaks for usability and efficiency.

**Comment by avagraphique** [comment]
> Maybe some compromise can be made where the icons are smaller and somehow fitted. Maybe 3 vertical icons could take the space of the single 3-dots icon. I am unsure, but the old UI speaks for usability and efficiency.

I guess it depends on your priority when searching. For me there wasn't enough text in the result to even know if I wanted to add the item to a list, so having the icons there was useless. I much prefer it as it is now, the 3 dot menu, additional tap to get to those other actions. In fact, I more frequently listen to the track first before I decide to add to a playlist so end up using buttons in the player screen.

**Comment by nerdCopter** [comment]
> I guess it depends on your priority ...

sure. my perspective here is setting over a hundred songs to "Make available offline", so more than a 300 taps (100+ triple taps: 3-dots; make available; tap-out)
