### ISSUE TITLE
[Feature] Show playlists as search results, ability to add playlist to library from search result list

### ISSUE THREAD

**Issue by avagraphique** [gokadzev/Musify#453]
### Is there an existing issue for this?

- [X] I have searched the existing issues and confirmed that this feature is not already requested.

### Category of the Feature

UI Improvements

### Credits

me

### Pain

When searching, only single songs show in result list. 
In order to add a youtube playlist , I have to search youtube in another app and bring the url.id back to musify.

### Suggested Solution

Populate search list with playlists as well as single song results

Playlists should be identified as such, perhaps with an icon overlay on the image or prhaps the iage could have a different crop shape (ex. square instead of rounded).

Choosing + to all should add a playlist to the library.

**Comment by avagraphique** [comment]
Oh I see, that is cool. I think for me it was not clear, becasue I think of "Library" as my local lists (phone) that I have collected. Ex. liking playlists and songs. Like my CD rack at home...
And "Search" being searching YouTube... For things to discover... Like the CD store...

One thing I noticed on the Library page, searching sems to only apply to the "Playlists" and "Albums" buttons (filter) are toggled, and no effect on the "User playlists" and "Liked playlists", so perhaps the search filters could be moved to the search page as per your suggestion.

**Comment by gokadzev** [comment]
> Oh I see, that is cool. I think for me it was not clear, becasue I think of "Library" as my local lists (phone) that I have collected. Ex. liking playlists and songs. Like my CD rack at home... And "Search" being searching YouTube... For things to discover... Like the CD store...
> 
> One thing I noticed on the Library page, searching sems to only apply to the "Playlists" and "Albums" buttons (filter) are toggled, and no effect on the "User playlists" and "Liked playlists", so perhaps the search filters could be moved to the search page as per your suggestion.

yeah, valid. I missed that part while redesigning library page and moving things there, so I think I'll definitely change it.
