### ISSUE TITLE
[Bug] Playlist doesn't update when songs get added to it

### ISSUE THREAD

**Issue by Heinrich-XIAO** [gokadzev/Musify#461]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [ ] I will fill out all the sections in this issue report.

### Current Behavior

When adding a song to a playlist, I have to leave the playlist and come back for it to update.

### Expected Behavior

It should show up immediately.

### Steps To Reproduce

1. Make a playlist.
2. Open it in the library tab.
3. Add a song to the playlist.
4. Observe that it doesn't appear.

### Musify Version

latest

### Device And Operating System

Huawei IDK the device name and its not realivent

### Android Version You Use

IDK

**Comment by gokadzev** [comment]
Ah yes, I was aware of this but I was lazy to fix that :D yeah, I'll look at it later

**Comment by gokadzev** [comment]
The best case I could found was adding sync button in the app bar, that will be valid for this I believe
