### ISSUE TITLE
Playing only parts of a song 

### ISSUE THREAD

**Issue by Heinrich-XIAO** [gokadzev/Musify#462]
### Is there an existing issue for this?

- [X] I have searched the existing issues and confirmed that this feature is not already requested.

### Category of the Feature

Unable to categorize

### Credits

Me

### Pain

I have to manually stop the song where I want the song to end. I sometimes only like some of the song but then I have to start and stop it myself. 

### Suggested Solution

It would be great if there was a "song profile" so I can play only some parts of the song. A song profile should be a profile to control how a song gets played ie the start and end times.

**Comment by Heinrich-XIAO** [comment]
A song profile should be able to be used for other things as well like audio balancing, and other aspects of playing songs.

**Comment by gokadzev** [comment]
That's not really something I'd like to work on. If it's about extra seconds coming from videos, SponsorBlock does its job.

**Comment by Heinrich-XIAO** [comment]
Its not about ads or anything its just that there are parts of songs that I like more than others. Its about playing different songs in different ways.

**Comment by Heinrich-XIAO** [comment]
Some songs are inherently louder than others and I want to have it play quieter so I have a consistent volume throughout a playlist.

**Comment by Heinrich-XIAO** [comment]
Also, I could work on this myself.

**Comment by gokadzev** [comment]
> Some songs are inherently louder than others and I want to have it play quieter so I have a consistent volume throughout a playlist.

Either I don't understand what you mean and I thought I did or you're suggesting several features here. I don't see any connection between this and what you said above

**Comment by Heinrich-XIAO** [comment]
You may not be understanding it. I'm saying you would be able to change how songs are played in volume, start time, end time and more.

**Comment by Heinrich-XIAO** [comment]
I already have it done, but not with the start and end times parts because I started with volume because I thought it would've been easier. I will still do the start and end times if this feature is deemed useful.
