### ISSUE TITLE
[Bug] <title>the song doesn't go to the next song and the player stays in a restart position 

### ISSUE THREAD

**Issue by Spyder-6** [gokadzev/Musify#469]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

On completion of a track , the players stays on the song even after there is song in  the up next option in a playlist 

### Expected Behavior

Should go to next track 

### Musify Version

Latest one

### Device And Operating System

CMF Phone 1  nothing OS 2.6

### Android Version You Use

Android 14

**Comment by Spyder-6** [comment]
Update: the app stopped totally like u can only play a single music file and that's it it then stays stagnant

**Comment by gokadzev** [comment]
> Update: the app stopped totally like u can only play a single music file and that's it it then stays stagnant

@Spyder-6 about this, what about now? it it the same?

**Comment by Spyder-6** [comment]
Yea bro, same problem happend with my friend to , the songs are totally freezed

**Comment by Spyder-6** [comment]
Imo

It is still the same only some songs are being played and no search results works

**Comment by gokadzev** [comment]
> Imo
> 
> It is still the same only some songs are being played and no search results works

Can you try to clear app data (backup if you have anything important there and then you'll be able to restore) and try to play the same song that wasn't playing before clearing the app data? If it works tell me and I might get an idea what's the potential problem

**Comment by Spyder-6** [comment]
Same issue bro I downloaded the latest version the playback problem is still there. I did a lot of things like u said clear app cache and data

**Comment by gokadzev** [comment]
> Same issue bro I downloaded the latest version the playback problem is still there. I did a lot of things like u said clear app cache and data

Strange, I'm checking and everything is playing without problem

**Comment by gokadzev** [comment]
Yeah, just found out. it should be fixed with V9.0.4
