### ISSUE TITLE
[Bug] Shuffle

### ISSUE THREAD

**Issue by Heinrich-XIAO** [gokadzev/Musify#472]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

Shuffle does not continue picking random songs when playing last song. 

### Expected Behavior

It should keep choosing random songs in the playlist. 

### Steps To Reproduce

1. Get playlist of more than one song.
2. Play until playing the last song.
3. Wait till the song finishes or put the player to the end
4. It just stops unlike every other time. 

### Musify Version

Latest

### Device And Operating System

Huawei

### Android Version You Use

Android 15

**Comment by gokadzev** [comment]
> ### Acknowledgements
> * [x]  I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
> * [x]  I will fill out all the sections in this issue report.
> 
> ### Current Behavior
> Shuffle does not continue picking random songs when playing last song.
> 
> ### Expected Behavior
> It should keep choosing random songs in the playlist.
> 
> ### Steps To Reproduce
> 1. Get playlist of more than one song.
> 2. Play until playing the last song.
> 3. Wait till the song finishes or put the player to the end
> 4. It just stops unlike every other time.
> 
> ### Musify Version
> Latest
> 
> ### Device And Operating System
> Huawei
> 
> ### Android Version You Use
> Android 15
> 
> ### Additional Information
> _No response_

That's not shuffle but repeat function for playlist that isn't added tho

**Comment by Heinrich-XIAO** [comment]
No, shuffle actually does repeat, just stops at the last one, it's theoretically possible for it to just play the first few forever, but whenever it reaches the last song it halts.

**Comment by gokadzev** [comment]
> No, shuffle actually does repeat, just stops at the last one, it's theoretically possible for it to just play the first few forever, but whenever it reaches the last song it halts.

I think you might have misunderstood what shuffle feature means.

**Comment by Heinrich-XIAO** [comment]
It is exactly what it does except for the last song. It plays random songs forever, but here it plays forever until it gets to the last song by shear chance.

**Comment by Heinrich-XIAO** [comment]
> > No, shuffle actually does repeat, just stops at the last one, it's theoretically possible for it to just play the first few forever, but whenever it reaches the last song it halts.
> 
> I think you might have misunderstood what shuffle feature means.

The code suggests it was intended to keep playing random songs. It's just that there is an edge case where it instead stops because it doesn't check if shuffle is on and goes the next conditions which stops the player.

**Comment by gokadzev** [comment]
> It is exactly what it does except for the last song. It plays random songs forever, but here it plays forever until it gets to the last song by shear chance.

Do you have repeat all feature enabled as well?

**Comment by Heinrich-XIAO** [comment]
No, repeat all is disabled. repeat is disabled.
![Screenshot_20241225_102101](https://github.com/user-attachments/assets/9a8e0285-a97d-4406-89ad-9430a4553e95)
This is where the bug takes place.

**Comment by Heinrich-XIAO** [comment]
The `skipToSong` function suggests that if `shuffleNotifier.value`, it chooses a random song and plays it. This wouldn't make sense unless it was intended to get run even when playing the last song (which it isn't and is where the bug takes place). 
![image](https://github.com/user-attachments/assets/d8b584c3-8f00-44ca-9b02-2efa99504383)
The shuffle functionality does do this as long as it never hits the last song by **chance**. It does **NOT** play in order and that is **NOT** what I am suggesting it should do.

**Comment by gokadzev** [comment]
> The `skipToSong` function suggests that if `shuffleNotifier.value`, it chooses a random song and plays it. This wouldn't make sense unless it was intended to get run even when playing the last song (which it isn't and is where the bug takes place). ![image](https://private-user-images.githubusercontent.com/74563446/398584823-d8b584c3-8f00-44ca-9b02-2efa99504383.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNDI1MzQsIm5iZiI6MTczNTE0MjIzNCwicGF0aCI6Ii83NDU2MzQ0Ni8zOTg1ODQ4MjMtZDhiNTg0YzMtOGYwMC00NGNhLTliMDItMmVmYTk5NTA0MzgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDE1NTcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ZWQxM2ExZmE1NDQyZjhjZDAyODJhYzhmYTczNDZmOWRhZjUwZTE2YTZjMzdiZTc3ZTBjMTY4ZWQ1NzRhYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4xUTdrK_tGKRXy93_0C_dg_gPlvG6YTsTPnFq7NMTdg) The shuffle functionality does do this as long as it never hits the last song by **chance**. It does **NOT** play in order and that is **NOT** what I am suggesting it should do.

Still couldn't catch what's the problem. is it that it plays every song in playlist except the last one?

**Comment by Heinrich-XIAO** [comment]
> > The `skipToSong` function suggests that if `shuffleNotifier.value`, it chooses a random song and plays it. This wouldn't make sense unless it was intended to get run even when playing the last song (which it isn't and is where the bug takes place). ![image](https://private-user-images.githubusercontent.com/74563446/398584823-d8b584c3-8f00-44ca-9b02-2efa99504383.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNDI1MzQsIm5iZiI6MTczNTE0MjIzNCwicGF0aCI6Ii83NDU2MzQ0Ni8zOTg1ODQ4MjMtZDhiNTg0YzMtOGYwMC00NGNhLTliMDItMmVmYTk5NTA0MzgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDE1NTcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ZWQxM2ExZmE1NDQyZjhjZDAyODJhYzhmYTczNDZmOWRhZjUwZTE2YTZjMzdiZTc3ZTBjMTY4ZWQ1NzRhYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4xUTdrK_tGKRXy93_0C_dg_gPlvG6YTsTPnFq7NMTdg) The shuffle functionality does do this as long as it never hits the last song by **chance**. It does **NOT** play in order and that is **NOT** what I am suggesting it should do.
> 
> Still couldn't catch what's the problem. is it that it plays every song in playlist except the last one?

No. Here is a recording of what can happen.

https://github.com/user-attachments/assets/fd441fb9-9e37-4f6b-b789-9cd8f854eebe

It keeps playing random songs until it stops at the last one.

**Comment by Heinrich-XIAO** [comment]
It means that I can't just leave it on shuffle and expect it to keep playing songs like every other song-playing app.

**Comment by Heinrich-XIAO** [comment]
In this case, `geometry dash official theme song` was the last song, and therefore did not keep playing random songs.
