### ISSUE TITLE
[Bug] fdroid versions

### ISSUE THREAD

**Issue by Heinrich-XIAO** [gokadzev/Musify#474]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

The fdroid version is usually behind by a few updates.

### Expected Behavior

the fdroid version should be the latest update, since it gets built for fdroid anyways.

### Musify Version

any of them everywhere all at once

### Device And Operating System

aejkrklawerjklklj;wer

### Android Version You Use

Android 15

**Comment by gokadzev** [comment]
Fdroid takes several day to sync updates and build and that's normal. Do you want the latest update faster? use GitHub version
