### ISSUE TITLE
French isn't available in the language selection 

### ISSUE THREAD

**Issue by gabouriel** [gokadzev/Musify#50]
French isn't available in the language selection despite the app_fr.abrb file in lib/localization
![Screenshot_2022-07-17-00-41-48-75.jpg](https://user-images.githubusercontent.com/97214417/179374088-147cab2a-de92-4df7-94ce-7c9e5dc155db.jpg)
![Screenshot_2022-07-17-00-41-59-78.jpg](https://user-images.githubusercontent.com/97214417/179374092-7e821d63-f4e6-479a-a3f2-78aff9925340.jpg)

**Comment by gokadzev** [comment]
> French isn't available in the language selection despite the app_fr.abrb file in lib/localization ![Screenshot_2022-07-17-00-41-48-75.jpg](https://user-images.githubusercontent.com/97214417/179374088-147cab2a-de92-4df7-94ce-7c9e5dc155db.jpg) ![Screenshot_2022-07-17-00-41-59-78.jpg](https://user-images.githubusercontent.com/97214417/179374092-7e821d63-f4e6-479a-a3f2-78aff9925340.jpg)

because it is not translated, if you wish i can give you text file and translate it, then send it here and i will add in next release. (you can make pr as well)

**Comment by RAZ321** [comment]
hey, i can do that i fou you want to send me the text file :)

**Comment by gokadzev** [comment]
> hey, i can do that i fou you want to send me the text file :)

sure :)
[fr.txt](https://github.com/gokadzev/Musify/files/9403261/fr.txt)

**Comment by RAZ321** [comment]
this is the french version ;)
[fr.txt](https://github.com/gokadzev/Musify/files/9403434/fr.txt)

**Comment by gokadzev** [comment]
> this is the french version ;) [fr.txt](https://github.com/gokadzev/Musify/files/9403434/fr.txt)

it will be available in the next version, thanks :)

**Comment by RAZ321** [comment]
np
