### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by senolfndk** [gokadzev/Musify#51]
### Steps to reproduce

same problem persists boot and connection speed is very slow and crashes

### Expected behavior

same problem persists boot and connection speed is very slow and crashes

### Actual behavior

same problem persists boot and connection speed is very slow and crashes

### Musify version

2.4.0

### Android version

android 11

### Other details

Why did you close the telegram page, which will be my off-topic question

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
- [X] I will fill out all

**Comment by gokadzev** [comment]
@senolfndk i need logs, otherwise i won't be able to find the reason of the crashing, because it seems problem is only on your device since i test it on 2 devices and it's smooth + doesn't crash.

**Comment by senolfndk** [comment]
how to make a diary

**Comment by gokadzev** [comment]
> how to make a diary

if you mean how to take logs:

app - https://play.google.com/store/apps/details?id=com.pluscubed.matlog&hl=ka&gl=US

instructions - https://www.celsoazevedo.com/files/android/how-to-save-logcat/

after you will start logging with Matlog, open Musify and wait before it will be crashed or whatever, then open Matlog and save logs as it's in instruction/video. then send them here

**Comment by senolfndk** [comment]
let me tell you the app freezes and hangs and suddenly closes while browsing

**Comment by senolfndk** [comment]
I can't record screen, app locks phone

**Comment by gokadzev** [comment]
> let me tell you the app freezes and hangs and suddenly closes while browsing

you can make logs with pc too. sorry, i can't do anything if i haven't logs since i haven't that problem when i open app.
