### ISSUE TITLE
Categories in Search section 

### ISSUE THREAD

**Issue by MrConqueror** [gokadzev/Musify#53]
### Describe your suggested feature

![Screenshot_2022-07-23-16-32-00-33_336682e91f254026b7419f73ea808126](https://user-images.githubusercontent.com/102837820/180597336-3b213d1d-98f3-45bb-8cbc-c8a92192baf2.jpg)
Can you put those playlist/category or whatever it is called in search section like this?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by gokadzev** [comment]
> ### Describe your suggested feature
> ![Screenshot_2022-07-23-16-32-00-33_336682e91f254026b7419f73ea808126](https://user-images.githubusercontent.com/102837820/180597336-3b213d1d-98f3-45bb-8cbc-c8a92192baf2.jpg) Can you put those playlist/category or whatever it is called in search section like this?
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I will fill out all of the requested information in this form.

there's search history in that place. if i will do that, i need to remove or move search history, which i don't think will be correct.
