### ISSUE TITLE
Clean UI, Design, and Organize

### ISSUE THREAD

**Issue by MrConqueror** [gokadzev/Musify#54]
### Describe your suggested feature

when we search a certain song please make it like this, looks clean. Don't put them inside a rectangle like those Songs in recommend for you in homepage.

### Other details

![Screenshot_2022-07-23-16-37-47-71](https://user-images.githubusercontent.com/102837820/180597557-72885d19-a925-4a28-9947-6167330ab2ac.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by owencz1998** [comment]
What app is that dude

**Comment by MrConqueror** [comment]
> What app is that dude

eSound It's available in Playstore you can download the song to listen offline it's free but has ads but not annoying one

**Comment by owencz1998** [comment]
Nice one thanks mate
