### ISSUE TITLE
Better German Translation

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [gokadzev/Musify#56]
{
  "about": "Über",
  "accentChangeMsg": "Akzentfarbe wurde geändert",
  "accentColor": "Akzentfarbe",
  "add": "Hinzufügen",
  "appUpdateAvailableAndDownloading": "Update ist verfügbar und wird heruntergeladen",
  "appUpdateIsAvailable": "Update ist verfügbar",
  "appUpdateIsNotAvailable": "Kein Update verfügbar",
  "audioFileType": "Audiodateierweiterung",
  "audioFileTypeMsg": "Der Audiodateityp wurde geändert",
  "backupUserData": "Sicherung von Benutzerdaten",
  "backupedSuccessfully": "Erfolgreich gesichert",
  "cacheMsg": "Cache gelöscht",
  "clearCache": "Cache leeren",
  "clearSearchHistory": "Suchverlauf löschen",
  "downloadAppUpdate": "Update herunterladen",
  "language": "Sprache",
  "languageMsg": "Sprache wurde geändert",
  "localSongs": "Lokale Lieder",
  "lyrics": "Liedtext",
  "lyricsNotAvailable": "Keine Liedtexte verfügbar ;(",
  "nowPlaying": "Läuft gerade",
  "playAll": "Alle wiedergeben",
  "playlist": "Wiedergabeliste",
  "playlists": "Wiedergabelisten",
  "queueInitText": "Warteschlange wird initialisiert... aus Leistungsgründen werden nur die ersten 20 Songs in die Warteschlange aufgenommen.",
  "recommendedForYou": "für Dich empfohlen",
  "restoreUserData": "Wiederherstellen von Benutzerdaten",
  "restoredSuccessfully": "Erfolgreich wiederhergestellt",
  "search": "Suche",
  "searchHistoryMsg": "Suchverlauf gelöscht",
  "settings": "Einstellungen",
  "suggestedPlaylists": "Vorgeschlagene Wiedergabelisten",
  "userLikedSongs": "beliebte Lieder",
  "userPlaylists": "Wiedergabelisten",
  "yourDownloadedSongsHere": "heruntergeladenen Lieder",
  "yourFavoriteSongsHere": "Lieblingslieder",
  "youtubePlaylistID": "Youtube-Playlist ID"
}

**Comment by gokadzev** [comment]
Thanks, will be changed in the next update.
