### ISSUE TITLE
Maybe extend this app to the desktop?

### ISSUE THREAD

**Issue by CodeCubeNeo** [gokadzev/Musify#57]
### Describe your suggested feature

Hello. This is just an idea, to also adjust your app for the desktop. Please share your thoughts.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by senolfndk** [comment]
Could you please take a video and upload it? I want to see how the application works, I get stuck and it freezes.

**Comment by gokadzev** [comment]
> ### Describe your suggested feature
> Hello. This is just an idea, to also adjust your app for the desktop. Please share your thoughts.
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I will fill out all of the requested information in this form.

it needs UI changes + additional plugins and implementations, since we can listen songs on background with even browser on pc currently i'm not thinking to add desktop support.
