### ISSUE TITLE
Download doesn't work

### ISSUE THREAD

**Issue by sm32d** [gokadzev/Musify#58]
### Steps to reproduce

Press the download button in any song

### Expected behavior

Should save a file to local storage

### Actual behavior

No file downloaded

### Musify version

2.6.0

### Android version

Android 12

### Other details

On MIUI

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
- [x] I will fill out all

**Comment by gokadzev** [comment]
@sm32d check app permissions

**Comment by sm32d** [comment]
> @sm32d check app permissions

![Screenshot_2022-07-25-00-32-45-015_com miui securitycenter](https://user-images.githubusercontent.com/64636803/180657071-742495d2-9b8d-429e-a01b-6bb027fb774e.jpg)
Seems alright

**Comment by gokadzev** [comment]
@sm32d  which MIUI version?

**Comment by sm32d** [comment]
> @sm32d which MIUI version?

MIUI 13.0.6 on Android 12

**Comment by gokadzev** [comment]
> > @sm32d which MIUI version?
> 
> MIUI 13.0.6 on Android 12

does it show local songs in app?

**Comment by sm32d** [comment]
> > > @sm32d which MIUI version?
> > 
> > 
> > MIUI 13.0.6 on Android 12
> 
> does it show local songs in app?

Yes, it does.

**Comment by gokadzev** [comment]
> > > > @sm32d which MIUI version?
> > > 
> > > 
> > > MIUI 13.0.6 on Android 12
> > 
> > 
> > does it show local songs in app?
> 
> Yes, it does.

i need exact description what it does (also check Musify or Downloads folders) or i will need logs

**Comment by sm32d** [comment]
> > > > > @sm32d which MIUI version?
> > > > 
> > > > 
> > > > MIUI 13.0.6 on Android 12
> > > 
> > > 
> > > does it show local songs in app?
> > 
> > 
> > Yes, it does.
> 
> i need exact description what it does (also check Musify or Downloads folders) or i will need logs

Here is a screen recording of what happens.
https://disk.yandex.com/i/wekMu3NiHpq33g

**Comment by gokadzev** [comment]
> > > > > > @sm32d which MIUI version?
> > > > > 
> > > > > 
> > > > > MIUI 13.0.6 on Android 12
> > > > 
> > > > 
> > > > does it show local songs in app?
> > > 
> > > 
> > > Yes, it does.
> > 
> > 
> > i need exact description what it does (also check Musify or Downloads folders) or i will need logs
> 
> Here is a screen recording of what happens. https://disk.yandex.com/i/wekMu3NiHpq33g

i will see and try to release fixed version in 2.6.1

**Comment by sm32d** [comment]
Thanks!
Loved the streaming, by the way. Great work. Hopefully the downloads work in the next release.

**Comment by gokadzev** [comment]
local songs aren't updating list when i download new song and i will review that later, but song download problem is fixed (songs are downloaded in root/Musify folder)
