### ISSUE TITLE
Lyrics don't work

### ISSUE THREAD

**Issue by Oopsiedai** [gokadzev/Musify#62]
### Steps to reproduce

1. Start the app
2. Search any song
3. Press the lyrics button

### Expected behavior

It should show now the songtexts/lyrics.

### Actual behavior

But it just loads and nothing happens.

### Musify version

2.8.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
- [ ] I will fill out all

**Comment by gokadzev** [comment]
@Oopsiedai it works, just sometimes api is so slow and that's why it needs more time

**Comment by Oopsiedai** [comment]
Hm, ok, i tried it again and if the Song is downloaded the Lyrics show up, but if i try any other song it just says "No lyrics available :(". It dont even show the loading circle then.
