### ISSUE TITLE
Download song doesn't work 

### ISSUE THREAD

**Issue by RyanLru** [gokadzev/Musify#63]
### Steps to reproduce

Open app
Search song
Click download button 

### Expected behavior

It's suppose launch download

### Actual behavior

However it doesn't launch nothings appear 

### Musify version

2.8

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
- [X] I will fill out all

**Comment by gokadzev** [comment]
@RyanLru have you checked Musify folder?

**Comment by RyanLru** [comment]
> @RyanLru have you checked Musify folder?

Yes a check nothings appear here because I didn't have musify folder

**Comment by gokadzev** [comment]
> > @RyanLru have you checked Musify folder?
> 
> Yes a check nothings appear here because I didn't have musify folder

check storage permissions and also access all files permisions which is required since Android 11

**Comment by RyanLru** [comment]
> > > @RyanLru have you checked Musify folder?
> > 
> > Yes a check nothings appear here because I didn't have musify folder
> 
> check storage permissions and also access all files permisions which is required since Android 11

Yes I check that and I allow storage permissions but it stay doesn't work
