### ISSUE TITLE
Add quality control option.

### ISSUE THREAD

**Issue by max5354** [gokadzev/Musify#7]
Will you add quality control option. So we can change the quality of audio like (low,medium,high)? This option also available in YouTube music.

**Comment by max5354** [comment]
Sorry to interrupt you. But I just want to know that how much time it will take to add #7 feature or  "audio quality change" option?

**Comment by gokadzev** [comment]
> Sorry to interrupt you. But I just want to know that how much time it will take to add #7 feature or "audio quality change" option?

There are more important things to add/change in app, so i don't know exactly. no ETA please.

**Comment by gokadzev** [comment]
> Sorry to interrupt you. But I just want to know that how much time it will take to add #7 feature or "audio quality change" option?


There are more important things which i need to add/change in app, so i don't know exactly. no ETA please.
