### ISSUE TITLE
Browse Channel

### ISSUE THREAD

**Issue by saracenz4** [gokadzev/Musify#75]
Hey can you add support for browsing music from a youtube channel

**Comment by gokadzev** [comment]
> Hey can you add support for browsing music from a youtube channel

in my opinion, that's not feature which music player app should have. (at least with channel form where you will see tons of other off topic channels.)

**Comment by saracenz4** [comment]
There are tons of youtube playlist created by users.eg Some movie OST
It doesn't appear in playlist search

**Comment by gokadzev** [comment]
> There are tons of youtube playlist created by users.eg Some movie OST It doesn't appear in playlist search

now i understand, yes that is possible. open new issue about it (example with title: make possible to search playlists dinamically) with your own description how do you want to work it and will see, maybe i will add it for v3.0.0
