### ISSUE TITLE
How to setup the project ?

### ISSUE THREAD

**Issue by RAZ321** [gokadzev/Musify#79]
**Hi,**
Can you explain me how to build the project for IOS & Android ? Because i'm new to Dart language and Phone Apps 💻, It will help me understand the language better. 
Thank you very much. 😀

**Comment by gokadzev** [comment]
> **Hi,** Can you explain me how to build the project for IOS & Android ? Because i'm new to Dart language and Phone Apps computer, It will help me understand the language better. Thank you very much.

Hello, you can use this links to get information about it :

https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1#0
https://docs.flutter.dev/get-started/test-drive?tab=terminal#terminal
