### ISSUE TITLE
Ui glitch

### ISSUE THREAD

**Issue by wikd** [gokadzev/Musify#84]
### Steps to reproduce

Launch app, tap search input area. Also just randomly does it.

### Expected behavior

Expect ui to not glitch.

### Actual behavior

Tap search and ui goes bonkers.
![Screenshot_20220822-191117_Musify](https://user-images.githubusercontent.com/30180247/186035960-92e901f6-11a7-4ccc-873e-0f2e5e7d2573.png)

### Musify version

version 3.0.1

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
- [X] I will fill out all

**Comment by gokadzev** [comment]
@wikd does it happen on the playlists page too?

**Comment by wikd** [comment]
Yes, it does exact same thing.
![Screenshot_20220823-062933_Musify](https://user-images.githubusercontent.com/30180247/186136318-1222e603-70fd-4ec0-8b27-4a2f013f00b5.png)

**Comment by gokadzev** [comment]
> Yes, it does exact same thing. ![Screenshot_20220823-062933_Musify](https://user-images.githubusercontent.com/30180247/186136318-1222e603-70fd-4ec0-8b27-4a2f013f00b5.png)

very interesting, it works good for me. i will try to find out what's problem

**Comment by Tolga077** [comment]
The same thing happens on another android 11 device. But it works fine on another device with android 8. I think this is a flutter related problem, it happens in some other flutter applications as well.

**Comment by wikd** [comment]
Here's a better example as to what it's doing.


https://user-images.githubusercontent.com/30180247/186269545-c84e0c94-988c-4741-ad00-5c014bfbfe9a.mp4
