### ISSUE TITLE
Ios Mobile Version !

### ISSUE THREAD

**Issue by RAZ321** [gokadzev/Musify#85]
### Why ?
Because IOS (iphone) users cannot download this beautiful app. Moreover, it remains that this platform so that Musify is available to all mobiles platforms ! 🎉

### Suggested Solution
I think you juste need to adapt the android version in ios, there is the swift language for ios apps or objective-c for this, after that you juste need to generate a .ipa downloadable on the [website page](https://gokadzev.github.io/Musify) (it will directly install the app on the home screen) 😀

### Useful resources/references

[Swift 🕊](https://developer.apple.com/swift/)
[Objective-©](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Introduction/Introduction.html)
[Create an ios app 📱](https://devmountain.com/blog/how-to-create-an-ios-app/)
[Many others languages 😎](https://developer.apple.com/develop/)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by RAZ321** [comment]
some news ?

**Comment by gokadzev** [comment]
> hi, some news ?

it needs Xcode (mac os) and some changes to make it work. since i haven't mac and also i won't be able to test it, we need to wait for anyone who will do it.

**Comment by RAZ321** [comment]
It require a mac ?

**Comment by gokadzev** [comment]
> It require a mac ?

yes

**Comment by RAZ321** [comment]
macOs emulators doesn't work ?

**Comment by gokadzev** [comment]
> macOs emulators doesn't work ?

I'm sure it will need various changes to make it work for ios, so currently there's needed anyone who has a mac and iPhone and at least a little bit experience.

update: branch for ios: https://github.com/gokadzev/Musify/tree/ios-support

**Comment by RAZ321** [comment]
my gf just got a mac so i can ask her to test the it ?

**Comment by SoCuul** [comment]
Hey, I have some experience in the iOS development world. Could I be of any help?
