### ISSUE TITLE
user playlist

### ISSUE THREAD

**Issue by tahrel** [gokadzev/Musify#96]
### Describe your suggested feature

I want to make my own playlist can you add this feature

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by gokadzev** [comment]
> ### Describe your suggested feature
> I want to make my own playlist can you add this feature
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I will fill out all of the requested information in this form.

Hello, you can:

1. create playlist on Youtube with your wanted songs, make its privacy unlisted or public, copy playlist ID and add it to user playlists in Musify
2. like your favorite songs
