### ISSUE TITLE
[🐞BUG] App Won't Open

### ISSUE THREAD

**Issue by Muteplayer** [gokadzev/Musify#97]
### Steps to reproduce

Open app

### Expected behavior

App open and display home page

### Actual behavior

App open but do not display anything else a gray background

### Musify version

3.2.0

### Android version

Android 12L (12.1)

### Other details

![Screenshot_20220907-194046_Musify](https://user-images.githubusercontent.com/107940851/188996985-a85d7785-cc38-4cc4-917e-faa1cb6359b9.png)

[2022-09-07-19-48-51.log](https://github.com/gokadzev/Musify/files/9522036/2022-09-07-19-48-51.log)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
- [X] I will fill out all

**Comment by gokadzev** [comment]
@Muteplayer  Hello, could you try this test build? (i don't have Android 12 to test it so...)

[Musify-test-release.apk.zip](https://github.com/gokadzev/Musify/files/9523671/Musify-test-release.apk.zip)

**Comment by gokadzev** [comment]
@Muteplayer let's try this one

[Musify-test-release1.apk.zip](https://github.com/gokadzev/Musify/files/9524403/Musify-test-release1.apk.zip)

**Comment by gokadzev** [comment]
@Muteplayer i have doubt that it's about splash screen, i hope this works

[Musify-test-release2.apk.zip](https://github.com/gokadzev/Musify/files/9532772/Musify-test-release2.apk.zip)

**Comment by gokadzev** [comment]
> If I can provide other type of log please tell me, I have root btw

@Muteplayer Is app crashing? or it is just stuck on the splash screen (black window)

**Comment by gokadzev** [comment]
@Muteplayer try to grant all permission manually for app

**Comment by gokadzev** [comment]
> I get back to Android 11 and still not open

i use android 11 as well, also there are people who tested it on as android 11 as android 12 and told me that it is working perfectly

**Comment by BNX070** [comment]
I'm facing the exactly same issue on Android 10. The app launches but is stuck on the splash screen.

**Comment by gokadzev** [comment]
> I'm facing the exactly same issue on Android 10. The app launches but is stuck on the splash screen.

hello, could you write below requested information?

Device full name: (Example: Xiaomi redmi xx)
Android: Android X (Stock (original rom) or custom rom)
Is there any version which works?

**Comment by gokadzev** [comment]
@Muteplayer check the latest version

**Comment by BNX070** [comment]
The issue is still there... 2.9.0 is the last working ver

**Comment by gokadzev** [comment]
checked on Android 12 and it works as well, if the problem is still active then maybe there's problem with your OS. if you find anything what can lead me and show me that problem is related to the app, feel free to reopen this issue.
